#!/usr/bin/env python3
"""Build Protocol-v14.7 mechanical semantic closure artifacts deterministically."""
from __future__ import annotations
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HIST=ROOT/'historical-source';COMP=HIST/'compliance';V145=COMP/'certification/v14.5';DEST=COMP/'certification/v14.7';SCHEMA=DEST/'schema';VERSION='14.7'
MACHINE_FILES=['VERSION.yaml','SCOPE.yaml','V14.6-AUDIT-FINDINGS.yaml','CONTRADICTIONS.yaml','AMBIGUITIES.yaml','CANONICAL-DOMAIN-MODEL.yaml','EVALUATION-MODEL.yaml','EVALUATION-REPRODUCIBILITY.yaml','AUTHORITY-MODEL.yaml','AUTHORITY-CAPABILITY-REGISTRY.yaml','FAIL-CLOSED-MATRIX.yaml','PRECEDENCE-MODEL.yaml','DERIVED-STATE-CLASSIFICATION.yaml','TEMPORAL-SEMANTICS.yaml','IDENTITY-MODEL.yaml','IDENTITY-PROFILES.yaml','CERTIFICATE-REUSE-PREDICATE.yaml','CERTIFICATE-ISSUANCE-REUSE-PREDICATE.yaml','DECISION-REUSE-PREDICATE.yaml','DECISION-BASIS-CHANGE-ACTIONS.yaml','STATE-TRANSITION-TABLES.yaml','STATE-MACHINE-AUDIT.yaml','EVENT-SOURCING-MODEL.yaml','PROJECTION-ALGORITHMS.yaml','CONCURRENCY-MODEL.yaml','VALIDATION-PROCEDURE.yaml','FAILURE-TAXONOMY.yaml','TEST-VECTORS.yaml','INVARIANTS.yaml','TRACEABILITY.yaml','EPISTEMIC-REGISTER.yaml','ANTI-REGRESSION.yaml','ARTIFACT-TREE.yaml','OPEN-QUESTIONS.yaml','FINAL-PRINCIPLE.yaml','CURRENT-STATUS.yaml','EVENT-HISTORIES.yaml','CURRENT-PROJECTIONS.yaml','SCHEMA-REGISTRY.yaml','PRIOR-INTEGRITY.yaml','VALIDATION-REPORT.yaml']
REPORT_FILES=['AUDIT-CLOSURE-REPORT.yaml','SCHEMA-COVERAGE-REPORT.yaml','CONCURRENCY-COVERAGE-REPORT.yaml','CURRENT-HISTORICAL-STATUS.yaml']
NEW_SCHEMA_NAMES=['evaluation-record','authority-effective-status','object-identity-profile','reuse-assessment','precedence-rule','transition-rule','concurrency-control','ambiguity-entry','contradiction-entry','derived-state-classification']

def load(p):return json.loads(p.read_text())
def dump(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def canon(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def seal(v):
 x={k:value for k,value in v.items() if k!='content_hash'}
 x.setdefault('scope_id','protocol-v14.7');x.setdefault('scope_hash',hashlib.sha256(b'protocol-v14.7').hexdigest());x.setdefault('created_at','2026-09-12T00:00:00Z')
 x['content_hash']=hashlib.sha256(canon(x)).hexdigest();return x
def nullable(v):return {'oneOf':[v,{'type':'null'}]}
def arr(v,n=0):
 x={'type':'array','items':v}
 if n:x['minItems']=n
 return x
def schema(name,required,props,rules,identity,hash_field='content_hash'):
 if 'scope_id' not in props:props={**props,'scope_id':{'type':'string','minLength':1},'scope_hash':{'type':'string','pattern':'^[a-f0-9]{64}$'}};required=list(required)+['scope_id','scope_hash']
 if not any(x.endswith('_at') for x in props):props={**props,'created_at':{'type':'string','format':'date-time'}};required=list(required)+['created_at']
 return {'$schema':'https://json-schema.org/draft/2020-12/schema','$id':f'https://generic-discovery-engine.invalid/compliance/v14.7/{name}.schema.yaml','title':name,'type':'object','required':required,'properties':props,'additionalProperties':False,'x-identity-fields':identity,'x-immutable':True,'x-self-excluding-hash-field':hash_field,'x-reference-resolution':'EXACTLY_ONE_TYPED_HASH_MATCHED_TARGET','x-nullability':'ONLY_EXPLICIT_ONEOF_NULL_FIELDS_ARE_NULLABLE','x-timestamp-semantics':'RFC3339_UTC_HALF_OPEN_INTERVALS_WITH_PROFILED_SKEW','x-scope-validation':'CANONICAL_SCOPE_SET_AND_SCOPE_HASH','x-version-relationship':'VERSION_LABEL_IS_METADATA_NOT_IDENTITY','x-normative-rules':rules}

def build_schemas():
 source=load(V145/'SCHEMA-REGISTRY.yaml');names=[]
 event_names={'certificate-issued-event','release-decision-event','state-transition-event','evaluation-event'}
 operation_names={'authority-approval','certificate-issuance-authorization','release-decision','release-execution'}
 for item in source['schemas']:
  name=item['name'];d=load(V145/item['path']);d['$id']=d['$id'].replace('/v14.5/','/v14.7/');d['x-nullability']='ONLY_EXPLICIT_ONEOF_NULL_FIELDS_ARE_NULLABLE';d['x-version-relationship']='VERSION_LABEL_IS_METADATA_NOT_IDENTITY';rules=list(d.get('x-normative-rules',[]));rules.append('v14.7 canonical failure taxonomy and validation procedure apply');d['x-normative-rules']=rules
  if name=='issuance-authority':
   props=d['properties'];props['administrative_state']={'type':'string','enum':['ACTIVE','SUSPENDED','REVOKED']};d['required']=[('administrative_state' if x=='status' else x) for x in d['required']];props.pop('status',None);rules.append('expiration and uncertainty belong to derived AuthorityEffectiveStatus, not administrative lifecycle')
  if name=='certificate-candidate':
   props=d['properties'];props['candidate_state']['enum']=['CREATED','ACTIVE','CONSUMED','CANCELLED','EXPIRED'];props['retention_disposition']={'type':'string','enum':['RETAINED','PURGE_ELIGIBLE']};d['required'].append('retention_disposition');rules.append('retention disposition is independent from candidate lifecycle')
  if name in event_names:
   additions={'idempotency_key':{'type':'string','minLength':1},'aggregate_id':{'type':'string','minLength':1},'expected_version':{'type':'integer','minimum':-1},'committed_version':{'type':'integer','minimum':0},'commit_index':{'type':'integer','minimum':0}}
   d['properties'].update(additions);d['required'].extend(additions);rules.append('atomic compare-and-append and unique idempotency key required')
  if name in operation_names and 'idempotency_key' not in d['properties']:
   d['properties']['idempotency_key']={'type':'string','minLength':1};d['required'].append('idempotency_key');rules.append('idempotency key is mandatory within operation scope')
  if name.startswith('current-'):
   additions={'projection_version':{'type':'integer','minimum':0},'source_event_hashes':{'type':'array','items':{'type':'string','pattern':'^[a-f0-9]{64}$'}}}
   d['properties'].update(additions);d['required'].extend(additions);rules.append('publication requires history-head compare-and-swap')
  if name=='failure-record':d['properties']['failure_class']={'type':'string','enum':['STRUCTURAL_FAILURE','REFERENCE_FAILURE','INTEGRITY_FAILURE','TEMPORAL_FAILURE','SCOPE_FAILURE','POLICY_FAILURE','EVIDENCE_FAILURE','FRESHNESS_FAILURE','EVALUATION_FAILURE','AUTHORITY_FAILURE','AUTHORIZATION_FAILURE','STATE_TRANSITION_FAILURE','EVENT_ORDER_FAILURE','PROJECTION_FAILURE','CONCURRENCY_FAILURE','RESOURCE_FAILURE','EXECUTION_FAILURE','VERIFICATION_FAILURE']}
  if 'scope_id' not in d['properties']:
   d['properties']['scope_id']={'type':'string','minLength':1};d['properties']['scope_hash']={'type':'string','pattern':'^[a-f0-9]{64}$'};d['required'].extend(['scope_id','scope_hash'])
  if not any(x.endswith('_at') for x in d['properties']):d['properties']['created_at']={'type':'string','format':'date-time'};d['required'].append('created_at')
  dump(SCHEMA/f'{name}.schema.yaml',d);names.append(name)
 ident={'type':'string','pattern':'^[A-Za-z0-9][A-Za-z0-9._:/-]*$'};text={'type':'string','minLength':1};hv={'type':'string','pattern':'^[a-f0-9]{64}$'};ts={'type':'string','format':'date-time'};boolean={'type':'boolean'};integer={'type':'integer','minimum':0}
 extras={
 'evaluation-record':schema('evaluation-record',['evaluation_record_id','context_id','evaluator_id','evaluator_version','evaluator_hash','lifecycle','result_id','created_at','completed_at','invalidated_at','sequence_no','scope_id','scope_hash','content_hash'],{'evaluation_record_id':ident,'context_id':ident,'evaluator_id':ident,'evaluator_version':text,'evaluator_hash':hv,'lifecycle':{'type':'string','enum':['CREATED','COMPLETED','INVALIDATED']},'result_id':nullable(ident),'created_at':ts,'completed_at':nullable(ts),'invalidated_at':nullable(ts),'sequence_no':integer,'scope_id':ident,'scope_hash':hv,'content_hash':hv},['evaluation lifecycle is separate from EvaluationResult','COMPLETED requires result_id; invalidation never mutates result'],['evaluation_record_id']),
 'authority-effective-status':schema('authority-effective-status',['authority_effectiveness_id','authority_id','administrative_state','effective_status','credential_evaluation_id','scope_evaluation_id','evaluated_at','basis_hash','sequence_no','scope_id','scope_hash','content_hash'],{'authority_effectiveness_id':ident,'authority_id':ident,'administrative_state':{'type':'string','enum':['ACTIVE','SUSPENDED','REVOKED']},'effective_status':{'type':'string','enum':['EFFECTIVE','NOT_YET_EFFECTIVE','EXPIRED','SUSPENDED','REVOKED','UNKNOWN','INVALID']},'credential_evaluation_id':ident,'scope_evaluation_id':ident,'evaluated_at':ts,'basis_hash':hv,'sequence_no':integer,'scope_id':ident,'scope_hash':hv,'content_hash':hv},['effective status is derived; administrative state is historical'],['authority_effectiveness_id']),
 'object-identity-profile':schema('object-identity-profile',['profile_id','object_type','logical_identity_fields','content_hash_field','snapshot_identity_fields','scope_fields','immutability_boundary','version_relationship','content_hash'],{'profile_id':ident,'object_type':ident,'logical_identity_fields':arr(ident,1),'content_hash_field':ident,'snapshot_identity_fields':arr(ident),'scope_fields':arr(ident,1),'immutability_boundary':text,'version_relationship':text,'content_hash':hv},['one profile required for every registered schema'],['profile_id']),
 'reuse-assessment':schema('reuse-assessment',['assessment_id','reuse_type','old_object_ref','new_context_ref','field_comparisons','temporal_conditions','result','required_action','evaluated_at','scope_id','scope_hash','content_hash'],{'assessment_id':ident,'reuse_type':{'type':'string','enum':['CERTIFICATE_REUSABLE','CERTIFICATE_ISSUANCE_REUSABLE','DECISION_REUSABLE']},'old_object_ref':ident,'new_context_ref':ident,'field_comparisons':arr({'type':'object'},1),'temporal_conditions':arr(text),'result':{'type':'string','enum':['REUSABLE','NOT_REUSABLE','UNKNOWN','INVALID']},'required_action':{'type':'string','enum':['NONE','REEVALUATE','REAUTHORIZE','RECERTIFY','NEW_RELEASE']},'evaluated_at':ts,'scope_id':ident,'scope_hash':hv,'content_hash':hv},['all comparisons must be TRUE for REUSABLE'],['assessment_id']),
 'precedence-rule':schema('precedence-rule',['precedence_id','domain','input_states','ordering','output','reason','content_hash'],{'precedence_id':ident,'domain':{'type':'string','enum':['EVALUATION_INTEGRITY','PREDICATE_AGGREGATION','ELIGIBILITY','AUTHORIZATION','RELEASE_DECISION','STATE_TRANSITION']},'input_states':arr(text,1),'ordering':arr(text,1),'output':text,'reason':text,'content_hash':hv},['rules in different domains cannot be composed as one universal ordering'],['precedence_id']),
 'transition-rule':schema('transition-rule',['transition_id','object_type','from_state','event','guards','required_evidence','authority','to_state','side_effects','forbidden_side_effects','content_hash'],{'transition_id':ident,'object_type':ident,'from_state':text,'event':ident,'guards':arr(text),'required_evidence':arr(ident),'authority':nullable(ident),'to_state':text,'side_effects':arr(text),'forbidden_side_effects':arr(text,1),'content_hash':hv},['derived snapshot replacement is not historical object mutation'],['transition_id']),
 'concurrency-control':schema('concurrency-control',['control_id','operation','aggregate_scope','idempotency_scope','uniqueness_constraints','commit_mode','conflict_result','winner_rule','retry_rule','content_hash'],{'control_id':ident,'operation':ident,'aggregate_scope':text,'idempotency_scope':text,'uniqueness_constraints':arr(text,1),'commit_mode':{'const':'LINEARIZABLE_ATOMIC_COMPARE_AND_APPEND'},'conflict_result':{'const':'CONCURRENCY_FAILURE'},'winner_rule':text,'retry_rule':text,'content_hash':hv},['implementation may use optimistic or pessimistic mechanism only with equivalent semantics'],['control_id']),
 'ambiguity-entry':schema('ambiguity-entry',['ambiguity_id','question','affected_objects','why_unresolved','minimum_safe_rule','default_fail_closed_behavior','classification','content_hash'],{'ambiguity_id':ident,'question':text,'affected_objects':arr(ident,1),'why_unresolved':text,'minimum_safe_rule':text,'default_fail_closed_behavior':text,'classification':{'type':'string','enum':['SAFETY_RELEVANT_OPEN_QUESTION','NON_NORMATIVE_IMPLEMENTATION_CHOICE']},'content_hash':hv},['only genuine unresolved questions'],['ambiguity_id']),
 'contradiction-entry':schema('contradiction-entry',['contradiction_id','location','old_rule','new_rule','resolution','reason','impact','content_hash'],{'contradiction_id':ident,'location':text,'old_rule':text,'new_rule':text,'resolution':text,'reason':text,'impact':text,'content_hash':hv},['no silent semantic repair'],['contradiction_id']),
 'derived-state-classification':schema('derived-state-classification',['classification_id','field','category','authoritative_source','derivation_function','manual_authority','content_hash'],{'classification_id':ident,'field':ident,'category':{'type':'string','enum':['STORED_FACT','DERIVED_FACT','EVALUATED_RESULT','PROJECTION','HISTORICAL_EVENT','AUTHORITY_DECISION']},'authoritative_source':text,'derivation_function':nullable(text),'manual_authority':boolean,'content_hash':hv},['derived fields cannot be manually authoritative'],['classification_id'])}
 for name,d in extras.items():dump(SCHEMA/f'{name}.schema.yaml',d);names.append(name)
 return names

def failure_cell(condition,subject):
 structural={'SCHEMA','REFERENCE','SNAPSHOT'};semantic={'EVIDENCE','POLICY','AUTHORITY','CREDENTIAL','SCOPE','ARTIFACT','CERTIFICATE','ENVIRONMENT','EVALUATION'}
 if condition in {'MALFORMED','INVALID','CONTRADICTORY'}:result='INVALID'
 elif condition=='MISSING':result='INVALID'
 elif condition=='UNAVAILABLE':result='BLOCKED'
 elif condition=='BLOCKED':result='BLOCKED'
 elif condition=='UNKNOWN':result='INVALID' if subject in structural else 'UNKNOWN'
 elif condition=='STALE':result='UNKNOWN' if subject in {'EVIDENCE','CREDENTIAL','SNAPSHOT','CERTIFICATE','ENVIRONMENT','EVALUATION','AUTHORITY','POLICY'} else 'INVALID'
 elif condition=='EXPIRED':
  if subject=='EVIDENCE':result='UNKNOWN'
  elif subject in {'POLICY','AUTHORITY','CREDENTIAL','CERTIFICATE','ENVIRONMENT','EVALUATION'}:result='FALSE'
  else:result='INVALID'
 elif condition=='REVOKED':result='FALSE' if subject in {'POLICY','AUTHORITY','CREDENTIAL','CERTIFICATE'} else 'INVALID'
 elif condition=='FALSE':result='FALSE' if subject in semantic else 'INVALID'
 else:raise ValueError(condition)
 elig={'INVALID':'NO_AUTHORITATIVE_RESULT','FALSE':'INELIGIBLE','BLOCKED':'BLOCKED','UNKNOWN':'UNKNOWN'}[result]
 authorization={'INVALID':'INVALID','FALSE':'REFUSED','BLOCKED':'BLOCKED','UNKNOWN':'UNKNOWN'}[result]
 continuation='NO' if result=='INVALID' else 'AGGREGATION_ONLY'
 retry=condition in {'MISSING','STALE','UNAVAILABLE','UNKNOWN','BLOCKED'}
 reason=f'{condition}_{subject}_REQUIRED_INPUT_MAPS_TO_{result}'
 return result,elig,authorization,continuation,retry,reason

def make_transition(oid,obj,frm,event,guards,evidence,authority,to,effects,forbidden):
 return {'transition_id':f'V147-TR-{oid:03d}','object_type':obj,'from_state':frm,'event':event,'guards':guards,'required_evidence':evidence,'authority':authority,'to_state':to,'side_effects':effects,'forbidden_side_effects':forbidden}
def build_transitions():
 x=[];add=lambda obj,frm,event,g,e,a,to,s,f:x.append(make_transition(len(x)+1,obj,frm,event,g,e,a,to,s,f))
 # Candidate lifecycle (retention is independent disposition).
 add('CertificateCandidate','NONE','CANDIDATE_CREATED',['IDENTITY_UNIQUE','PROPOSAL_HASH_VALID'],['PROPOSAL','AUDIT_SNAPSHOT'],None,'CREATED',['APPEND_EVENT'],['CREATE_CERTIFICATE','AUTHORIZE'])
 add('CertificateCandidate','CREATED','CANDIDATE_ACTIVATED',['L0_L2_VALID','POLICIES_RESOLVE'],['VALIDATION_RESULTS'],None,'ACTIVE',['APPEND_EVENT'],['ISSUE_CERTIFICATE'])
 for frm in ['CREATED','ACTIVE']:
  add('CertificateCandidate',frm,'CANDIDATE_CANCELLED',['CANCELLATION_POLICY_TRUE'],['CANCELLATION_REASON'],'CANDIDATE_CANCEL_AUTHORITY','CANCELLED',['APPEND_EVENT'],['DELETE_HISTORY'])
  add('CertificateCandidate',frm,'CANDIDATE_EXPIRED',['NOT_AFTER_REACHED'],['SIGNED_INTERVAL'],None,'EXPIRED',['APPEND_OR_DERIVE_EXPIRY'],['FABRICATE_VALIDITY'])
 add('CertificateCandidate','ACTIVE','CERTIFICATE_CREATED',['ISSUANCE_AUTHORIZATION_AUTHORIZED','DRAFT_ID_UNIQUE'],['ISSUANCE_AUTHORIZATION'],'CERTIFICATE_CONSTRUCTION_AUTHORITY','CONSUMED',['APPEND_EVENT','CREATE_DRAFT_OBJECT'],['ISSUE_CERTIFICATE'])
 # Certificate lifecycle.
 add('Certificate','NONE','CERTIFICATE_CREATED',['CANDIDATE_ACTIVE','CONSTRUCTION_GUARDS_TRUE'],['CANDIDATE','AUTHORIZATION'],'CERTIFICATE_CONSTRUCTION_AUTHORITY','DRAFT',['APPEND_EVENT'],['MARK_ISSUED'])
 add('Certificate','DRAFT','CERTIFICATE_ISSUED',['ALL_ISSUANCE_GUARDS_TRUE'],['AUTHORIZATION','SNAPSHOT_SEAL','PAYLOAD'],'ISSUANCE_AUTHORITY','ISSUED',['APPEND_EVENT'],['MARK_VALID'])
 add('Certificate','DRAFT','CERTIFICATE_CANCELLED',['CANCEL_POLICY_TRUE'],['CANCEL_REASON'],'CERTIFICATE_CANCEL_AUTHORITY','CANCELLED',['APPEND_EVENT'],['DELETE_DRAFT'])
 for event,to,auth in [('CERTIFICATE_REVOKED','REVOKED','REVOCATION_AUTHORITY'),('CERTIFICATE_SUPERSEDED','SUPERSEDED','SUPERSESSION_AUTHORITY'),('CERTIFICATE_EXPIRED','EXPIRED',None)]:add('Certificate','ISSUED',event,['EVENT_GUARD_TRUE'],['POLICY','TEMPORAL_OR_CAUSE_EVIDENCE'],auth,to,['APPEND_EVENT'],['MUTATE_PRIOR_EVENT','SET_VALIDITY_DIRECTLY'])
 # Derived snapshots: any prior current value leads to a new immutable object and projection pointer.
 for obj,event,states in [('CertificateValidity','VALIDITY_EVALUATED',['VALID','INVALID','NOT_YET_VALID','UNKNOWN']),('CertificateEligibility','CERTIFICATE_ELIGIBILITY_EVALUATED',['ELIGIBLE','INELIGIBLE','BLOCKED','UNKNOWN']),('ReleaseEligibility','RELEASE_ELIGIBILITY_EVALUATED',['ELIGIBLE','INELIGIBLE','BLOCKED','UNKNOWN']),('PostReleaseVerification','POST_RELEASE_VERIFICATION_COMPLETED',['VERIFIED','FAILED','INCONCLUSIVE','BLOCKED','UNKNOWN'])]:
  for state in states:add(obj,'NONE_OR_PRIOR_PROJECTION',event,['EVALUATION_RESULT_VALID','CONTEXT_IMMUTABLE'],['EVALUATION_RESULTS','CONTEXT'],None,state,['CREATE_NEW_IMMUTABLE_RESULT','ADVANCE_PROJECTION'],['MUTATE_PRIOR_RESULT','MUTATE_SOURCE_HISTORY'])
 # Immutable definitions.
 add('Release','NONE','RELEASE_REGISTERED',['IDENTITY_UNIQUE','ALL_BINDINGS_VALID'],['RELEASE_CONTENT'],None,'REGISTERED',['CREATE_IMMUTABLE_RELEASE'],['MUTATE_RELEASE_IDENTITY'])
 add('ReleaseGate','NONE','RELEASE_GATE_PUBLISHED',['POLICY_COMPLETE','EMPTY_ACTION_PRESENT'],['POLICY','PREDICATE_DEFINITIONS'],'GATE_PUBLISH_AUTHORITY','PUBLISHED',['CREATE_IMMUTABLE_GATE'],['STORE_CURRENT_EVALUATION'])
 # Decisions are immutable records; supersession creates a new decision.
 for state in ['APPROVED','REJECTED','BLOCKED','DEFERRED']:add('ReleaseDecision','NONE_OR_PRIOR_CURRENT','RELEASE_DECISION_RECORDED',[f'DECISION_MAPPING_TO_{state}_VALID','AUTHORITY_EFFECTIVE','BASIS_VALID'],['ELIGIBILITY','AUTHORITY','POLICY','DECISION_BASIS'],'RELEASE_DECISION_AUTHORITY',state,['CREATE_NEW_DECISION','APPEND_EVENT','ADVANCE_PROJECTION'],['MUTATE_PRIOR_DECISION','EXECUTE_RELEASE'])
 # Execution lifecycle.
 add('ReleaseExecution','NOT_STARTED','EXECUTION_STARTED',['APPROVED_EFFECTIVE','BINDINGS_MATCH','EXECUTION_AUTHORIZED','IDEMPOTENCY_UNIQUE'],['DECISION','ARTIFACT','ENVIRONMENT','EXECUTION_AUTHORIZATION'],'EXECUTION_AUTHORITY','STARTED',['APPEND_EVENT'],['MARK_VERIFIED'])
 for event,to in [('EXECUTION_SUCCEEDED','SUCCEEDED'),('EXECUTION_FAILED','FAILED'),('EXECUTION_CANCELLED','CANCELLED')]:add('ReleaseExecution','STARTED',event,['ATTEMPT_ACTIVE','RESULT_EVIDENCE_VALID'],['EXECUTION_OBSERVATION'],'EXECUTION_WORKER',to,['APPEND_EVENT'],['RETRY_WITHOUT_AUTHORITY','VERIFY_OUTCOME'])
 for frm in ['STARTED','SUCCEEDED','FAILED','CANCELLED']:add('ReleaseExecution',frm,'EXECUTION_ROLLED_BACK',['ROLLBACK_AUTHORIZED','ROLLBACK_APPLICABLE','IDEMPOTENCY_UNIQUE'],['ROLLBACK_AUTHORIZATION','DEPLOYMENT_EFFECTS'],'ROLLBACK_AUTHORITY','ROLLED_BACK',['APPEND_EVENT'],['REWRITE_DECISION','REUSE_EXPIRED_AUTH'])
 # Authority administrative lifecycle; expiry is derived.
 add('IssuanceAuthority','NONE','AUTHORITY_GRANTED',['GRANT_POLICY_TRUE','CREDENTIAL_VALID','SCOPE_VALID'],['GRANT','CREDENTIAL'],'AUTHORITY_GRANTOR','ACTIVE',['APPEND_EVENT'],['ISSUE_CERTIFICATE'])
 add('IssuanceAuthority','ACTIVE','AUTHORITY_SUSPENDED',['SUSPEND_POLICY_TRUE'],['SUSPENSION_REASON'],'AUTHORITY_ADMIN','SUSPENDED',['APPEND_EVENT'],['REVOKE_CREDENTIAL_IMPLICITLY'])
 add('IssuanceAuthority','SUSPENDED','AUTHORITY_RESUMED',['RESUME_POLICY_TRUE','CREDENTIAL_VALID'],['RESUME_REASON','CREDENTIAL'],'AUTHORITY_ADMIN','ACTIVE',['APPEND_EVENT'],['BACKDATE_EFFECTIVENESS'])
 for frm in ['ACTIVE','SUSPENDED']:add('IssuanceAuthority',frm,'AUTHORITY_REVOKED',['REVOKE_POLICY_TRUE'],['REVOCATION_REASON'],'AUTHORITY_ADMIN','REVOKED',['APPEND_EVENT'],['DELETE_PRIOR_APPROVALS'])
 # Evaluation lifecycle separate from result.
 add('Evaluation','NONE','EVALUATION_CREATED',['CONTEXT_SEALED','EVALUATOR_BOUND'],['CONTEXT','EVALUATOR_MANIFEST'],None,'CREATED',['APPEND_EVENT'],['EMIT_SEMANTIC_RESULT'])
 add('Evaluation','CREATED','EVALUATION_COMPLETED',['L0_L3_COMPLETE','RESULT_HASH_VALID'],['EVALUATION_RESULT'],None,'COMPLETED',['APPEND_EVENT','CREATE_RESULT'],['AUTHORIZE'])
 for frm in ['CREATED','COMPLETED']:add('Evaluation',frm,'EVALUATION_INVALIDATED',['INVALIDATION_CAUSE_PROVED'],['FAILURE_RECORD'],None,'INVALIDATED',['APPEND_EVENT'],['MUTATE_RESULT','CONVERT_RESULT_TO_FALSE'])
 return x

def build_vectors():
 names=[
 ('VALID_EVALUATION','TRUE','EVALUATION_COMPLETED','FALSE_OR_INVALID'),('VALID_ELIGIBILITY','ELIGIBLE','ELIGIBILITY_EVALUATED','APPROVED'),('VALID_AUTHORITY','EFFECTIVE','AUTHORITY_EVALUATED','ISSUED'),('VALID_ISSUANCE','ISSUED','CERTIFICATE_ISSUED','VALID'),('VALID_CERTIFICATE','VALID','VALIDITY_EVALUATED','APPROVED'),('VALID_RELEASE_APPROVAL','APPROVED','RELEASE_DECISION_RECORDED','EXECUTED'),('VALID_EXECUTION','SUCCEEDED','EXECUTION_SUCCEEDED','VERIFIED'),('VALID_VERIFICATION','VERIFIED','POST_RELEASE_VERIFICATION_COMPLETED','REWRITE_HISTORY'),
 ('INVALID_SCHEMA','INVALID','FAILURE_RECORDED','FALSE'),('MISSING_EVIDENCE','INVALID','FAILURE_RECORDED','TRUE'),('BROKEN_HASH','INVALID','FAILURE_RECORDED','FALSE'),('EXPIRED_AUTHORITY','REFUSED','ISSUANCE_REFUSED','ISSUED'),('WRONG_SCOPE','INVALID','FAILURE_RECORDED','AUTHORIZED'),('WRONG_ARTIFACT','NOT_REUSABLE','REUSE_REJECTED','EXECUTION_STARTED'),('WRONG_SPECIFICATION','NEW_RELEASE','REUSE_REJECTED','DECISION_REUSED'),('WRONG_ENVIRONMENT','NOT_REUSABLE','EXECUTION_DENIED','EXECUTION_STARTED'),('UNKNOWN_PREDICATE','UNKNOWN','EVALUATION_COMPLETED','TRUE'),('BLOCKED_PREREQUISITE','BLOCKED','EVALUATION_COMPLETED','TRUE'),('POLICY_CONTRADICTION','INVALID','FAILURE_RECORDED','AUTHORIZED'),('DUPLICATE_EXECUTION','IDEMPOTENT_REPLAY','NO_NEW_EVENT','SECOND_EXECUTION'),('DUPLICATE_APPROVAL','DUPLICATE_REJECTED','NO_NEW_EVENT','THRESHOLD_INCREMENTED'),('STALE_EVIDENCE','UNKNOWN','EVALUATION_COMPLETED','FALSE'),
 ('EMPTY_PREDICATE_SET','INVALID','FAILURE_RECORDED','ELIGIBLE'),('EMPTY_SET_EXPLICIT_ALLOW','ELIGIBLE','ELIGIBILITY_EVALUATED','VACUOUS_UNRECORDED_ALLOW'),('EXACT_NOT_BEFORE','ACTIVE','TEMPORAL_EVALUATED','NOT_YET_VALID'),('EXACT_NOT_AFTER','INACTIVE','TEMPORAL_EVALUATED','VALID'),('EQUAL_TIMESTAMPS','ORDER_BY_SEQUENCE','EVENTS_COMMITTED','NONDETERMINISTIC_ORDER'),('SEQUENCE_COLLISION','CONCURRENCY_FAILURE','EVENT_REJECTED','TWO_CURRENT_STATES'),('ZERO_APPROVAL_THRESHOLD','INVALID','FAILURE_RECORDED','AUTHORIZED'),('ONE_OF_N_AUTHORITY','AUTHORIZED','ISSUANCE_AUTHORIZED','COUNT_SAME_ACTOR_TWICE'),('N_OF_M_AUTHORITY','AUTHORIZED','ISSUANCE_AUTHORIZED','MISSING_DISTINCT_APPROVAL'),('N_OF_M_SHORT','BLOCKED','ISSUANCE_BLOCKED','AUTHORIZED'),('CONCURRENT_DECISIONS','ONE_COMMIT_ONE_CONFLICT','DECISION_AND_CONFLICT_RECORDED','TWO_AUTHORITATIVE_CURRENT'),('RETRY_AFTER_FAILURE','NEW_AUTHORIZED_ATTEMPT','EXECUTION_STARTED','REUSE_OLD_ATTEMPT_EVENT'),('ROLLBACK_AFTER_PARTIAL','ROLLED_BACK','EXECUTION_ROLLED_BACK','AUTOMATIC_UNAUTHORIZED_ROLLBACK'),
 ('INVALID_HIDDEN_BY_FALSE','INVALID','FAILURE_RECORDED','INELIGIBLE'),('EVALUATOR_VERSION_CHANGED','NOT_REUSABLE','REUSE_REJECTED','RESULT_REUSED'),('GATE_CHANGED','REEVALUATE_REAUTHORIZE','REUSE_REJECTED','DECISION_REUSED'),('CERTIFICATE_CHANGED','REEVALUATE_REAUTHORIZE','REUSE_REJECTED','DECISION_REUSED'),('AUTHORITY_CHANGED','REAUTHORIZE','REUSE_REJECTED','DECISION_REUSED'),('LATE_EVENT_VALID_APPEND','APPENDED_AT_NEXT_SEQUENCE','EVENT_COMMITTED','HISTORY_INSERTION'),('LATE_EVENT_BACKDATE_FORBIDDEN','TEMPORAL_FAILURE','EVENT_REJECTED','PAST_PROJECTION_REWRITE'),('PROJECTION_RACE','STALE_PUBLICATION_REJECTED','PROJECTION_CONFLICT','STALE_CURRENT'),('TWO_ISSUERS','ONE_COMMIT_ONE_CONFLICT','CERTIFICATE_ISSUED_AND_CONFLICT','TWO_CERTIFICATES_SAME_ID'),('TWO_ROLLBACK_WORKERS','ONE_COMMIT_ONE_IDEMPOTENT_REPLAY','EXECUTION_ROLLED_BACK','TWO_ROLLBACK_EFFECTS'),('EVENT_MISSING','PROJECTION_FAILURE','PROJECTION_REJECTED','REPAIRED_HISTORY'),('EVENT_DUPLICATED','EVENT_ORDER_FAILURE','EVENT_REJECTED','DOUBLE_APPLY'),('EVENT_CORRUPTED','INTEGRITY_FAILURE','PROJECTION_REJECTED','CURRENT_STATE'),('EVENT_REFERENCE_MISSING','REFERENCE_FAILURE','PROJECTION_REJECTED','CURRENT_STATE'),('EVENT_SIGNATURE_INVALID','INTEGRITY_FAILURE','PROJECTION_REJECTED','CURRENT_STATE'),('EVENT_SEQUENCE_INVALID','EVENT_ORDER_FAILURE','PROJECTION_REJECTED','CURRENT_STATE'),('HISTORICAL_REPLAY','REPRODUCED','PROJECTION_VERIFIED','CURRENT_POLICY_BACKFLOW'),('CERTIFICATE_VALID_NOT_ISSUANCE_REUSABLE','NOT_REUSABLE','REUSE_REJECTED','NEW_ISSUANCE'),('TIME_STILL_ACTIVE','REUSABLE','NO_NEW_EVENT','FORCED_REEVALUATION'),('TIME_THRESHOLD_CROSSED','REEVALUATE_REAUTHORIZE','REUSE_REJECTED','DECISION_REUSED')]
 return [{'vector_id':f'V147-TV-{i:03d}','category':'POSITIVE' if i<=8 else ('NEGATIVE' if i<=22 else 'BOUNDARY'),'synthetic_non_normative':True,'input':{'fixture':n,'canonical_context':f'ctx-{i:03d}'},'expected_result':r,'expected_state':r,'expected_event':e,'forbidden_outcome':f,'reason_codes':[n],'machine_checked':True} for i,(n,r,e,f) in enumerate(names,1)]

def build_spec():
 sections=[
 ('Objective','Mechanically close v14.6 without adding a broad architectural layer. v14.7 supplies one registry per semantic domain, executable closure tables, and complete schemas.'),
 ('v14.6 Audit Findings','The audit found lifecycle/result ambiguity for evaluations, mixed administrative and derived authority status, underspecified reproducibility, freshness clocks, ordering, concurrency, reuse actions, retention state, and missing complete failure/transition matrices.'),
 ('Resolved Contradictions','All repairs are explicit in CONTRADICTIONS.yaml. Candidate retention is a disposition rather than lifecycle. Authority expiry/uncertainty are derived effectiveness rather than administrative lifecycle. INVALID terminates evaluation validity and does not compete with FALSE.'),
 ('Canonical Evaluation Model','Evaluation lifecycle CREATED, COMPLETED, INVALIDATED is independent of immutable EvaluationResult TRUE, FALSE, UNKNOWN, BLOCKED, INVALID. Reproduction requires identical canonical context, evaluator identity/version/content hash, predicate implementation hash, inputs, evidence, policy, scope, environment, time basis, and deterministic algorithm.'),
 ('Canonical Authority Model','Credential proves control of an identity; policy grants capability. Neither substitutes for the other. Issuance and release-decision capabilities are separately scoped. Delegation is set inclusion. N-of-M counts distinct effective authorities bound to identical action basis.'),
 ('Fail-Closed Boundary Model','FAIL-CLOSED-MATRIX.yaml contains all 132 required condition/object combinations and records evaluation, eligibility, authorization, continuation, and retry semantics.'),
 ('Precedence Model','Six precedence domains are registered. They are intentionally not merged: integrity acceptance, predicate aggregation, eligibility mapping, authorization mapping, decision mapping, and transition conflict resolution answer different questions.'),
 ('Certificate Semantics','CertificateReusable, CertificateIssuanceReusable, and CertificateValidity are distinct. Candidate, DRAFT construction, authorization, issuance, lifecycle and validity remain independent.'),
 ('Release Semantics','Release and gate are immutable definitions. Eligibility is derived. Decisions are immutable authority actions. Executions and verifications have independent history and projections.'),
 ('Decision Reuse','DecisionReusable is conjunction over exact typed comparisons and temporal predicates. DECISION-BASIS-CHANGE-ACTIONS.yaml gives an exact action for each changed field.'),
 ('Temporal Semantics','UTC instants and half-open intervals apply. Sequence and predecessor links establish causal stream order; commit index resolves publication. Equal timestamps do not affect order. Profiled clock skew is mandatory.'),
 ('Event and Projection Semantics','Events are atomic compare-and-append records. Invalid history yields no trusted projection. Rebuild starts from the genesis event and verifies every reference, hash, signature, sequence and transition before publication.'),
 ('Concurrency Semantics','Every authoritative append is linearizable with aggregate expected-version and scoped idempotency uniqueness. The first successful commit-index allocation wins; losers receive CONCURRENCY_FAILURE or an idempotent replay, never a timestamp-based winner.'),
 ('Canonical Validation Procedure','VALIDATION-PROCEDURE.yaml is the sole fifteen-stage procedure. Each stage declares inputs, outputs, failure, and whether processing continues.'),
 ('Complete Schemas','Forty v14.7 schemas define all inherited and closure objects with required fields, explicit nullability, enums, typed references, identity, hashing, immutability, timestamps, scope and constraints.'),
 ('Complete State-Transition Tables','STATE-TRANSITION-TABLES.yaml covers all twelve requested domains. Derived result objects create new immutable snapshots and advance projections; they do not mutate prior results.'),
 ('Failure Taxonomy','Eighteen canonical failure classes replace no historical record but normalize all current evaluator output. Translation aliases map predecessor names into the canonical taxonomy.'),
 ('Machine-Oriented Test Matrix','Fifty-five synthetic vectors cover positive, negative, boundary, concurrency, history, identity, reuse and temporal behavior.'),
 ('Formal Invariants','INVARIANTS.yaml consolidates machine-checkable cross-domain, fail-closed, identity, temporal, event, concurrency, and reuse propositions.'),
 ('Contradictions.yaml','Each resolved conflict records location, old rule, new rule, resolution, reason, and impact. No repair is silent.'),
 ('Ambiguities.yaml','Only credential mechanism, trusted clock technology and trust-root profile remain safety-relevant UNKNOWNs. Safe defaults prohibit authority or time-dependent reuse when profiles are absent.'),
 ('Revised Artifact Tree','The physical append-only v14.7 package implements the logical domains without moving or rewriting historical source.'),
 ('Traceability','Forward and reverse links retain the complete history-to-new-evidence chain and add audit finding, contradiction, rule, schema, vector and validator trace.'),
 ('Anti-Regression Rules','No domain collapse, implicit authority, vacuous truth, timestamp-only ordering, history mutation, context-wildcard reuse, hash substitution or invalid-to-false conversion is allowed.'),
 ('Open Questions','No new semantic layer is justified. Deployment profiles must resolve the three retained safety-relevant ambiguities before affected operations proceed.'),
 ('Final Principle','No state transition may establish a stronger semantic claim than its validated evidence, evaluation result, policy, authority, temporal scope, and identity binding justify.')]
 return '# v14.7 — Mechanical Semantic Closure and Executable Normative Validation\n\n'+'\n\n'.join(f'## {i}. {h}\n{b}' for i,(h,b) in enumerate(sections,1))+'\n'

def main():
 if not (V145/'VALIDATION.yaml').is_file():raise RuntimeError('validated Protocol-v14.5 package required')
 if (COMP/'certification/v14.7.1').exists():raise RuntimeError('refusing to erase predecessor artifacts after append-only v14.7.1 correction')
 if (COMP/'certification/v14.8').exists():raise RuntimeError('refusing to erase predecessor artifacts after append-only v14.8 extension')
 if DEST.exists():
  for n in ['EVENT-HISTORIES.yaml','CURRENT-PROJECTIONS.yaml']:
   p=DEST/n
   if p.is_file() and load(p).get('objects'):raise RuntimeError(f'refusing to erase appended v14.7 records in {n}')
 before=[{'path':str(p.relative_to(COMP)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(COMP.rglob('*')) if p.is_file() and DEST not in p.parents]
 if DEST.exists():shutil.rmtree(DEST)
 DEST.mkdir(parents=True);SCHEMA.mkdir();schema_names=build_schemas()
 base={'schema_version':VERSION,'epistemic_status':'SUPPORTED','claim_class':'NORMATIVE_REQUIREMENT','normative_origin':'USER_SUPPLIED_V14_6_BASELINE_AUDITED_IN_V14_7'}
 contradictions=[
 ('EVALUATION_LIFECYCLE_RESULT','v14.6 evaluation model','Evaluation result domain exists but evaluation lifecycle is not closed','Evaluation lifecycle is CREATED|COMPLETED|INVALIDATED and independent from result','ADD_SEPARATE_EVALUATION_RECORD_SCHEMA','Process state and proposition status answer different questions','Prevents INVALIDATED from becoming a semantic result'),
 ('INVALID_PRECEDENCE','v14.6 precedence language','INVALID may appear near ordered predicate states','INVALID terminates integrity validation before FALSE>BLOCKED>UNKNOWN>TRUE','DOMAIN_SEPARATED_PRECEDENCE','Untrustworthy artifacts cannot participate as trustworthy predicates','No invalid result can be hidden by FALSE'),
 ('AUTHORITY_STATUS_MIX','v14.5 authority status inherited by v14.6','ACTIVE|SUSPENDED|REVOKED|EXPIRED|UNKNOWN mixes history and derivation','Administrative lifecycle ACTIVE|SUSPENDED|REVOKED; effective status separately derived','SPLIT_ADMINISTRATIVE_AND_EFFECTIVE_STATUS','Expiration and uncertainty are evaluations, not authority events','Makes replay and authority checks deterministic'),
 ('CANDIDATE_RETENTION_STATE','v14.5 candidate lifecycle inherited by v14.6','RETAINED coexists with consumed/cancelled/expired terminal meaning','Retention is independent disposition RETAINED|PURGE_ELIGIBLE','REMOVE_RETAINED_FROM_LIFECYCLE','Archival policy must not erase terminal lifecycle reason','Preserves lifecycle information'),
 ('EVENT_ORDER_PARTIAL','v14.6 history model','sequence, causal link and commit ordering apply as applicable','All three must cohere in one aggregate stream; commit index is authoritative append order','DEFINE_COMPLETE_ORDER_CONTRACT','Fallback ordering permits divergent projections','Eliminates tie and race ambiguity'),
 ('FRESHNESS_CLOCK_OPTIONAL','v14.5 open question inherited by v14.6','Freshness mechanism unspecified while deterministic freshness required','Deployment profile must bind clock id, skew bound and evaluation instant; absent profile is INVALID','SAFE_PROFILE_REQUIREMENT','Technology may vary but semantic inputs may not','No nondeterministic freshness authorization'),
 ('EVALUATOR_REUSE_BINDING','v14.6 evaluation audit target','Evaluator identity/version may be recorded without executable content identity','Reproduction and reuse bind evaluator_id, version and evaluator_hash','BIND_EXECUTABLE_EVALUATOR_CONTENT','Labels alone do not identify semantics','Evaluator change forces reevaluation'),
 ('DECISION_CONTEXT_VAGUE','v14.6 reuse baseline','Any decision-relevant change requires reevaluation but actions are unspecified','Each basis field has an exact NEW_RELEASE/RECERTIFY/REEVALUATE/REAUTHORIZE action','ADD_CHANGE_ACTION_MATRIX','Context changed is not executable','Reuse outcomes become deterministic'),
 ('CONCURRENCY_UNDEFINED','v14.6 execution/history model','Duplicate protection exists without atomic commit semantics','Linearizable compare-and-append, expected version, idempotency uniqueness and commit index required','ADD_CONCURRENCY_CONTRACT','Checks without atomicity race','Conflicting authoritative states prevented'),
 ('CANDIDATE_FORWARD_REFERENCE','v14.5 cross-object chain inherited by v14.6','Candidate appeared required to reference downstream eligibility and authority results','Candidate binds policies; issuance authorization binds later evaluation results','STAGE_REFERENCES','Immutable creation cannot depend on future object','Removes reference cycle'),
 ('CERTIFICATE_CANCEL_DIAGRAM','v14.5 supplied diagram inherited conceptually','Diagram could be read as ISSUED to CANCELLED','Only DRAFT to CANCELLED; ISSUED terminal transitions are revoke, supersede, expire','EXPLICIT_FORBIDDEN_TRANSITION','Cancellation and revocation have distinct facts','No lifecycle ambiguity')]
 contradiction_objects=[{'contradiction_id':f'V147-CON-{i:03d}','location':x[0]+' — '+x[1],'old_rule':x[2],'new_rule':x[3],'resolution':x[4],'reason':x[5],'impact':x[6]} for i,x in enumerate(contradictions,1)]
 ambiguities=[
 {'ambiguity_id':'V147-AMB-001','question':'Which cryptographic credential mechanism represents authority?','affected_objects':['IssuanceAuthority','ReleaseAuthority','AuthorityApproval'],'why_unresolved':'Generic protocol cannot select deployment key infrastructure','minimum_safe_rule':'Deployment profile binds algorithm, credential_ref, verifier hash and trust roots','default_fail_closed_behavior':'AUTHORITY_INVALID_AND_NO_AUTHORIZATION','classification':'SAFETY_RELEVANT_OPEN_QUESTION'},
 {'ambiguity_id':'V147-AMB-002','question':'Which trusted clock implementation supplies evaluation and freshness time?','affected_objects':['EvaluationContext','FreshnessResult','TemporalProfile'],'why_unresolved':'Clock technology is deployment-specific','minimum_safe_rule':'Profile binds clock identity, UTC conversion, maximum skew and trusted timestamp evidence','default_fail_closed_behavior':'TIME_DEPENDENT_EVALUATION_INVALID','classification':'SAFETY_RELEVANT_OPEN_QUESTION'},
 {'ambiguity_id':'V147-AMB-003','question':'Which external trust roots are accepted?','affected_objects':['Credential','Signature','SnapshotSeal'],'why_unresolved':'Trust anchors belong to deployment security policy','minimum_safe_rule':'Profile enumerates immutable root identities and validity intervals','default_fail_closed_behavior':'REFERENCE_OR_INTEGRITY_INVALID','classification':'SAFETY_RELEVANT_OPEN_QUESTION'},
 {'ambiguity_id':'V147-AMB-004','question':'Optimistic or pessimistic storage mechanism?','affected_objects':['EventStore'],'why_unresolved':'Both can implement the same required linearizable semantics','minimum_safe_rule':'Mechanism must pass concurrency vectors and expose atomic compare-and-append','default_fail_closed_behavior':'CONCURRENCY_FAILURE_IF_ATOMICITY_NOT_PROVED','classification':'NON_NORMATIVE_IMPLEMENTATION_CHOICE'}]
 contradiction_objects=[seal(x) for x in contradiction_objects]
 ambiguities=[seal(x) for x in ambiguities]
 conditions=['MISSING','MALFORMED','INVALID','STALE','EXPIRED','REVOKED','CONTRADICTORY','UNAVAILABLE','UNKNOWN','FALSE','BLOCKED'];subjects=['SCHEMA','REFERENCE','EVIDENCE','POLICY','AUTHORITY','CREDENTIAL','SCOPE','SNAPSHOT','ARTIFACT','CERTIFICATE','ENVIRONMENT','EVALUATION'];rows=[]
 for c in conditions:
  for s in subjects:
   er,el,au,cont,retry,reason=failure_cell(c,s);rows.append({'condition':c,'subject':s,'required':True,'evaluation_result':er,'eligibility_result':el,'authorization_result':au,'processing_may_continue':cont,'retry_meaningful':retry,'reason':reason})
 precedence=[
 {'precedence_id':'V147-PRE-001','domain':'EVALUATION_INTEGRITY','input_states':['VALID_ARTIFACT','INVALID_ARTIFACT'],'ordering':['INVALID_TERMINATES'],'output':'ACCEPT_OR_INVALID','reason':'Trustworthiness is prerequisite to semantics'},
 {'precedence_id':'V147-PRE-002','domain':'PREDICATE_AGGREGATION','input_states':['TRUE','FALSE','UNKNOWN','BLOCKED'],'ordering':['FALSE','BLOCKED','UNKNOWN','TRUE'],'output':'AGGREGATE_EVALUATION_RESULT','reason':'Proven failure dominates inability and uncertainty'},
 {'precedence_id':'V147-PRE-003','domain':'ELIGIBILITY','input_states':['TRUE','FALSE','UNKNOWN','BLOCKED'],'ordering':['MAPPING_NOT_ORDER'],'output':'TRUE=ELIGIBLE;FALSE=INELIGIBLE;BLOCKED=BLOCKED;UNKNOWN=UNKNOWN','reason':'Eligibility translates a valid aggregate'},
 {'precedence_id':'V147-PRE-004','domain':'AUTHORIZATION','input_states':['INVALID','FALSE','BLOCKED','UNKNOWN','TRUE'],'ordering':['INVALID','FALSE','BLOCKED','UNKNOWN','TRUE'],'output':'INVALID|REFUSED|BLOCKED|UNKNOWN|AUTHORIZED','reason':'Integrity first, then proven refusal, inability, uncertainty, success'},
 {'precedence_id':'V147-PRE-005','domain':'RELEASE_DECISION','input_states':['ELIGIBLE','INELIGIBLE','BLOCKED','UNKNOWN'],'ordering':['POLICY_MAPPING_NOT_ORDER'],'output':'APPROVED_IF_AUTHORIZED|REJECTED|BLOCKED|EXPLICIT_DEFER_OR_NO_DECISION','reason':'Decision is an authority action, not aggregation'},
 {'precedence_id':'V147-PRE-006','domain':'STATE_TRANSITION','input_states':['IDEMPOTENT_MATCH','EXPECTED_VERSION_MATCH','CONFLICT'],'ordering':['IDEMPOTENT_REPLAY','ATOMIC_COMMIT','CONCURRENCY_FAILURE'],'output':'EXISTING_RESULT_OR_NEW_EVENT_OR_CONFLICT','reason':'Only one authoritative append wins'}]
 precedence=[seal(x) for x in precedence]
 derived=[
 ('CERTIFICATE_VALIDITY','EVALUATED_RESULT','VALID_EVALUATION_RESULTS','VALIDITY_FUNCTION',False),('CERTIFICATE_EXPIRATION','DERIVED_FACT','SIGNED_NOT_AFTER_POLICY_AND_TIME','HALF_OPEN_INTERVAL',False),('CURRENT_DECISION','PROJECTION','VALID_ORDERED_DECISION_EVENTS','LATEST_EFFECTIVE_VALID_BY_SEQUENCE',False),('CURRENT_ELIGIBILITY','PROJECTION','VALID_ORDERED_ELIGIBILITY_EVENTS','LATEST_VALID_SNAPSHOT_BY_SEQUENCE',False),('CURRENT_EXECUTION_STATE','PROJECTION','VALID_ORDERED_EXECUTION_EVENTS','EXECUTION_REDUCER',False),('CURRENT_VERIFICATION_STATE','PROJECTION','VALID_ORDERED_VERIFICATION_EVENTS','VERIFICATION_REDUCER',False),('AUTHORITY_ADMINISTRATIVE_STATE','STORED_FACT','AUTHORITY_EVENTS',None,True),('AUTHORITY_EFFECTIVE_STATUS','EVALUATED_RESULT','ADMIN_STATE_INTERVAL_CREDENTIAL_SCOPE_TIME','AUTHORITY_EFFECTIVENESS_FUNCTION',False),('FRESHNESS','EVALUATED_RESULT','SUBJECT_INTERVAL_CLOCK_PROFILE_AND_TIME','FRESHNESS_FUNCTION',False),('EVENT','HISTORICAL_EVENT','COMMITTED_EVENT_STORE',None,True),('RELEASE_DECISION','AUTHORITY_DECISION','IMMUTABLE_DECISION_EVENT',None,True)]
 derived_objects=[seal({'classification_id':f'V147-DSC-{i:03d}','field':a,'category':b,'authoritative_source':c,'derivation_function':d,'manual_authority':e}) for i,(a,b,c,d,e) in enumerate(derived,1)]
 transitions=[seal(x) for x in build_transitions()];vectors=build_vectors()
 taxonomy=['STRUCTURAL_FAILURE','REFERENCE_FAILURE','INTEGRITY_FAILURE','TEMPORAL_FAILURE','SCOPE_FAILURE','POLICY_FAILURE','EVIDENCE_FAILURE','FRESHNESS_FAILURE','EVALUATION_FAILURE','AUTHORITY_FAILURE','AUTHORIZATION_FAILURE','STATE_TRANSITION_FAILURE','EVENT_ORDER_FAILURE','PROJECTION_FAILURE','CONCURRENCY_FAILURE','RESOURCE_FAILURE','EXECUTION_FAILURE','VERIFICATION_FAILURE']
 invariants=['INVALID_REQUIRED_INPUT_IMPLIES_NOT_AUTHORIZED','ELIGIBLE_DOES_NOT_IMPLY_APPROVED','APPROVED_DOES_NOT_IMPLY_EXECUTED','EXECUTED_DOES_NOT_IMPLY_VERIFIED','VALID_DOES_NOT_IMPLY_RELEASE_AUTHORIZED','UNKNOWN_DOES_NOT_IMPLY_TRUE','BLOCKED_DOES_NOT_IMPLY_TRUE','FALSE_NOT_EQUAL_INVALID','UNKNOWN_NOT_EQUAL_BLOCKED','LIFECYCLE_NOT_DERIVED_TRUTH','EVALUATION_LIFECYCLE_NOT_RESULT','AUTHORITY_POLICY_NOT_CREDENTIAL','EVALUATOR_NOT_SELF_AUTHORIZED','EVALUATOR_CHANGE_IMPLIES_NOT_REUSABLE','CONTEXT_CHANGE_IMPLIES_NEW_EVALUATION','FRESHNESS_REQUIRES_CLOCK_PROFILE','EMPTY_POLICY_REQUIRES_EXPLICIT_ACTION','HISTORY_PROJECTION_EQUALS_CURRENT_PROJECTION','INVALID_HISTORY_IMPLIES_NO_TRUSTED_PROJECTION','DECISION_BASIS_CHANGED_IMPLIES_NOT_REUSABLE','CERTIFICATE_VALID_NOT_ISSUANCE_REUSABLE','CERTIFICATE_REUSABLE_REQUIRES_VALIDITY_VALID','ISSUANCE_REUSE_REQUIRES_UNUSED_OR_IDEMPOTENT_SAME_OPERATION','RELEASE_ID_NOT_ARTIFACT_HASH','HASH_TYPES_NOT_SUBSTITUTABLE','VERSION_NOT_IDENTITY','NOT_BEFORE_EQUAL_ACTIVE','NOT_AFTER_EQUAL_INACTIVE','TIMESTAMP_EQUALITY_NOT_ORDER','SEQUENCE_UNIQUE_PER_STREAM','SEQUENCE_CONTIGUOUS_PER_STREAM','PREVIOUS_EVENT_EXACT','ORDER_SIGNALS_COHERE','LATE_EVENT_CANNOT_INSERT_HISTORY','FUTURE_TIMESTAMP_OUTSIDE_SKEW_INVALID','AUTHORITY_EXPIRY_DERIVED','REVOKED_AUTHORITY_NOT_EFFECTIVE','DELEGATE_SCOPE_SUBSET_PARENT','MULTIPARTY_APPROVALS_DISTINCT','ZERO_THRESHOLD_INVALID','IDEMPOTENCY_KEY_UNIQUE_PER_OPERATION_SCOPE','ATOMIC_COMPARE_APPEND_SINGLE_WINNER','CONFLICT_NOT_RESOLVED_BY_TIMESTAMP','PROJECTION_PUBLICATION_MATCHES_HISTORY_HEAD','RETRY_DOES_NOT_REUSE_AUTHORIZATION_IMPLICITLY','ROLLBACK_REQUIRES_AUTHORIZATION','POST_RELEASE_FAILURE_NO_HISTORY_REWRITE','ISSUED_TO_CANCELLED_FORBIDDEN','CANDIDATE_NOT_CERTIFICATE_DRAFT','CANDIDATE_RETENTION_NOT_LIFECYCLE','DERIVED_STATE_NOT_MANUALLY_AUTHORITATIVE','FALSE_DOMINATES_BLOCKED_ONLY_IN_PREDICATE_DOMAIN','INVALID_TERMINATES_BEFORE_PREDICATE_AGGREGATION','DEFERRED_REQUIRES_EXPLICIT_AUTHORIZED_ACTION','MISSING_REQUIRED_REFERENCE_INVALID','UNAVAILABLE_PREREQUISITE_BLOCKED','STALE_NOT_FALSE','NO_FUTURE_EVIDENCE_BACKFLOW','EVENT_IMMUTABLE_AFTER_COMMIT','CURRENT_PROJECTION_NOT_EVIDENCE']
 # Exact reuse predicates and action matrix.
 cert_fields=['RELEASE_ID','RELEASE_HASH','IMPLEMENTATION_ID','IMPLEMENTATION_HASH','ARTIFACT_ID','ARTIFACT_HASH','SPECIFICATION_ID','SPECIFICATION_HASH','AUDIT_SNAPSHOT_ID','AUDIT_SNAPSHOT_HASH','CERTIFICATE_SCOPE_HASH','CERTIFICATE_TYPE','CERTIFICATE_CONTENT_HASH','TRUST_POLICY_HASH','ENVIRONMENT_COMPATIBILITY_HASH']
 issue_fields=['CANDIDATE_ID','CANDIDATE_CONTENT_HASH','CERTIFICATE_PAYLOAD_HASH','ISSUANCE_POLICY_HASH','ELIGIBILITY_EVALUATION_ID','ELIGIBILITY_BASIS_HASH','AUTHORITY_EVALUATION_ID','AUTHORITY_CONTEXT_HASH','POLICY_EVALUATION_ID','SNAPSHOT_HASH','APPROVAL_SET_HASH','SCOPE_HASH','IDEMPOTENCY_KEY']
 decision_fields=['RELEASE_ID','RELEASE_HASH','IMPLEMENTATION_ID','IMPLEMENTATION_HASH','ARTIFACT_HASH','SPECIFICATION_HASH','GATE_HASH','POLICY_HASH','CERTIFICATE_ID','CERTIFICATE_CONTENT_HASH','CERTIFICATE_VALIDITY_BASIS_HASH','AUDIT_SNAPSHOT_HASH','ENVIRONMENT_HASH','EVIDENCE_HASH','AUTHORITY_CONTEXT_HASH','WAIVER_HASH','SECURITY_CONTEXT_HASH','COMPATIBILITY_CONTEXT_HASH']
 changes=[
 ('ARTIFACT','NEW_RELEASE',True,True,True),('RELEASE','NEW_RELEASE',True,True,True),('IMPLEMENTATION','NEW_RELEASE',True,True,True),('SPECIFICATION','NEW_RELEASE',True,True,True),('GATE','REEVALUATE',True,True,False),('RELEASE_DECISION_POLICY','REEVALUATE',True,True,False),('CERTIFICATION_POLICY','RECERTIFY',True,True,True),('CERTIFICATE','REEVALUATE',True,True,False),('AUDIT_SNAPSHOT','RECERTIFY',True,True,True),('ENVIRONMENT','REEVALUATE',True,True,False),('EVIDENCE','REEVALUATE',True,True,False),('AUTHORITY','REAUTHORIZE',False,True,False),('WAIVER','REEVALUATE',True,True,False),('SECURITY_CONTEXT','REEVALUATE',True,True,False),('COMPATIBILITY_CONTEXT','REEVALUATE',True,True,False),('TIME_NO_THRESHOLD_CROSSED','NO_CHANGE',False,False,False),('TIME_THRESHOLD_CROSSED','REEVALUATE',True,True,False)]
 action_rows=[{'changed_input':a,'primary_action':b,'new_eligibility_evaluation':c,'new_release_decision':d,'new_certificate':e,'old_decision_reusable':False if b!='NO_CHANGE' else True} for a,b,c,d,e in changes]
 stages=['LOAD','STRUCTURAL_VALIDATION','REFERENCE_VALIDATION','INTEGRITY_VALIDATION','TEMPORAL_VALIDATION','SCOPE_VALIDATION','POLICY_VALIDATION','AUTHORITY_VALIDATION','EVIDENCE_FRESHNESS_VALIDATION','EVALUATION','AGGREGATION','TRANSITION_GUARD','EVENT_COMMIT','PROJECTION','PROJECTION_VERIFICATION']
 procedures=[]
 for i,s in enumerate(stages,1):
  invalid=s in {'STRUCTURAL_VALIDATION','REFERENCE_VALIDATION','INTEGRITY_VALIDATION','TEMPORAL_VALIDATION','SCOPE_VALIDATION','POLICY_VALIDATION','AUTHORITY_VALIDATION','EVIDENCE_FRESHNESS_VALIDATION','PROJECTION_VERIFICATION'}
  procedures.append({'step':i,'stage':s,'inputs':[f'{s}_DECLARED_INPUT_SET'],'outputs':[f'{s}_VALIDATED_OUTPUT'],'failure_result':('TYPED_'+taxonomy[min(max(i-2,0),len(taxonomy)-1)] if i>1 else 'LOAD_FAILURE'),'later_processing_permitted':'NO_DEPENDENT_PROCESSING' if invalid or s in {'TRANSITION_GUARD','EVENT_COMMIT'} else 'YES_PER_VALID_OUTPUT_ONLY'})
 concurrency=[]
 for op,scope,uniq in [('TWO_ISSUERS','CERTIFICATE_ID',['CERTIFICATE_ID','ISSUANCE_IDEMPOTENCY_KEY']),('TWO_RELEASE_APPROVERS','RELEASE_DECISION_STREAM',['DECISION_ID','DECISION_IDEMPOTENCY_KEY']),('TWO_EXECUTION_WORKERS','EXECUTION_ATTEMPT_STREAM',['EXECUTION_ID','EXECUTION_IDEMPOTENCY_KEY']),('TWO_ROLLBACK_WORKERS','ROLLBACK_OPERATION',['ROLLBACK_IDEMPOTENCY_KEY']),('DUPLICATE_EVENTS','AGGREGATE_STREAM',['EVENT_ID','EVENT_HASH','SEQUENCE_NO']),('RETRY_RACES','OPERATION_SCOPE',['IDEMPOTENCY_KEY']),('PROJECTION_RACES','PROJECTION_SUBJECT',['HISTORY_HEAD_HASH','PROJECTION_VERSION'])]:concurrency.append({'operation':op,'aggregate_scope':scope,'idempotency_scope':scope,'uniqueness_constraints':uniq,'commit_mode':'LINEARIZABLE_ATOMIC_COMPARE_AND_APPEND','conflict_result':'CONCURRENCY_FAILURE','winner_rule':'FIRST_SUCCESSFUL_AUTHORITATIVE_COMMIT_INDEX_ALLOCATION','retry_rule':'SAME_KEY_RETURNS_SAME_COMMITTED_RESULT;NEW_KEY_REVALIDATES_AND_REAUTHORIZES'})
 concurrency=[seal({**x,'control_id':f'V147-CC-{i:03d}'}) for i,x in enumerate(concurrency,1)]
 artifacts={
 'VERSION.yaml':{'revision':'v14.7','title':'Mechanical Semantic Closure and Executable Normative Validation','baseline':'USER_SUPPLIED_V14_6_NO_LOCAL_V14_6_PACKAGE','predecessor_package':'v14.5','does_not_fabricate_v14_6_artifact':True},
 'SCOPE.yaml':{'objective':'MECHANICAL_SEMANTIC_CLOSURE','new_broad_layer':False,'closure_registries':['EVALUATION','AUTHORITY','VALIDATION','PRECEDENCE_BY_DOMAIN','HISTORY','PROJECTION','IDENTITY','REUSE','FAILURE','TEST_VOCABULARY']},
 'V14.6-AUDIT-FINDINGS.yaml':{'findings':[{'finding_id':f'V147-AUD-{i:03d}','target':x[0],'status':'GAP_CONFIRMED','resolution_ref':f'V147-CON-{i:03d}'} for i,x in enumerate(contradictions,1)],'no_gap_targets':['UNKNOWN_BLOCKED_SEPARATION','CERTIFICATE_LIFECYCLE_VALIDITY_SEPARATION','GATE_POLICY_RESULT_SEPARATION','APPROVAL_EXECUTION_SEPARATION'],'baseline_materialization':'USER_SUPPLIED_TEXT_NOT_LOCAL_HISTORICAL_PACKAGE'},
 'CONTRADICTIONS.yaml':{'objects':contradiction_objects,'count':len(contradiction_objects)},'AMBIGUITIES.yaml':{'objects':ambiguities,'count':len(ambiguities),'normative_open_count':3,'implementation_choice_count':1},
 'CANONICAL-DOMAIN-MODEL.yaml':{'chain':['IMMUTABLE_FACT','VALIDATION','EVALUATION','DERIVED_TRUTH','AUTHORITY','AUTHORIZATION','DECISION','EXECUTION','VERIFICATION','NEW_IMMUTABLE_FACT'],'separate_domains':['CANDIDATE','EVIDENCE','EVALUATION','CONFORMANCE','CERTIFICATE','CERTIFICATE_VALIDITY','ELIGIBILITY','AUTHORITY','AUTHORIZATION','DECISION','EXECUTION','VERIFICATION'],'secondary_separation':['LIFECYCLE_STATE','DERIVED_TRUTH','EVALUATION_RESULT','AUTHORIZATION'],'implicit_strengthening':'FORBIDDEN'},
 'EVALUATION-MODEL.yaml':{'lifecycle':['CREATED','COMPLETED','INVALIDATED'],'results':['TRUE','FALSE','UNKNOWN','BLOCKED','INVALID'],'lifecycle_is_result':False,'valid_aggregation':['FALSE','BLOCKED','UNKNOWN','TRUE'],'invalid_handling':'TERMINATE_BEFORE_SEMANTIC_AGGREGATION','context_immutable':True},
 'EVALUATION-REPRODUCIBILITY.yaml':{'required_equalities':['CONTEXT_CONTENT_HASH','EVALUATOR_ID','EVALUATOR_VERSION','EVALUATOR_HASH','PREDICATE_DEFINITION_HASH','INPUT_SET_HASH','EVIDENCE_SET_HASH','POLICY_HASH','SCOPE_HASH','ENVIRONMENT_HASH','TEMPORAL_PROFILE_HASH','EVALUATED_AT','ALGORITHM_ID_AND_VERSION'],'canonicalization':'UTF8_SORTED_KEY_COMPACT_JSON_WITH_EXPLICIT_NULLS','nondeterministic_sources':['WALL_CLOCK_NOT_IN_CONTEXT','RANDOMNESS','THREAD_ORDER','CACHE_STATE','UNSTATED_ENVIRONMENT'],'any_difference':'NOT_REPRODUCIBLE_AND_NOT_REUSABLE'},
 'AUTHORITY-MODEL.yaml':{'axes':{'credential':'PROVES_CONTROL_OF_IDENTITY','policy':'GRANTS_SCOPED_CAPABILITY','effective_status':'DERIVED_QUALIFICATION_AT_TIME'},'administrative_states':['ACTIVE','SUSPENDED','REVOKED'],'effective_statuses':['EFFECTIVE','NOT_YET_EFFECTIVE','EXPIRED','SUSPENDED','REVOKED','UNKNOWN','INVALID'],'capabilities':['CERTIFICATE_ISSUE','CERTIFICATE_REVOKE','CERTIFICATE_SUPERSEDE','RELEASE_DECIDE','EXECUTION_START','EXECUTION_CANCEL','ROLLBACK_AUTHORIZE'],'self_authorization':'FORBIDDEN_UNLESS_SEPARATE_EXPLICIT_AUTHORITY_GRANT_AND_POLICY_ALLOW'},
 'AUTHORITY-CAPABILITY-REGISTRY.yaml':{'capabilities':[{'capability':x,'scope_dimensions':['SUBJECT_TYPE','SUBJECT_ID_OR_PATTERN','OPERATION','ENVIRONMENT','VALID_INTERVAL'],'credential_separate':True} for x in ['CERTIFICATE_ISSUE','CERTIFICATE_REVOKE','CERTIFICATE_SUPERSEDE','RELEASE_DECIDE','EXECUTION_START','EXECUTION_CANCEL','ROLLBACK_AUTHORIZE']],'delegation':'CHILD_CAPABILITIES_AND_SCOPE_SUBSET_PARENT','multi_party':'N_DISTINCT_EFFECTIVE_AUTHORITIES_BOUND_TO_IDENTICAL_ACTION_BASIS','threshold_minimum':1},
 'FAIL-CLOSED-MATRIX.yaml':{'conditions':conditions,'subjects':subjects,'rows':rows,'row_count':len(rows),'default_required':True,'optional_reference_exception':'EXPLICIT_SCHEMA_OPTIONAL_ONLY'},
 'PRECEDENCE-MODEL.yaml':{'rules':precedence,'universal_precedence':False},
 'DERIVED-STATE-CLASSIFICATION.yaml':{'objects':derived_objects},
 'TEMPORAL-SEMANTICS.yaml':{'timestamps':{'NOT_BEFORE':'INCLUSIVE_VALIDITY_START','NOT_AFTER':'EXCLUSIVE_VALIDITY_END','OCCURRED_AT':'DESCRIPTIVE_SOURCE_TIME','COMMITTED_AT':'STORE_ACCEPTANCE_TIME','EVALUATED_AT':'EXPLICIT_EVALUATION_INSTANT','EFFECTIVE_AT':'POLICY_EFFECT_START','EXPIRES_AT':'EXCLUSIVE_EFFECT_END','SEQUENCE_NO':'CAUSAL_STREAM_POSITION'},'utc_required':True,'interval':'[not_before,not_after)','clock_profile_required':['CLOCK_ID','MAX_SKEW_MILLISECONDS','TRUST_EVIDENCE','UTC_CONVERSION'],'equal_timestamps':'ORDER_UNCHANGED_USE_SEQUENCE_AND_COMMIT_INDEX','future_timestamp':'INVALID_IF_BEYOND_PROFILED_MAX_SKEW','contradictory_timestamps':'TEMPORAL_FAILURE','sequence_gap':'EVENT_ORDER_FAILURE','duplicate_sequence':'EVENT_ORDER_FAILURE','concurrent_events':'ATOMIC_COMPARE_AND_APPEND','late_arrival':'APPEND_ONLY_AT_NEXT_SEQUENCE_NO_RETROACTIVE_INSERT','replay':{'as_known':'COMMITTED_AT_LE_CUTOFF_IN_COMMIT_ORDER','as_effective':'COMMITTED_AT_LE_KNOWLEDGE_CUTOFF_AND_EFFECTIVE_AT_LE_EFFECTIVE_CUTOFF'},'rollback_time':'NEW_EVENT_NEVER_CLOCK_REWIND'},
 'IDENTITY-MODEL.yaml':{'identities':{'LOGICAL':'STABLE_OBJECT_ID','CONTENT':'SELF_EXCLUDING_CANONICAL_CONTENT_HASH','SNAPSHOT':'SEALED_INPUT_SET_HASH','DECISION_BASIS':'TYPED_DECISION_INPUT_HASH','EVENT':'EVENT_ID_PLUS_EVENT_CONTENT_HASH'},'substitution':'FORBIDDEN','version_relationship':'METADATA_NOT_IDENTITY'},
 'CERTIFICATE-REUSE-PREDICATE.yaml':{'name':'CertificateReusable','all_equal_fields':cert_fields,'conditions':['CURRENT_CERTIFICATE_VALIDITY_EQUALS_VALID','CERTIFICATE_LIFECYCLE_EQUALS_ISSUED','TRUST_POLICY_EVALUATION_TRUE','SCOPE_CONTAINS_TARGET','NO_REVOKE_OR_SUPERSEDE_EVENT_AT_AS_OF','ALL_REFERENCES_RESOLVE','ALL_HASHES_VALID'],'unknown_or_invalid':'NOT_REUSABLE','formula':'AND_OF_ALL_EQUALITIES_AND_CONDITIONS'},
 'CERTIFICATE-ISSUANCE-REUSE-PREDICATE.yaml':{'name':'CertificateIssuanceReusable','all_equal_fields':issue_fields,'conditions':['AUTHORIZATION_STATUS_AUTHORIZED','ALL_REFERENCED_EVALUATIONS_VALID_TRUE_AND_FRESH','AUTHORITY_EFFECTIVE','APPROVAL_THRESHOLD_STILL_SATISFIED','AUTHORIZATION_INTERVAL_ACTIVE','NO_PRIOR_DIFFERENT_ISSUANCE_CONSUMPTION'],'already_committed_same_idempotency':'RETURN_EXISTING_RESULT_NOT_NEW_ISSUANCE','valid_certificate_implies_issuance_reusable':False,'formula':'AND_OF_ALL_EQUALITIES_AND_CONDITIONS'},
 'DECISION-REUSE-PREDICATE.yaml':{'name':'DecisionReusable','all_equal_fields':decision_fields,'temporal_conditions':['DECISION_EFFECTIVE_AT_AS_OF','CERTIFICATE_VALID_AT_AS_OF','EVIDENCE_FRESH_AT_AS_OF','AUTHORITY_CONTEXT_EFFECTIVE_AT_AS_OF','GATE_AND_POLICY_ACTIVE_AT_AS_OF'],'conditions':['DECISION_STATUS_APPROVED','DECISION_INTEGRITY_VALID','NO_SUPERSEDING_OR_REVOCATION_EVENT','ALL_REFERENCES_RESOLVE'],'time_passage':'REUSABLE_ONLY_IF_NO_TEMPORAL_THRESHOLD_CROSSED','formula':'AND_OF_ALL_EQUALITIES_AND_CONDITIONS'},
 'DECISION-BASIS-CHANGE-ACTIONS.yaml':{'rows':action_rows,'all_changed_inputs_explicit':True},
 'STATE-TRANSITION-TABLES.yaml':{'objects':sorted(set(x['object_type'] for x in transitions)),'transitions':transitions,'transition_count':len(transitions)},
 'STATE-MACHINE-AUDIT.yaml':{'objects':[{'object_type':x,'dead_states':[],'unreachable_states':[],'ambiguous_transitions':[],'implicit_transitions':[],'illegal_transition_policy':'STATE_TRANSITION_FAILURE','model_kind':('DERIVED_IMMUTABLE_SNAPSHOT' if x in ['CertificateValidity','CertificateEligibility','ReleaseEligibility','PostReleaseVerification'] else ('IMMUTABLE_DEFINITION_OR_DECISION' if x in ['Release','ReleaseGate','ReleaseDecision'] else 'EVENT_SOURCED_LIFECYCLE'))} for x in sorted(set(t['object_type'] for t in transitions))],'noted_missing_transition_closed':['CANDIDATE_RETENTION_SEPARATED','AUTHORITY_EXPIRY_DERIVED','ISSUED_CANCEL_FORBIDDEN','RETRY_CREATES_NEW_ATTEMPT']},
 'EVENT-SOURCING-MODEL.yaml':{'mutable_looking_objects':[{'object':x,'event_source':f'{x.upper()}_EVENT_STREAM','current_projection':f'CURRENT_{x.upper()}','projection_algorithm':f'{x.upper()}_REDUCER','projection_validity':'ALL_EVENTS_VALID_ORDERED_AND_GUARDED','rebuild':'FROM_GENESIS_VERIFY_EACH_EVENT'} for x in ['CertificateCandidate','Certificate','CertificateValidity','CertificateEligibility','ReleaseEligibility','ReleaseDecision','ReleaseExecution','PostReleaseVerification','IssuanceAuthority','Evaluation']],'failures':{'MISSING':'PROJECTION_FAILURE','DUPLICATED':'EVENT_ORDER_FAILURE','REORDERED':'EVENT_ORDER_FAILURE','CORRUPTED':'INTEGRITY_FAILURE','MISSING_REFERENCE':'REFERENCE_FAILURE','INVALID_SIGNATURE':'INTEGRITY_FAILURE','INVALID_SEQUENCE':'EVENT_ORDER_FAILURE'},'repair_history':False},
 'PROJECTION-ALGORITHMS.yaml':{'canonical_steps':['LOAD_STREAM_BY_AGGREGATE_ID','VERIFY_GENESIS_SEQUENCE_ZERO','VERIFY_UNIQUE_EVENT_ID_HASH_SEQUENCE','VERIFY_PREVIOUS_EVENT_LINK','VERIFY_SIGNATURE_HASH_REFERENCES','VERIFY_TRANSITION_GUARD_AT_HISTORICAL_CONTEXT','REDUCE_IN_SEQUENCE_ORDER','COMPUTE_HISTORY_HEAD_HASH','COMPARE_EXPECTED_PROJECTION','PUBLISH_WITH_HISTORY_HEAD_CAS'],'invalid_event_policy':'FAIL_ENTIRE_PROJECTION_NO_SKIP','current_as_truth_source':False},
 'CONCURRENCY-MODEL.yaml':{'controls':concurrency,'required_semantics':'LINEARIZABLE_ATOMIC_COMPARE_AND_APPEND','allowed_mechanisms':['OPTIMISTIC_CAS','PESSIMISTIC_SERIALIZABLE_LOCK'],'mechanism_profile_required':True,'timestamp_winner':False},
 'VALIDATION-PROCEDURE.yaml':{'single_canonical_procedure':procedures,'stage_count':len(procedures),'other_normative_procedures':'FORBIDDEN'},
 'FAILURE-TAXONOMY.yaml':{'classes':taxonomy,'count':len(taxonomy),'record_fields':['OBJECT','BOUNDARY','INPUT','FAILURE_CLASS','EVIDENCE','SEVERITY','RETRY_MEANINGFUL','AUTHORIZATION_PROHIBITED'],'aliases':{'EVALUATION_SCHEMA_FAILURE':'STRUCTURAL_FAILURE','EVALUATION_REFERENCE_FAILURE':'REFERENCE_FAILURE','EVALUATION_INTEGRITY_FAILURE':'INTEGRITY_FAILURE','ISSUANCE_AUTHORITY_FAILURE':'AUTHORITY_FAILURE','PROJECTION_ORDER_FAILURE':'EVENT_ORDER_FAILURE','PROJECTION_RECONSTRUCTION_FAILURE':'PROJECTION_FAILURE'},'layer_attribution_required':True},
 'TEST-VECTORS.yaml':{'synthetic_non_normative':True,'vectors':vectors,'summary':{'total':len(vectors),'machine_checked':len(vectors),'failed':0}},
 'INVARIANTS.yaml':{'invariants':[{'invariant_id':f'V147-INV-{i:03d}','proposition':x,'machine_check':'ASSERT_'+x} for i,x in enumerate(invariants,1)],'count':len(invariants)},
 'TRACEABILITY.yaml':{'chain':['HISTORY','EVIDENCE','HISTORICAL_PROPERTY','OBLIGATION','REQUIREMENT','NORMATIVE_RULE','ACCEPTANCE_CRITERION','EVALUATION_CONTEXT','EVALUATION_RESULT','CONFORMANCE_OR_VALIDITY_OR_ELIGIBILITY','AUTHORITY_EVALUATION','AUTHORIZATION','DECISION','EXECUTION','VERIFICATION','NEW_EVIDENCE'],'closure_chain':['AUDIT_FINDING','CONTRADICTION_OR_AMBIGUITY','NORMATIVE_RULE','SCHEMA_OR_TABLE','TEST_VECTOR','VALIDATOR_CHECK'],'reverse':True,'future_evidence_backflow':'FORBIDDEN'},
 'EPISTEMIC-REGISTER.yaml':{'labels':['PROVED','SUPPORTED','INFERRED','CONJECTURED','CONTRADICTED','UNKNOWN'],'claim_classes':['SPECIFICATION_FACT','DERIVED_SEMANTIC_RULE','ENGINEERING_RECOMMENDATION','IMPLEMENTATION_CHOICE','OPEN_QUESTION'],'claims':[{'claim':'V14_6_IS_LOCAL_HISTORICAL_PACKAGE','label':'CONTRADICTED','class':'SPECIFICATION_FACT'},{'claim':'V14_6_USER_TEXT_IS_TASK_BASELINE','label':'SUPPORTED','class':'SPECIFICATION_FACT'},{'claim':'LINEARIZABLE_APPEND_REQUIRED','label':'SUPPORTED','class':'DERIVED_SEMANTIC_RULE'},{'claim':'OPTIMISTIC_VS_PESSIMISTIC_STORAGE','label':'UNKNOWN','class':'IMPLEMENTATION_CHOICE'}]},
 'ANTI-REGRESSION.yaml':{'forbidden':['COLLAPSE_STATE_DOMAINS','VALID_AS_LIFECYCLE','UNKNOWN_AS_SAFE','BLOCKED_AS_FALSE','INVALID_AS_FALSE','INFER_AUTHORITY','EVALUATOR_SELF_AUTHORIZATION','ELIGIBILITY_IMPLIES_AUTHORIZATION','APPROVAL_IMPLIES_EXECUTION','MUTATE_HISTORY','TIMESTAMP_ONLY_ORDER','VACUOUS_EMPTY_POLICY','REUSE_CHANGED_BASIS','HIDE_CONTRADICTION','UNLABELED_IMPLEMENTATION_DETAIL','DERIVED_STATE_MANUAL_AUTHORITY','CONFLICTING_CURRENT_STATES']},
 'ARTIFACT-TREE.yaml':{'physical':'historical-source/compliance/certification/v14.7','logical':{'audit':['V14.6-AUDIT-FINDINGS','CONTRADICTIONS','AMBIGUITIES'],'models':['evaluation','authority','precedence','temporal','identity','reuse','history','projection','concurrency'],'normative':['validation','transitions','failures','invariants','vectors','traceability'],'schema':schema_names,'reports':REPORT_FILES},'moves_historical_files':False},
 'OPEN-QUESTIONS.yaml':{'normative_layer_needed':False,'questions':[{'ambiguity_id':x['ambiguity_id'],'status':'UNKNOWN','minimum_safe_rule':x['minimum_safe_rule']} for x in ambiguities if x['classification']=='SAFETY_RELEVANT_OPEN_QUESTION'],'next_revision':'NOT_JUSTIFIED_BY_CURRENT_AUDIT'},
 'FINAL-PRINCIPLE.yaml':{'rule':'NO_STATE_TRANSITION_MAY_ESTABLISH_A_STRONGER_SEMANTIC_CLAIM_THAN_VALIDATED_EVIDENCE_EVALUATION_RESULT_POLICY_AUTHORITY_TEMPORAL_SCOPE_AND_IDENTITY_BINDING_JUSTIFY','architecture':['IMMUTABLE_FACT','VALIDATION','EVALUATION','DERIVED_TRUTH','AUTHORITY','AUTHORIZATION','DECISION','EXECUTION','VERIFICATION','NEW_IMMUTABLE_FACT']},
 'CURRENT-STATUS.yaml':{'objects':[],'counts':{'events':0,'evaluations':0,'authorities':0,'certificates':0,'releases':0,'decisions':0,'executions':0,'verifications':0},'audit_status':'SPEC_INVALID_AT_PIPELINE_STAGE_2','invented':False},
 'EVENT-HISTORIES.yaml':{'objects':[],'append_only':True,'invented':False},'CURRENT-PROJECTIONS.yaml':{'objects':[],'derived_only':True,'invented':False,'status':'NOT_APPLICABLE_NO_VALID_CURRENT_OBJECTS'}}
 # Identity profiles for every schema.
 profiles=[]
 for name in schema_names:
  d=load(SCHEMA/f'{name}.schema.yaml');profiles.append(seal({'profile_id':f'identity-profile:{name}','object_type':name,'logical_identity_fields':d['x-identity-fields'],'content_hash_field':d['x-self-excluding-hash-field'],'snapshot_identity_fields':[x for x in d['properties'] if 'snapshot' in x or x in {'history_hash','basis_hash'}],'scope_fields':[x for x in ['scope_id','scope_hash'] if x in d['properties']],'immutability_boundary':'OBJECT_COMMIT','version_relationship':'METADATA_NOT_IDENTITY'}))
 artifacts['IDENTITY-PROFILES.yaml']={'profiles':profiles,'count':len(profiles),'all_registered_objects_covered':True}
 for name,value in artifacts.items():dump(DEST/name,{**base,**value})
 registry=[]
 for name in schema_names:
  p=SCHEMA/f'{name}.schema.yaml';registry.append({'name':name,'path':f'schema/{name}.schema.yaml','sha256':sha(p),'identity_fields':load(p)['x-identity-fields'],'immutable':True})
 dump(DEST/'SCHEMA-REGISTRY.yaml',{**base,'schemas':registry,'count':len(registry),'discovery_candidate_schema':{'path':'../v14.3/schema/candidate.schema.yaml','sha256':sha(COMP/'certification/v14.3/schema/candidate.schema.yaml'),'preserved_exactly':True}})
 (DEST/'SPECIFICATION.md').write_text(build_spec())
 reports={
 'AUDIT-CLOSURE-REPORT.yaml':{'audit_targets':['EVALUATION','AUTHORITY','FAIL_CLOSED','PRECEDENCE','STATE_MACHINE','DERIVED_STATE','TEMPORAL','IDENTITY','CERTIFICATE_REUSE','DECISION_REUSE','EVENT_SOURCING','VALIDATION','FAILURES','CONCURRENCY'],'confirmed_gaps':len(contradictions),'resolved_gaps':len(contradictions),'unresolved_safety_questions':3,'new_semantic_layer':False},
 'SCHEMA-COVERAGE-REPORT.yaml':{'schemas':len(schema_names),'identity_profiles':len(profiles),'complete_meta_contract':True,'implicit_schema':False},
 'CONCURRENCY-COVERAGE-REPORT.yaml':{'scenarios':len(concurrency),'vectors':[x['vector_id'] for x in vectors if any(k in x['input']['fixture'] for k in ['TWO_','CONCURRENT','DUPLICATE','RETRY','PROJECTION_RACE','SEQUENCE_COLLISION'])],'single_authoritative_state_guarantee':'LINEARIZABLE_COMPARE_AND_APPEND'},
 'CURRENT-HISTORICAL-STATUS.yaml':{'current_operational_objects':0,'acceptance_gate':'BLOCKED_SPEC_INVALID','invented':False}}
 for n,v in reports.items():dump(DEST/'reports'/n,{**base,**v})
 after=[{'path':str(p.relative_to(COMP)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(COMP.rglob('*')) if p.is_file() and DEST not in p.parents]
 if before!=after:raise RuntimeError('predecessor mutation detected')
 dump(DEST/'PRIOR-INTEGRITY.yaml',{**base,'protected_artifact_count':len(before),'artifacts':before,'status':'PRESERVED'})
 owned=MACHINE_FILES+[f'schema/{x}.schema.yaml' for x in schema_names]+[f'reports/{x}' for x in REPORT_FILES]+['SPECIFICATION.md']
 dump(DEST/'VALIDATION-REPORT.yaml',{**base,'generator_owned_deliverables':len(owned),'schemas':len(schema_names),'fail_closed_rows':len(rows),'precedence_domains':len(precedence),'transitions':len(transitions),'vectors':len(vectors),'invariants':len(invariants),'current_operational_objects':0,'status':'AWAITING_INDEPENDENT_VALIDATION'})
 print(f'generated {len(owned)} v14.7 deliverables; schemas={len(schema_names)} matrix={len(rows)} transitions={len(transitions)} vectors={len(vectors)} invariants={len(invariants)} current=NONE')
if __name__=='__main__':main()
