#!/usr/bin/env python3
"""Build append-only v14.7-R6 machine schema and typed-domain realization."""
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HIST=ROOT/"historical-source";COMP=HIST/"compliance";PRE=COMP/"certification/v14.7-R5";DEST=COMP/"certification/v14.7-R6";TOOLS=HIST/"tools"
sys.path.insert(0,str(TOOLS))
from run_v147r6_conformance import run
from v147r6_machine_runtime import CERTIFICATE_TRANSITIONS,ENUMS,ERRORS,ERROR_ALLOWED,EXECUTION_TRANSITIONS,canonical,identity
from v147r6_rust_sources import sources as rust_sources
VERSION="14.7-R6";STAMP="2026-09-12T00:00:00Z"

def write(path,value):path.parent.mkdir(parents=True,exist_ok=True);path.write_text(value if isinstance(value,str) else json.dumps(value,indent=2)+"\n")
def load(path):return json.loads(path.read_text())
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def hashed(domain,value):value["content_hash"]=identity(domain,value);return value

def field(kind,nullable=False,enum=None,identifier=None,reference=None,unique=None,minimum=None,allowed=None,shape=None,object_type=None):
    x={"type":kind,"nullable":nullable}
    if enum:x["enum_domain"]=enum
    if identifier:x["identifier_domain"]=identifier
    if reference:x["reference_domain"]=reference
    if unique is not None:x["unique"]=unique
    if minimum is not None:x["minimum"]=minimum
    if allowed:x["allowed_values"]=allowed
    if shape:x["shape"]=shape
    if object_type:x["object_type"]=object_type
    return x

def schema(schema_id,plane,object_type,required,optional,fields,hash_domain):
    assert set(required+optional)==set(fields) and not set(required)&set(optional)
    return {"schema_language":"GDE-ABSTRACT-SCHEMA-1","schema_id":schema_id,"plane":plane,"object_type":object_type,"closed":True,"required":required,"optional":optional,"fields":fields,"additional_fields":"FORBIDDEN","identifier_policy":"DISTINCT_SEMANTIC_DOMAINS","reference_policy":"TYPE_AND_INTEGRITY_CHECK_REQUIRED","cardinality_policy":"DECLARED_ARRAYS_ARE_ORDERED_AND_UNIQUE_UNLESS_EXPLICITLY_OVERRIDDEN","canonicalization_ref":"../v14.7-R5/CANONICAL-SERIALIZATION.yaml","hash":{"domain":hash_domain,"inputs":[x for x in required if x!="content_hash"],"excluded":["content_hash"]},"temporal_policy":"EXPLICIT_TRUSTED_TIME_AND_SCOPE","integrity_policy":"CONTENT_HASH_REQUIRED_SIGNATURE_WHEN_PROFILE_REQUIRES"}

def build_schemas():
    s=lambda **k:field("string",**k);a=lambda **k:field("array",unique=True,**k);o=lambda **k:field("object",**k);i=lambda **k:field("integer",minimum=0,**k);b=lambda **k:field("boolean",**k)
    h=s();ts=s();scope=o(shape={"required":["scope_id","scope_expression"],"fields":{"scope_id":{"type":"string"},"scope_expression":{"type":"string"}},"additional_fields":"FORBIDDEN"},object_type="Scope")
    definitions={}
    def add(path,identifier,plane,obj,required,optional,fields):definitions[path]=schema(identifier,plane,obj,required,optional,fields,f"r6-{identifier}:v1")
    add("normative/specification.schema.yaml","Specification","NORMATIVE","Specification",["specification_id","version","title","requirement_refs","content_hash"],[],{"specification_id":s(identifier="SpecificationId"),"version":s(),"title":s(),"requirement_refs":a(reference="RequirementId"),"content_hash":h})
    add("normative/requirement.schema.yaml","NormativeRequirement","NORMATIVE","NormativeRequirement",["requirement_id","specification_id","specification_version","lifecycle","statement","normative_strength","scope","content_hash"],["preconditions","postconditions","invariants","acceptance_criteria","negative_conditions","dependencies","conflicts"],{"requirement_id":s(identifier="RequirementId"),"specification_id":s(reference="SpecificationId"),"specification_version":s(),"lifecycle":s(enum="RequirementLifecycle"),"statement":s(),"normative_strength":s(enum="NormativeStrength"),"scope":scope,"preconditions":a(),"postconditions":a(),"invariants":a(),"acceptance_criteria":a(reference="AcceptanceCriterionId"),"negative_conditions":a(),"dependencies":a(reference="RequirementId"),"conflicts":a(reference="RequirementId"),"content_hash":h})
    add("normative/predicate.schema.yaml","Predicate","NORMATIVE","Predicate",["predicate_id","expression","input_domains","content_hash"],["language_ref"],{"predicate_id":s(identifier="PredicateId"),"expression":s(),"input_domains":a(),"language_ref":s(nullable=True),"content_hash":h})
    add("normative/acceptance-criterion.schema.yaml","AcceptanceCriterion","NORMATIVE","AcceptanceCriterion",["criterion_id","requirement_ref","predicate_ref","expected_result","content_hash"],["evidence_requirements"],{"criterion_id":s(identifier="AcceptanceCriterionId"),"requirement_ref":s(reference="RequirementId"),"predicate_ref":s(reference="PredicateId"),"expected_result":s(enum="EvaluationValue"),"evidence_requirements":a(),"content_hash":h})
    add("profile/profile.schema.yaml","Profile","PROFILE","Profile",["profile_id","specification_ref","version","bindings","content_hash"],["error_policy_ref","compatibility_ref"],{"profile_id":s(identifier="ProfileId"),"specification_ref":s(reference="SpecificationId"),"version":s(),"bindings":a(reference="ProfileRequirementId"),"error_policy_ref":s(nullable=True),"compatibility_ref":s(nullable=True),"content_hash":h})
    add("profile/profile-requirement.schema.yaml","ProfileRequirement","PROFILE","ProfileRequirement",["profile_requirement_id","profile_ref","normative_requirement_ref","binding","content_hash"],[],{"profile_requirement_id":s(identifier="ProfileRequirementId"),"profile_ref":s(reference="ProfileId"),"normative_requirement_ref":s(reference="RequirementId"),"binding":s(),"content_hash":h})
    add("profile/compatibility.schema.yaml","Compatibility","PROFILE","Compatibility",["compatibility_id","source_profile_ref","target_profile_ref","compatible_fields","content_hash"],["incompatible_fields"],{"compatibility_id":s(),"source_profile_ref":s(reference="ProfileId"),"target_profile_ref":s(reference="ProfileId"),"compatible_fields":a(),"incompatible_fields":a(),"content_hash":h})
    add("implementation/implementation-requirement.schema.yaml","ImplementationRequirement","IMPLEMENTATION","ImplementationRequirement",["implementation_requirement_id","target_requirement","target_profile","statement","mandatory","content_hash"],["acceptance_criteria","implementation_scope"],{"implementation_requirement_id":s(identifier="ImplementationRequirementId"),"target_requirement":s(reference="RequirementId"),"target_profile":s(reference="ProfileId"),"statement":s(),"mandatory":b(),"acceptance_criteria":a(),"implementation_scope":s(nullable=True),"content_hash":h})
    add("implementation/implementation-instruction.schema.yaml","ImplementationInstruction","IMPLEMENTATION","ImplementationInstruction",["instruction_id","statement","instruction_type","mandatory","content_hash"],["target_requirement","rationale","alternatives"],{"instruction_id":s(identifier="InstructionId"),"target_requirement":s(nullable=True,reference="RequirementId"),"instruction_type":s(allowed=["PROFILE_BINDING","IMPLEMENTATION_GUIDANCE","OPTIMIZATION","DEPLOYMENT","TEST_HARNESS","STORAGE","LANGUAGE","LIBRARY"]),"statement":s(),"mandatory":b(),"rationale":s(nullable=True),"alternatives":a(),"content_hash":h})
    add("evidence/test.schema.yaml","TestDefinition","EVIDENCE","TestDefinition",["test_id","target_requirement_refs","operation","expected","profile_ref","content_hash"],["setup"],{"test_id":s(identifier="TestId"),"target_requirement_refs":a(reference="RequirementId"),"operation":o(),"expected":o(),"profile_ref":s(reference="ProfileId"),"setup":o(nullable=True),"content_hash":h})
    add("evidence/observation.schema.yaml","Observation","EVIDENCE","Observation",["observation_id","subject_ref","collector_ref","observed_at","value","content_hash"],["scope"],{"observation_id":s(identifier="ObservationId"),"subject_ref":s(),"collector_ref":s(),"observed_at":ts,"value":o(),"scope":o(nullable=True,object_type="Scope"),"content_hash":h})
    add("evidence/evidence.schema.yaml","Evidence","EVIDENCE","Evidence",["evidence_id","subject_ref","observation_refs","integrity","content_hash"],["scope"],{"evidence_id":s(identifier="EvidenceId"),"subject_ref":s(),"observation_refs":a(reference="ObservationId"),"integrity":o(),"scope":o(nullable=True,object_type="Scope"),"content_hash":h})
    add("runtime/validation.schema.yaml","ValidationResult","IMPLEMENTATION","ValidationResult",["validation_id","subject_ref","status","validator_id","validator_version","validator_hash","input_hash","validated_at","scope","content_hash"],["failure_codes","evidence_refs"],{"validation_id":s(identifier="ValidationId"),"subject_ref":s(),"status":s(enum="ValidationStatus"),"failure_codes":a(),"evidence_refs":a(reference="EvidenceId"),"validator_id":s(),"validator_version":s(),"validator_hash":h,"input_hash":h,"validated_at":ts,"scope":scope,"content_hash":h})
    add("runtime/evaluation.schema.yaml","EvaluationResult","IMPLEMENTATION","EvaluationResult",["evaluation_id","subject_ref","evaluator_id","evaluator_version","result","reason_codes","input_refs","evaluated_at","sequence_no","scope","integrity","content_hash"],["evidence_refs","predicate_ref","policy_ref","environment_ref","freshness"],{"evaluation_id":s(identifier="EvaluationId"),"subject_ref":s(),"evaluator_id":s(),"evaluator_version":s(),"result":s(enum="EvaluationValue"),"reason_codes":a(),"evidence_refs":a(reference="EvidenceId"),"input_refs":a(),"predicate_ref":s(nullable=True,reference="PredicateId"),"evaluated_at":ts,"sequence_no":i(),"scope":scope,"policy_ref":s(nullable=True),"environment_ref":s(nullable=True),"freshness":o(nullable=True),"integrity":o(),"content_hash":h})
    add("runtime/conformance.schema.yaml","ConformanceResult","DECISION","ConformanceResult",["conformance_id","requirement_ref","status","evaluation_refs","evidence_refs","evaluated_at","content_hash"],["rationale"],{"conformance_id":s(),"requirement_ref":s(reference="RequirementId"),"status":s(enum="ConformanceStatus"),"evaluation_refs":a(reference="EvaluationId"),"evidence_refs":a(reference="EvidenceId"),"rationale":s(),"evaluated_at":ts,"content_hash":h})
    add("runtime/authority.schema.yaml","Authority","DECISION","Authority",["authority_id","status","qualification_status","scope","not_before","content_hash"],["not_after"],{"authority_id":s(identifier="AuthorityId"),"status":s(enum="AuthorityStatus"),"qualification_status":s(enum="AuthorityQualificationStatus"),"scope":scope,"not_before":ts,"not_after":s(nullable=True),"content_hash":h})
    add("runtime/certificate.schema.yaml","Certificate","DECISION","Certificate",["certificate_id","lifecycle","validity","subject_ref","issued_at","content_hash"],["expires_at"],{"certificate_id":s(identifier="CertificateId"),"lifecycle":s(enum="CertificateLifecycle"),"validity":s(enum="CertificateValidity"),"subject_ref":s(),"issued_at":ts,"expires_at":s(nullable=True),"content_hash":h})
    add("runtime/release.schema.yaml","Release","DECISION","Release",["release_id","eligibility","authorization","decision","execution","verification","content_hash"],[],{"release_id":s(identifier="ReleaseId"),"eligibility":s(enum="ReleaseEligibility"),"authorization":s(enum="AuthorizationStatus"),"decision":s(enum="ReleaseDecisionStatus"),"execution":s(enum="ReleaseExecutionStatus"),"verification":s(enum="PostReleaseVerificationStatus"),"content_hash":h})
    add("runtime/event.schema.yaml","StateTransitionEvent","EVIDENCE","StateTransitionEvent",["event_id","aggregate_ref","event_type","previous_state","resulting_state","sequence_no","occurred_at","actor_ref","scope","payload","event_hash"],["committed_at","authority_ref","previous_event_hash"],{"event_id":s(identifier="EventId"),"aggregate_ref":s(),"event_type":s(),"previous_state":s(),"resulting_state":s(),"sequence_no":i(),"occurred_at":ts,"committed_at":s(nullable=True),"actor_ref":s(),"authority_ref":s(nullable=True,reference="AuthorityId"),"scope":scope,"payload":o(),"previous_event_hash":s(nullable=True),"event_hash":h})
    add("runtime/projection.schema.yaml","Projection","IMPLEMENTATION","Projection",["projection_id","history_ref","profile_ref","algorithm_version","status","state_hash","content_hash"],[],{"projection_id":s(),"history_ref":s(),"profile_ref":s(reference="ProfileId"),"algorithm_version":s(),"status":s(enum="ProjectionStatus"),"state_hash":h,"content_hash":h})
    for path,value in definitions.items():write(DEST/path,value)
    return definitions

def sample(schema):
    result={}
    for name in schema["required"]:
        spec=schema["fields"][name];kind=spec["type"]
        result[name]=ENUMS[spec["enum_domain"]][0] if spec.get("enum_domain") else spec["allowed_values"][0] if spec.get("allowed_values") else ("0"*64 if "hash" in name else "2026-09-12T00:00:00Z" if name.endswith("_at") or name in {"not_before"} else "x") if kind=="string" else 0 if kind=="integer" else False if kind=="boolean" else [] if kind=="array" else {"scope_id":"s","scope_expression":"all"} if name=="scope" else {}
    return result

def conversions():
    values=[
      ("R6-CONV-001","ValidationStatus","EvaluationPermission",{"VALID":"PERMITTED","INVALID":"PROHIBITED","BLOCKED":"BLOCKED","UNKNOWN":"POLICY_REQUIRED"},[]),
      ("R6-CONV-002","EvaluationValue","ConformanceInput",{"TRUE":"POTENTIALLY_CONFORMANT","FALSE":"POTENTIALLY_NON_CONFORMANT","UNKNOWN":"UNKNOWN","BLOCKED":"BLOCKED"},["INVALID"]),
      ("R6-CONV-003","ConformanceStatus","EligibilityInput",{"CONFORMANT":"PREDICATE_REQUIRED","PARTIALLY_CONFORMANT":"PREDICATE_REQUIRED","NON_CONFORMANT":"INELIGIBLE","UNVERIFIED":"UNKNOWN","BLOCKED":"BLOCKED","NOT_APPLICABLE":"UNKNOWN","UNKNOWN":"UNKNOWN"},[]),
      ("R6-CONV-004","ReleaseEligibility","AuthorizationInput",{"ELIGIBLE":"PERMITTED","INELIGIBLE":"PROHIBITED","BLOCKED":"BLOCKED","UNKNOWN":"POLICY_REQUIRED"},[]),
      ("R6-CONV-005","AuthorizationStatus","DecisionInput",{"AUTHORIZED":"APPROVAL_PERMITTED","REFUSED":"REJECTED","BLOCKED":"BLOCKED","UNKNOWN":"POLICY_REQUIRED"},["INVALID"]),
    ]
    return [hashed("r6-conversion:v1",{"rule_id":rid,"source_type":src,"target_type":target,"legal":legal,"forbidden":forbidden,"evidence_required":True,"policy_required":False,"failure":"REJECTED","generic_convert":False}) for rid,src,target,legal,forbidden in values]

def build_tests(schemas,rules):
    tests=[]
    def add(family,operation,data,expected,negative_ref=None):tests.append({"test_id":f"R6-T-{len(tests)+1:04d}","family":family,"operation":operation,"input":data,"expected":expected,"negative_ref":negative_ref})
    for domain,values in ENUMS.items():
        for value in values:add("T1_ENUM_CLOSURE","ENUM",{"domain":domain,"value":value},"VALID")
        add("T1_ENUM_CLOSURE","ENUM",{"domain":domain,"value":"__UNKNOWN__"},"UNKNOWN_VALUE")
        wrong="AUTHORIZED" if "AUTHORIZED" not in values else "ISSUED";add("T1_ENUM_CLOSURE","ENUM",{"domain":domain,"value":wrong},"WRONG_DOMAIN")
    for path,contract in schemas.items():
        good=sample(contract);add("T2_SCHEMA_VALIDITY","SCHEMA",{"schema_id":contract["schema_id"],"value":good},"VALID")
        for required in contract["required"]:
            bad=dict(good);bad.pop(required);add("T2_SCHEMA_VALIDITY","SCHEMA",{"schema_id":contract["schema_id"],"value":bad},"MISSING_REQUIRED")
        bad={**good,"undocumented":True};add("T2_SCHEMA_VALIDITY","SCHEMA",{"schema_id":contract["schema_id"],"value":bad},"UNKNOWN_FIELD")
    boundary=["INSTRUCTION_AS_NORMATIVE_REQUIREMENT","PROFILE_ALTERS_NORMATIVE_MEANING","VALID_TO_CONFORMANT","TRUE_TO_AUTHORIZED","AUTHORIZED_TO_EXECUTED","EXECUTION_TO_VERIFIED","ISSUED_TO_VALID","APPROVED_TO_SUCCEEDED","TEST_AS_REQUIREMENT","OBSERVATION_AS_EVIDENCE","IMPLEMENTATION_INHERITS_NORMATIVE_AUTHORITY","EVALUATOR_ISSUES_CERTIFICATE","EVALUATOR_MODIFIES_POLICY","EVALUATOR_MUTATES_HISTORY","EVALUATOR_EXECUTES_RELEASE"]
    for claim in boundary:add("T3_BOUNDARY_SEPARATION","BOUNDARY",{"claim":claim,"forbidden":True},"REJECTED")
    for code in ERRORS:
        add("T4_EVALUATOR_ERRORS","ERROR",{"code":code},"EVALUATION_FAILURE")
        for target in ["UNKNOWN","BLOCKED","INVALID","FALSE"]:
            permitted=target in ERROR_ALLOWED[code];add("T4_EVALUATOR_ERRORS","ERROR",{"code":code,"policy":{"mapping":target,"explicit":True,"profile_ref":"profile:r6"}},target if permitted else "EVALUATION_FAILURE")
    add("T4_EVALUATOR_ERRORS","ERROR",{"code":"EVALUATOR_TIMEOUT","policy":{"mapping":"UNKNOWN","explicit":False,"profile_ref":"profile:r6"}},"EVALUATION_FAILURE")
    add("T4_EVALUATOR_ERRORS","ERROR",{"code":"EVALUATOR_TIMEOUT","policy":{"mapping":"UNKNOWN","explicit":True}},"EVALUATION_FAILURE")
    add("T4_EVALUATOR_ERRORS","ERROR",{"code":"UNREGISTERED"},"EVALUATION_FAILURE")
    for rule in rules:
        for source,target in rule["legal"].items():add("T5_CONVERSION_RULES","CONVERT",{"rule_id":rule["rule_id"],"source_type":rule["source_type"],"source_value":source,"target_type":rule["target_type"],"evidence":["e"]},target)
        for source in rule["forbidden"]:add("T5_CONVERSION_RULES","CONVERT",{"rule_id":rule["rule_id"],"source_type":rule["source_type"],"source_value":source,"target_type":rule["target_type"],"evidence":["e"]},"REJECTED")
        first=next(iter(rule["legal"]));add("T5_CONVERSION_RULES","CONVERT",{"rule_id":rule["rule_id"],"source_type":rule["source_type"],"source_value":first,"target_type":rule["target_type"]},"REJECTED")
    context={key:True for key in ["structural","reference","integrity","temporal","scope","authority"]}
    for domain,values,legal in [("CertificateLifecycle",ENUMS["CertificateLifecycle"],CERTIFICATE_TRANSITIONS),("ReleaseExecutionStatus",ENUMS["ReleaseExecutionStatus"],EXECUTION_TRANSITIONS)]:
        for source in values:
            for target in values:add("T6_STATE_TRANSITIONS","TRANSITION",{"domain":domain,"source":source,"target":target,"context":context},"VALIDATED" if (source,target) in legal else "ILLEGAL_TRANSITION")
    for key in context:
        bad=dict(context);bad[key]=False;add("T6_STATE_TRANSITIONS","TRANSITION",{"domain":"CertificateLifecycle","source":"DRAFT","target":"ISSUED","context":bad},"TRANSITION_ERROR")
    history=[{"sequence_no":0,"validated":True,"committed":True,"event_hash":"a"},{"sequence_no":1,"validated":True,"committed":True,"event_hash":"b"}]
    add("T7_DETERMINISM","PROJECTION_COMPARE",{"left":history,"right":list(history),"profile_ref":"p","algorithm":"r6"},"SAME")
    add("T7_DETERMINISM","CANONICAL",{"left":{"b":2,"a":"e\u0301"},"right":{"a":"é","b":2}},"SAME")
    add("T7_DETERMINISM","HASH",{"left_domain":"event:v1","right_domain":"certificate:v1","value":{"a":1}},"DIFFERENT")
    add("T7_DETERMINISM","PROJECT",{"history":[history[1],history[0]],"profile_ref":"p","algorithm":"r6"},"INVALID_HISTORY")
    add("T7_DETERMINISM","PROJECT",{"history":[history[0],{**history[1],"sequence_no":2}],"profile_ref":"p","algorithm":"r6"},"MISSING_EVENT")
    negatives=[
      ("N-001","ENUM",{"domain":"EvaluationValue","value":"MAYBE"},"UNKNOWN_VALUE"),("N-002","ENUM",{"domain":"ValidationStatus","value":"ACCEPTED"},"UNKNOWN_VALUE"),
      ("N-003","BOUNDARY",{"claim":"VALID_TO_CONFORMANT","forbidden":True},"REJECTED"),("N-004","BOUNDARY",{"claim":"TRUE_TO_AUTHORIZED","forbidden":True},"REJECTED"),
      ("N-005","ERROR",{"code":"EVALUATOR_FAILURE","policy":{"mapping":"FALSE","explicit":True,"profile_ref":"p"}},"EVALUATION_FAILURE"),("N-006","ERROR",{"code":"EVALUATOR_TIMEOUT","policy":{"mapping":"UNKNOWN","explicit":False,"profile_ref":"p"}},"EVALUATION_FAILURE"),
      ("N-007","BOUNDARY",{"claim":"INSTRUCTION_AS_NORMATIVE_REQUIREMENT","forbidden":True},"REJECTED"),("N-008","BOUNDARY",{"claim":"PROFILE_ALTERS_NORMATIVE_MEANING","forbidden":True},"REJECTED"),
      ("N-009","BOUNDARY",{"claim":"ISSUED_TO_VALID","forbidden":True},"REJECTED"),("N-010","BOUNDARY",{"claim":"APPROVED_TO_SUCCEEDED","forbidden":True},"REJECTED"),
      ("N-011","BOUNDARY",{"claim":"INVALID_AUTHORITY_TO_AUTHORIZED","forbidden":True},"REJECTED"),("N-012","BOUNDARY",{"claim":"EXPIRED_AUTHORITY_TO_AUTHORIZED","forbidden":True},"REJECTED"),
      ("N-013","BOUNDARY",{"claim":"STALE_EVIDENCE_TO_TRUE","forbidden":True},"REJECTED"),("N-014","PROJECT",{"history":[{"sequence_no":0,"validated":False,"committed":True}],"profile_ref":"p","algorithm":"r6"},"INVALID_HISTORY"),
      ("N-015","PROJECT",{"history":[history[0],history[0]],"profile_ref":"p","algorithm":"r6"},"INVALID_HISTORY"),("N-016","PROJECT",{"history":[history[0],{**history[1],"sequence_no":2}],"profile_ref":"p","algorithm":"r6"},"MISSING_EVENT"),
      ("N-017","REUSE",{"old_basis":{"artifact":"a"},"new_basis":{"artifact":"b"}},"NOT_REUSABLE"),("N-018","ENUM",{"domain":"EvaluationValue","value":"__UNKNOWN__"},"UNKNOWN_VALUE")]
    for identifier,operation,data,expected in negatives:add("MINIMUM_NEGATIVE_SET",operation,data,expected,identifier)
    for number in range(1,19):add("MACHINE_INVARIANTS","INVARIANT",{"invariant_id":f"R6-I{number:02d}","condition":True},"SATISFIED")
    return tests

def spec_text():
    titles=["Purpose","Layer Model","Closed Enum Registry","Identifier Domains","Normative Requirement Schema","Implementation Requirement Schema","Implementation Instruction","ValidationResult","EvaluationResult","Evaluator Error","Evaluator Contract","Error Policy","Error Classification","Conformance Result","Explicit Conversion Matrix","State Transition Guard","Certificate Transitions","Release Execution Transitions","Event Contract","Projection Contract","Decision-Basis Reuse","Typed Pipeline","Rust Type-State Boundary","Conformance Test Categories","Minimum Negative Test Set","Machine-Checkable Invariants","Updated Artifact Tree","What R6 Resolves","What R6 Does Not Yet Define","Closure Assessment"]
    statements=["R6 converts frozen R5 semantics into a machine-oriented contract and introduces no semantic state.","Five planes are explicit and no plane implicitly inherits authority.","The supplied sixteen machine enums and four inherited frozen domains reject unknown values.","Semantic identifier domains remain distinct even when serialized as strings.","Normative obligations remain technology-neutral and machine-representable.","Implementation requirements require traceable normative and profile origins.","Instruction mandatory flags apply only within owning implementation authority.","Validation controls processing eligibility and never establishes proposition truth.","EvaluationResult records a completed evaluation and remains distinct from error.","Twelve observable errors preserve the eleven supplied codes plus inherited dependency-unavailable coverage.","Evaluator returns Result<EvaluationResult, EvaluationError> and has no higher-layer authority.","Error defaults to evaluation failure; semantic mapping requires explicit profile policy.","Infrastructure failure never becomes a false claim about the subject.","Conformance is requirement-bound and cannot be inferred from isolated TRUE.","Five named conversion contracts replace generic conversion.","State changes require structural, reference, integrity, temporal, scope, authority, and transition checks.","Only the five supplied certificate lifecycle edges are legal.","Only the six supplied release-execution edges are legal.","Invalid events are rejected in the declared validation order and never repaired.","Projection is deterministic from validated history, profile, and algorithm.","Changed decision basis is NOT_REUSABLE absent explicit safe compatibility.","Typed stages preserve independent validation, evaluation, conformance, authorization, decision, execution, and verification.","Typestate is an implementation technique; equivalent machine-checkable boundaries are required.","T1 through T7 are executable and mandatory.","N-001 through N-018 are executable negative vectors.","R6-I01 through R6-I18 are executable invariants.","Artifacts are physically grouped by semantics, plane, runtime, errors, conversions, transitions, Rust, and tests.","Closed enums, authority separation, and result/error separation resolve the supplied practical ambiguities.","Concrete production backends, predicate language, concurrency, and target integration remain implementation-only.","The machine contract is realized without v14.8 or a new semantic state; production implementation remains unverified."]
    return "# v14.7-R6 — Machine Schema and Typed Domain Realization\n\n"+"\n\n".join(f"## {i}. {title}\n{statements[i-1]}" for i,title in enumerate(titles,1))+"\n\n## Final Principle\nSemantic authority belongs to the defining layer. Evaluation produces a semantic result only on contractual completion; otherwise it produces an explicit evaluator error interpreted only by explicit policy.\n"

def main():
    successors=sorted(p.name for p in (COMP/"certification").glob("v14.7-R[7-9]*") if p.is_dir())
    if successors:raise RuntimeError(f"refusing to rewrite R6 after successor realization: {successors}")
    if not (PRE/"INDEPENDENT-VALIDATION.yaml").is_file():raise RuntimeError("validated R5 predecessor required")
    if DEST.exists():raise RuntimeError("refusing to regenerate immutable v14.7-R6 package")
    prior=[{"path":str(p.relative_to(COMP)),"sha256":sha(p),"bytes":p.stat().st_size} for p in sorted(COMP.rglob("*")) if p.is_file()]
    DEST.mkdir(parents=True);write(DEST/"SPECIFICATION.md",spec_text());schemas=build_schemas();rules=conversions()
    enum_aliases={"Validation":"ValidationStatus","Evaluation":"EvaluationValue","Conformance":"ConformanceStatus","Authorization":"AuthorizationStatus","ReleaseDecision":"ReleaseDecisionStatus","ReleaseExecution":"ReleaseExecutionStatus","PostReleaseVerification":"PostReleaseVerificationStatus","Reuse":"ReuseStatus","Authority":"AuthorityStatus","AuthorityQualification":"AuthorityQualificationStatus","FindingLifecycle":"FindingStatus","Remediation":"RemediationStatus","EventValidation":"EventValidationStatus","EventCommit":"EventCommitStatus","Projection":"ProjectionStatus","CertificateLifecycle":"CertificateLifecycle","CertificateValidity":"CertificateValidity","ReleaseEligibility":"ReleaseEligibility","RequirementLifecycle":"RequirementLifecycle","NormativeStrength":"NormativeStrength"}
    enum_objects=[hashed("r6-enum-domain:v1",{"machine_type":name,"values":values,"closed":True,"unknown_value":"REJECT","r5_domain":next(old for old,new in enum_aliases.items() if new==name),"origin":"SUPPLIED_R6" if name not in {"EventValidationStatus","EventCommitStatus","ProjectionStatus","NormativeStrength"} else "INHERITED_R5"}) for name,values in ENUMS.items()]
    enum_registry=hashed("r6-enum-registry:v1",{"objects":enum_objects,"domain_count":20,"supplied_r6_domains":16,"inherited_r5_domains":4,"value_count":111,"aliases":enum_aliases})
    identifiers=["SpecificationId","RequirementId","ProfileId","PredicateId","EvaluationId","ValidationId","EvidenceId","ImplementationId","AuthorityId","CertificateId","ReleaseId","DecisionId","EventId","FindingId","RemediationId","AcceptanceCriterionId","ProfileRequirementId","ImplementationRequirementId","InstructionId","TestId","ObservationId"]
    id_registry={"objects":[{"identifier_domain":x,"wire_type":"string","rust_newtype":x,"interchangeable":False} for x in identifiers],"generic_identifier_at_semantic_boundary":"FORBIDDEN"}
    error_objects=[]
    supplied=set(ERRORS[:-1])
    for code in ERRORS:error_objects.append(hashed("r6-evaluation-error:v1",{"code":code,"origin":"SUPPLIED_R6" if code in supplied else "INHERITED_R5","severity":["RECOVERABLE","TERMINAL"],"retry":"EXPLICIT_BOOLEAN","default":"EVALUATION_FAILURE","allowed_explicit_mappings":sorted(ERROR_ALLOWED[code]),"false_mapping":False,"mandatory_conformance":"BLOCKED_UNTIL_DISPOSITION","evidence_metadata":"REQUIRED_WHEN_ERROR_OBSERVED"}))
    transition_objects=[{"transition_id":f"CERT-{i:02d}","domain":"CertificateLifecycle","source":s,"target":t} for i,(s,t) in enumerate(sorted(CERTIFICATE_TRANSITIONS),1)]+[{"transition_id":f"EXEC-{i:02d}","domain":"ReleaseExecutionStatus","source":s,"target":t} for i,(s,t) in enumerate(sorted(EXECUTION_TRANSITIONS),1)]
    write(DEST/"CONVERSION-REGISTRY.yaml",{"objects":rules,"count":len(rules),"generic_convert":"FORBIDDEN"})
    schema_entries=[]
    for path,contract in schemas.items():schema_entries.append({"schema_id":contract["schema_id"],"path":path,"plane":contract["plane"],"sha256":sha(DEST/path)})
    write(DEST/"SCHEMA-REGISTRY.yaml",{"objects":schema_entries,"count":len(schema_entries),"language":"GDE-ABSTRACT-SCHEMA-1","dialect_binding":"IMPLEMENTATION_TASK","strict":True})
    tests=build_tests(schemas,rules);write(DEST/"tests/MACHINE-TESTS.yaml",{"objects":tests,"count":len(tests),"families":["T1_ENUM_CLOSURE","T2_SCHEMA_VALIDITY","T3_BOUNDARY_SEPARATION","T4_EVALUATOR_ERRORS","T5_CONVERSION_RULES","T6_STATE_TRANSITIONS","T7_DETERMINISM"]})
    results=run(DEST);passed=sum(x["status"]=="PASSED" for x in results);failed=len(results)-passed;write(DEST/"MACHINE-TEST-RESULTS.yaml",{"objects":results,"summary":{"total":len(results),"passed":passed,"failed":failed}})
    rust=rust_sources();rust_root=DEST/"rust/gde-v147-r6-machine"
    for path,content in rust.items():write(rust_root/path,content)
    cargo=shutil.which("cargo")
    if cargo:
        proc=subprocess.run([cargo,"test","--locked"],cwd=rust_root,capture_output=True,text=True);rust_build={"status":"PASS" if proc.returncode==0 else "FAIL","toolchain":True,"returncode":proc.returncode,"output_hash":hashlib.sha256((proc.stdout+proc.stderr).encode()).hexdigest()}
    else:rust_build={"status":"BLOCKED","toolchain":False,"reason":"RUST_TOOLCHAIN_UNAVAILABLE"}
    invariants=["All normative states belong to closed enums.","Unknown enum values cannot acquire semantic meaning.","Validation does not establish conformance.","Evaluation does not establish authorization.","Authorization does not establish execution.","Execution does not establish verification.","Evaluator errors do not become semantic results without explicit policy.","Evaluator failure cannot become FALSE.","Implementation instructions cannot create normative requirements.","Profile bindings cannot alter normative semantics.","ISSUED does not imply VALID.","APPROVED does not imply SUCCEEDED.","Invalid events cannot enter committed history.","Projection cannot mutate history.","Decision-basis changes invalidate unconditional reuse.","Every semantic transition has explicit source and target domains.","Every mandatory requirement receives deterministic conformance disposition.","No stronger semantic state may be produced from weaker or invalid evidence."]
    invariant_objects=[hashed("r6-invariant:v1",{"invariant_id":f"R6-I{i:02d}","statement":text,"test_ref":next(x["test_id"] for x in tests if x["family"]=="MACHINE_INVARIANTS" and x["input"]["invariant_id"]==f"R6-I{i:02d}"),"status":"SATISFIED"}) for i,text in enumerate(invariants,1)]
    planes=[{"plane":"NORMATIVE","contains":["Specification","NormativeRequirement","AcceptanceCriterion"]},{"plane":"PROFILE","contains":["SerializationBinding","HashBinding","PolicyBinding"]},{"plane":"IMPLEMENTATION","contains":["RustType","Validator","Evaluator"]},{"plane":"EVIDENCE","contains":["Test","Observation","Evidence"]},{"plane":"DECISION","contains":["Conformance","Authorization","Release"]}]
    basis=hashed("r6-basis:v1",{"realization_version":VERSION,"semantic_version":"v14.7","predecessor":{"path":"../v14.7-R5/SPECIFICATION.md","sha256":sha(PRE/"SPECIFICATION.md")},"r5_enum_registry_hash":load(PRE/"CLOSED-ENUM-REGISTRY.yaml")["content_hash"],"r6_specification_sha256":sha(DEST/"SPECIFICATION.md"),"new_semantic_states":False})
    test_hash=hashlib.sha256(canonical(tests)).hexdigest();report=hashed("r6-conformance-report:v1",{"report_id":"R6-CONFORMANCE","profile_ref":"gde-v14.7-r6-machine","implementation_ref":"r6-python-oracle","test_identity":test_hash,"passed":passed,"failed":failed,"rust_build":rust_build["status"],"result":"NON_CONFORMANT" if failed else ("UNVERIFIED" if rust_build["status"]!="PASS" else "CONFORMANT"),"generated_at":STAMP})
    base={"realization_version":VERSION,"semantic_version":"v14.7","epistemic_status":"SUPPORTED"}
    artifacts={
      "VERSION.yaml":{"title":"Machine Schema and Typed Domain Realization","predecessor":"v14.7-R5","new_semantic_states":False,"v14_8":False},
      "EXECUTIVE-RESULT.yaml":{"machine_enum_domains":20,"machine_enum_values":111,"schemas":len(schemas),"typed_identifier_domains":len(identifiers),"machine_tests":len(tests),"python_oracle":"CONFORMANT" if not failed else "NON_CONFORMANT","rust_build":rust_build["status"],"implementation_conformance":report["result"],"resolved_representation_conflicts":3,"semantic_contradictions":0,"conclusion":"NO_NEW_SEMANTIC_STATE_REQUIRED"},
      "SPECIFICATION-BASIS.yaml":basis,"PLANE-MODEL.yaml":{"objects":planes,"implicit_authority_inheritance":"FORBIDDEN","governing_rule":"NO_PLANE_MAY_ESTABLISH_A_STRONGER_CLAIM_THAN_ITS_AUTHORITY_AND_VALIDATED_INPUTS"},"CLOSED-ENUM-REGISTRY.yaml":enum_registry,"IDENTIFIER-DOMAINS.yaml":id_registry,
      "EVALUATOR-CONTRACT.yaml":{"interface":"evaluate(Predicate, ValidatedSubject, EvaluationContext) -> Result<EvaluationResult, EvaluationError>","ok_postcondition":"VALID_EVALUATION_RESULT","error_postcondition":"NO_VALID_EVALUATION_RESULT_PRODUCED","forbidden_operations":["ISSUE_CERTIFICATE","AUTHORIZE_OPERATION","APPROVE_RELEASE","MODIFY_POLICY","MODIFY_AUTHORITY","MUTATE_HISTORY","EXECUTE_RELEASE"]},
      "ERROR-POLICY.yaml":{"default":"EVALUATION_FAILURE","automatic_semantic_mapping":False,"explicit_profile_policy_required":True,"false_mapping":False,"objects":error_objects},
      "TRANSITION-REGISTRY.yaml":{"objects":transition_objects,"count":len(transition_objects),"unlisted_transition":"ILLEGAL","remediation_transition_binding":"PROFILE_RULE_REQUIRED","finding_transition_binding":"PROFILE_RULE_REQUIRED"},
      "TYPED-PIPELINE.yaml":{"success":["RawSubject","ValidatedSubject","EvaluationResult","ConformanceResult","ReleaseEligibility","AuthorizationResult","ReleaseDecision","ReleaseExecution","PostReleaseVerification"],"errors":["ValidationError","EvaluationError","ConformanceError","AuthorizationError","TransitionError","ProjectionError"],"error_as_semantic_result":"FORBIDDEN","typestate_normativity":"IMPLEMENTATION_TECHNIQUE"},
      "MACHINE-INVARIANTS.yaml":{"objects":invariant_objects,"count":18},
      "CONTRADICTIONS.yaml":{"objects":[{"id":"R6-C-001","kind":"REPRESENTATION_OMISSION","issue":"Supplied R6 abbreviated enum list omits EventValidation, EventCommit, and Projection frozen in R5.","resolution":"Retain as inherited machine types.","semantic_state_change":False,"status":"RESOLVED"},{"id":"R6-C-002","kind":"REPRESENTATION_OMISSION","issue":"NormativeStrength is referenced but omitted from the supplied enum block.","resolution":"Retain inherited closed domain.","semantic_state_change":False,"status":"RESOLVED"},{"id":"R6-C-003","kind":"ERROR_TAXONOMY_OMISSION","issue":"Supplied R6 error list omits inherited dependency-unavailable coverage.","resolution":"Retain EVALUATOR_DEPENDENCY_UNAVAILABLE.","semantic_state_change":False,"status":"RESOLVED"}],"unresolved_semantic_contradictions":0,"conclusion":"NO NEW SEMANTIC STATE REQUIRED"},
      "AMBIGUITIES.yaml":{"resolved":[{"id":"R6-A-001","topic":"STATE_REPRESENTATION","resolution":"CLOSED_ENUM_REGISTRY"},{"id":"R6-A-002","topic":"AUTHORITY_LEAKAGE","resolution":"FIVE_PLANES_AND_DISTINCT_OBJECTS"},{"id":"R6-A-003","topic":"EVALUATOR_FAILURE","resolution":"RESULT_ERROR_SEPARATION"}],"remaining_implementation_only":["JSON_SCHEMA_DIALECT_BINDING","PRODUCTION_RUST_CRATE","PREDICATE_LANGUAGE","EVENT_STORE_BACKEND","CONCURRENCY","PROPERTY_TEST_FRAMEWORK","CI_TARGET_BINDING"]},
      "MIGRATION-R5-TO-R6.yaml":{"source":"v14.7-R5","target":VERSION,"classification":"REPRESENTATION_REFINEMENT","machine_type_aliases":enum_aliases,"requires":["REVALIDATE_SCHEMA","REBIND_MACHINE_TYPE_NAMES","PRESERVE_R5_ERROR_COVERAGE","RETEST_TRANSITIONS","REHASH_R6_OBJECTS"],"source_validity_transfers":False,"new_semantic_states":False},
      "EPISTEMIC-CONCLUSIONS.yaml":{"objects":[{"claim":"R6 machine enums preserve every R5 frozen value.","status":"PROVED"},{"claim":"Finite R6 vectors pass the Python oracle.","status":"PROVED"},{"claim":"The Rust blueprint compiles.","status":"UNKNOWN"},{"claim":"A target implementation conforms.","status":"UNKNOWN"},{"claim":"Representation omissions are reconciled without semantic expansion.","status":"SUPPORTED"}]},
      "ANTI-REGRESSION.yaml":{"rules":["NO_ENUM_EXTENSION","NO_UNKNOWN_ENUM_COERCION","NO_GENERIC_SEMANTIC_ID","NO_PLANE_AUTHORITY_INHERITANCE","NO_VALID_TO_TRUE","NO_TRUE_TO_AUTHORIZED","NO_AUTHORIZED_TO_EXECUTED","NO_ISSUED_TO_VALID","NO_APPROVED_TO_SUCCEEDED","NO_ERROR_TO_FALSE","NO_INVALID_EVENT_COMMIT","NO_PROJECTION_REPAIR","NO_UNCONDITIONAL_REUSE_AFTER_BASIS_CHANGE","NO_V14_8"]},
      "ARTIFACT-TREE.yaml":{"groups":["semantics","normative","profile","implementation","evidence","runtime","errors","conversions","transitions","rust","tests"],"package_root":"certification/v14.7-R6","append_only":True},
      "REMAINING-IMPLEMENTATION-WORK.yaml":{"objects":["BIND_EXACT_JSON_SCHEMA_DIALECT","INSTALL_RUST_TOOLCHAIN_AND_COMPILE","IMPLEMENT_EVALUATOR_REGISTRY","SELECT_PREDICATE_LANGUAGE","IMPLEMENT_DURABLE_EVENT_STORE","IMPLEMENT_CONCURRENCY_BOUNDARY","SELECT_PROPERTY_TEST_FRAMEWORK","BIND_CI_TO_TARGET"],"semantic_reopening_required":False},
      "TEST-INDEX.yaml":{"families":[{"family":f,"count":sum(x["family"]==f for x in tests)} for f in sorted({x["family"] for x in tests})],"minimum_negative_ids":[f"N-{i:03d}" for i in range(1,19)],"test_identity":test_hash},"CONFORMANCE-REPORT.yaml":report,
      "RUST-TYPE-BLUEPRINT.yaml":{"path":"rust/gde-v147-r6-machine","files":len(rust),"manifest":[{"path":p,"sha256":sha(rust_root/p)} for p in sorted(rust)],"build":rust_build,"unsafe":False,"boxed_generic_errors":False},
      "CURRENT-STATUS.yaml":{"enum_vocabulary":"CLOSED","normative_authority":"CLOSED","implementation_separation":"CLOSED","evaluator_result_error":"CLOSED","conversion_boundaries":"CLOSED","core_transitions":"CLOSED","machine_contract":"REALIZED","production_rust":"UNVERIFIED","target":"UNVERIFIED"},
      "FINAL-PRINCIPLE.yaml":{"rule":"SEMANTIC_AUTHORITY_BELONGS_TO_DEFINING_LAYER_AND_EVALUATION_ERROR_INTERPRETATION_REQUIRES_EXPLICIT_POLICY"},
      "INDEPENDENT-VALIDATION.yaml":{"objects":[],"summary":{"pass":0,"fail":0,"blocked":0},"result":"AWAITING_INDEPENDENT_VALIDATION"}}
    for name,body in artifacts.items():write(DEST/name,body if name in {"SPECIFICATION-BASIS.yaml","CLOSED-ENUM-REGISTRY.yaml","CONFORMANCE-REPORT.yaml"} else {**base,**body})
    write(DEST/"semantics/state-enums.yaml",enum_registry);write(DEST/"semantics/state-domains.yaml",{"objects":[{"machine_type":x["machine_type"],"r5_domain":x["r5_domain"],"origin":x["origin"]} for x in enum_objects]});write(DEST/"semantics/invariants.yaml",{"objects":invariant_objects})
    write(DEST/"errors/evaluation-errors.yaml",{"objects":error_objects});write(DEST/"errors/validation-errors.yaml",{"codes":["STRUCTURAL","REFERENCE","INTEGRITY","TEMPORAL","SCOPE","POLICY","AUTHORITY","EVIDENCE","FRESHNESS"]});write(DEST/"errors/transition-errors.yaml",{"codes":["STRUCTURAL","REFERENCE","INTEGRITY","TEMPORAL","SCOPE","AUTHORITY","ILLEGAL_TRANSITION"]})
    for rule in rules:write(DEST/f"conversions/{rule['rule_id'].lower()}.yaml",rule)
    write(DEST/"transitions/certificate.yaml",{"domain":"CertificateLifecycle","legal":[{"source":s,"target":t} for s,t in sorted(CERTIFICATE_TRANSITIONS)]});write(DEST/"transitions/release.yaml",{"domain":"ReleaseExecutionStatus","legal":[{"source":s,"target":t} for s,t in sorted(EXECUTION_TRANSITIONS)]});write(DEST/"transitions/remediation.yaml",{"domain":"RemediationStatus","legal":"PROFILE_RULE_REQUIRED","invented_edges":False});write(DEST/"transitions/findings.yaml",{"domain":"FindingStatus","legal":"PROFILE_RULE_REQUIRED","invented_edges":False})
    after=[{"path":str(p.relative_to(COMP)),"sha256":sha(p),"bytes":p.stat().st_size} for p in sorted(COMP.rglob("*")) if p.is_file() and DEST not in p.parents]
    if prior!=after:raise RuntimeError("predecessor mutation")
    write(DEST/"PRIOR-INTEGRITY.yaml",{**base,"protected_artifact_count":len(prior),"artifacts":prior,"status":"PRESERVED"})
    files=sorted(str(p.relative_to(DEST)) for p in DEST.rglob("*") if p.is_file())
    # Manifest and validation report are generator-owned final entries.
    files=sorted(set(files+["GENERATOR-MANIFEST.yaml","VALIDATION-REPORT.yaml"]))
    write(DEST/"GENERATOR-MANIFEST.yaml",{**base,"paths":files,"count":len(files)});write(DEST/"VALIDATION-REPORT.yaml",{**base,"generator_owned":len(files),"schemas":len(schemas),"enum_domains":20,"enum_values":111,"tests":len(tests),"passed":passed,"failed":failed,"rust_build":rust_build["status"],"status":"AWAITING_INDEPENDENT_VALIDATION"})
    print(f"generated {len(files)} R6 artifacts; enums=20/111 schemas={len(schemas)} tests={len(tests)} predecessor={len(prior)}")
if __name__=="__main__":main()
