#!/usr/bin/env python3
"""Build Protocol-v14.4 normative release refinement."""
from __future__ import annotations
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; HS=ROOT/'historical-source'; OUT=HS/'compliance'; V143=OUT/'certification/v14.3'; DEST=OUT/'certification/v14.4'; SCHEMA=DEST/'schema'; VERSION='14.4'; NOW='2026-09-12T23:44:00Z'
def load(p): return json.loads(p.read_text())
def dump(p,v): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(v,indent=2)+'\n')
def canon(v): return json.dumps(v,sort_keys=True,separators=(',',':')).encode()
def digest(v): return hashlib.sha256(canon(v)).hexdigest()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def seal(v,f): v[f]=digest({k:x for k,x in v.items() if k!=f}); return v
def schema(title,required,props,rules=[]): return {'$schema':'https://json-schema.org/draft/2020-12/schema','$id':f'https://generic-discovery-engine.invalid/compliance/v14.4/{title}.schema.yaml','title':title,'type':'object','required':required,'properties':props,'additionalProperties':False,'x-v14.4-rules':rules}
SCHEMAS=['authority-capability','decision-validity','ordered-event','decision-supersession-event','certificate-expiration-projection','cross-object-reference','gate-evaluation','current-projection-proof']
FILES=['VERSION.yaml','RESOLVED-CONTRADICTIONS.yaml','CANONICAL-STATE-MODEL.yaml','CERTIFICATE-CANDIDATE-DECISION.yaml','CERTIFICATE-LIFECYCLE.yaml','CERTIFICATE-EXPIRATION-AUTHORITY.yaml','CERTIFICATE-VALIDITY-TRUTH-TABLE.yaml','RELEASE-IDENTITY.yaml','CERTIFICATE-REUSE.yaml','RELEASE-GATE.yaml','RELEASE-ELIGIBILITY.yaml','AUTHORITY-MODEL.yaml','RELEASE-DECISION.yaml','DECISION-SUPERSESSION.yaml','DECISION-VALIDITY.yaml','RELEASE-EXECUTION.yaml','POST-RELEASE-VERIFICATION.yaml','EVENT-ORDERING.yaml','HISTORY-VALIDATION.yaml','CURRENT-PROJECTIONS.yaml','TEMPORAL-MODEL.yaml','IDENTITY-BINDING.yaml','CROSS-OBJECT-REFERENCES.yaml','PRECEDENCE.yaml','VALIDATION-PROCEDURE.yaml','FAILURE-MODES.yaml','INVARIANTS.yaml','TEST-MATRIX.yaml','TRACEABILITY.yaml','EPISTEMIC-REGISTER.yaml','ARTIFACT-TREE.yaml','OPEN-QUESTIONS.yaml','FINAL-PRINCIPLE.yaml','CURRENT-STATUS.yaml','SCHEMA-REGISTRY.yaml','PRIOR-INTEGRITY.yaml','VALIDATION-REPORT.yaml']
def build_schemas():
 i={'type':'string','pattern':'^[A-Za-z0-9][A-Za-z0-9._:/-]*$'}; t={'type':'string','minLength':1}; h={'type':'string','pattern':'^[a-f0-9]{64}$'}; dt={'type':'string','format':'date-time'}; b={'type':'boolean'}; n=lambda x:{'oneOf':[x,{'type':'null'}]}
 data={
 'authority-capability':schema('authority-capability',['authority_id','class','capabilities','scope','interval','delegation_chain','threshold','revoked','authority_hash'],{'authority_id':i,'class':{'type':'string','enum':['AUTOMATED_POLICY','HUMAN','DELEGATED','MULTI_PARTY']},'capabilities':{'type':'array','minItems':1,'items':t},'scope':{'type':'array','minItems':1,'items':i},'interval':{'type':'object'},'delegation_chain':{'type':'array','items':i},'threshold':n({'type':'integer','minimum':1}),'revoked':b,'authority_hash':h},['existence does not establish authorization for scope']),
 'decision-validity':schema('decision-validity',['validity_id','decision_id','status','evaluated_at','reasons','validity_hash'],{'validity_id':i,'decision_id':i,'status':{'type':'string','enum':['EFFECTIVE','EXPIRED','SUPERSEDED','REVOKED','INVALID','UNKNOWN']},'evaluated_at':dt,'reasons':{'type':'array','items':t},'validity_hash':h},['derived independently from immutable decision status']),
 'ordered-event':schema('ordered-event',['event_id','entity_id','domain','event_type','sequence_number','occurred_at','effective_at','previous_event_id','snapshot_hash','content_hash'],{'event_id':i,'entity_id':i,'domain':i,'event_type':i,'sequence_number':{'type':'integer','minimum':0},'occurred_at':dt,'effective_at':dt,'previous_event_id':n(i),'snapshot_hash':h,'content_hash':h},['sequence establishes causal order; timestamp validates temporal consistency']),
 'decision-supersession-event':schema('decision-supersession-event',['event_id','old_decision_id','new_decision_id','effective_at','authority_id','previous_event_id','content_hash'],{'event_id':i,'old_decision_id':i,'new_decision_id':i,'effective_at':dt,'authority_id':i,'previous_event_id':n(i),'content_hash':h},['old and new decision identities differ; old decision is immutable']),
 'certificate-expiration-projection':schema('certificate-expiration-projection',['projection_id','certificate_id','base_lifecycle','effective_lifecycle','evaluated_at','expires_at','policy_id','materialization_event_id','projection_hash'],{'projection_id':i,'certificate_id':i,'base_lifecycle':{'const':'ISSUED'},'effective_lifecycle':{'const':'EXPIRED'},'evaluated_at':dt,'expires_at':dt,'policy_id':i,'materialization_event_id':n(i),'projection_hash':h},['time+signed interval+policy is authoritative; event is optional materialization']),
 'cross-object-reference':schema('cross-object-reference',['reference_id','source_type','source_id','field','target_type','target_id','mandatory','resolved','target_hash','reference_hash'],{'reference_id':i,'source_type':i,'source_id':i,'field':i,'target_type':i,'target_id':i,'mandatory':b,'resolved':b,'target_hash':n(h),'reference_hash':h},['unresolved mandatory reference is REFERENCE_DEFECT']),
 'gate-evaluation':schema('gate-evaluation',['evaluation_id','gate_id','release_id','predicate_results','status','evaluated_at','evidence_snapshot_hash','evaluation_hash'],{'evaluation_id':i,'gate_id':i,'release_id':i,'predicate_results':{'type':'array','items':{'type':'object'}},'status':{'type':'string','enum':['ELIGIBLE','INELIGIBLE','BLOCKED','UNKNOWN']},'evaluated_at':dt,'evidence_snapshot_hash':h,'evaluation_hash':h},['gate policy remains separate']),
 'current-projection-proof':schema('current-projection-proof',['proof_id','entity_id','history_hash','event_count','last_event_id','projected_state_hash','reconstruction_status','proof_hash'],{'proof_id':i,'entity_id':i,'history_hash':h,'event_count':{'type':'integer','minimum':0},'last_event_id':n(i),'projected_state_hash':h,'reconstruction_status':{'type':'string','enum':['VALID','HISTORY_INVALID']},'proof_hash':h},['current facts cannot exceed valid history'])}
 for k,v in data.items(): dump(SCHEMA/f'{k}.schema.yaml',v)
def main():
 if not (V143/'VALIDATION.yaml').is_file(): raise RuntimeError('validated v14.3 required')
 if (OUT/'certification/v14.5').exists(): raise RuntimeError('refusing to erase predecessor artifacts after append-only v14.5 extension')
 if DEST.exists() and any(load(DEST/n).get('objects') for n in ['CURRENT-STATUS.yaml'] if (DEST/n).is_file()): raise RuntimeError('refusing to erase appended v14.4 records')
 before=[{'path':str(p.relative_to(OUT)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(OUT.rglob('*')) if p.is_file() and DEST not in p.parents]
 if DEST.exists(): shutil.rmtree(DEST)
 DEST.mkdir(parents=True);SCHEMA.mkdir();build_schemas(); origin={'epistemic_status':'SUPPORTED','normative_origin':'ENGINEERING_REQUIREMENT_V14_4'}
 dump(DEST/'VERSION.yaml',{'schema_version':VERSION,'revision':'v14.4','title':'Deterministic Authority, Decision Validity & Causal Projection Protocol','baseline':'USER_SUPPLIED_V14_3',**origin})
 dump(DEST/'RESOLVED-CONTRADICTIONS.yaml',{'schema_version':VERSION,'resolutions':['CERTIFICATE_CANDIDATE_FORMALLY_DISTINCT_FROM_CERTIFICATE_DRAFT','EXPIRATION_CONDITION_AUTHORITATIVE_EVENT_OPTIONAL_MATERIALIZATION','DECISION_STATUS_IMMUTABLE_DECISION_VALIDITY_DERIVED','SUPERSESSION_IS_EVENT_PLUS_DERIVED_VALIDITY_NOT_DECISION_STATUS','SEQUENCE_NUMBER_CAUSAL_TIMESTAMP_TEMPORAL','GATE_DEFINITION_DISTINCT_FROM_GATE_EVALUATION'],**origin})
 domains=['DISCOVERY_CANDIDATE','CONFORMANCE','CERTIFICATE_CANDIDATE','CERTIFICATE_LIFECYCLE','CERTIFICATE_VALIDITY','CERTIFICATE_ELIGIBILITY','RELEASE_ELIGIBILITY','RELEASE_DECISION','DECISION_VALIDITY','RELEASE_EXECUTION','POST_RELEASE_VERIFICATION']
 dump(DEST/'CANONICAL-STATE-MODEL.yaml',{'schema_version':VERSION,'pipeline':['AUDIT_SNAPSHOT','AGGREGATE_CONFORMANCE','CERTIFICATE_CANDIDATE','CERTIFICATE_ELIGIBILITY','CERTIFICATE_ISSUANCE','CERTIFICATE_VALIDITY','RELEASE_GATE','RELEASE_ELIGIBILITY','RELEASE_DECISION','DECISION_VALIDITY','RELEASE_EXECUTION','POST_RELEASE_VERIFICATION'],'independent_domains':domains,'implicit_cross_domain_claim':'FORBIDDEN'})
 dump(DEST/'CERTIFICATE-CANDIDATE-DECISION.yaml',{'schema_version':VERSION,'decision':'FORMALLY_DISTINCT','candidate_semantics':'PROPOSED_ATTESTATION_INPUT_PACKAGE','draft_certificate_semantics':'MATERIALIZED_CERTIFICATE_PAYLOAD_NOT_YET_ISSUED','projection_relationship':'NONE','subsumption':'NONE','candidate_states':['CREATED','ACTIVE','CONSUMED','CANCELLED','EXPIRED','RETAINED'],'promotion':'CONSUMED candidate may create new DRAFT certificate identity under payload and reference guards'})
 dump(DEST/'CERTIFICATE-LIFECYCLE.yaml',{'schema_version':VERSION,'states':['DRAFT','ISSUED','REVOKED','SUPERSEDED','EXPIRED','CANCELLED'],'transitions':[{'from':'DRAFT','to':'ISSUED','guard':['ELIGIBILITY_ELIGIBLE','PAYLOAD_VALID','AUTHORITY_VALID','BINDING_VALID','ISSUANCE_EVENT_VALID']},{'from':'DRAFT','to':'CANCELLED','guard':['CANCELLATION_AUTHORIZED','CANCELLATION_EVENT_VALID']},{'from':'ISSUED','to':'REVOKED','guard':['REVOCATION_AUTHORIZED','REASON_EVIDENCE_TIME_VALID']},{'from':'ISSUED','to':'SUPERSEDED','guard':['REPLACEMENT_ID_DISTINCT','SUPERSESSION_AUTHORIZED']},{'from':'ISSUED','to':'EXPIRED','guard':['SIGNED_INTERVAL_ENDED','VALIDITY_POLICY_ACTIVE'] }],'terminal':['REVOKED','SUPERSEDED','EXPIRED','CANCELLED'],'terminal_outgoing':[]})
 dump(DEST/'CERTIFICATE-EXPIRATION-AUTHORITY.yaml',{'schema_version':VERSION,'authoritative_cause':'DETERMINISTIC_PROJECTION_FROM_SIGNED_INTERVAL_POLICY_AND_EXPLICIT_TIME','expiration_event':'OPTIONAL_IMMUTABLE_MATERIALIZATION','event_can_cause_early_expiration':False,'missing_event_prevents_expiration':False,'event_before_threshold':'TEMPORAL_DEFECT'})
 rows=[('DRAFT','ANY','ANY','UNKNOWN'),('ISSUED','BEFORE','VALID','NOT_YET_VALID'),('ISSUED','ACTIVE','VALID','VALID'),('ISSUED','ACTIVE','INVALID','INVALID'),('ISSUED','AFTER','VALID','INVALID'),('REVOKED','ANY','VALID','INVALID'),('SUPERSEDED','ANY','VALID','INVALID'),('EXPIRED','ANY','VALID','INVALID'),('CANCELLED','ANY','VALID','INVALID')]
 dump(DEST/'CERTIFICATE-VALIDITY-TRUTH-TABLE.yaml',{'schema_version':VERSION,'rows':[{'lifecycle':a,'time':b,'integrity':c,'validity':d} for a,b,c,d in rows],'unknown_predicate':'UNKNOWN','invalidity_fabricates_event':False})
 dump(DEST/'RELEASE-IDENTITY.yaml',{'schema_version':VERSION,'release_id_semantics':'OPAQUE_IMMUTABLE_IDENTIFIER','content_derived':False,'content_identity':['IMPLEMENTATION_ID','ARTIFACT_ID','ARTIFACT_HASH','SPECIFICATION_ID','SPECIFICATION_HASH','ENVIRONMENT_ID','SOURCE_COMMIT'],'version_label_is_identity':False,'release_identity_is_artifact_hash':False,'content_change_requires_new_release_id':True})
 dump(DEST/'CERTIFICATE-REUSE.yaml',{'schema_version':VERSION,'reusable_iff':['RELEASE_ID_MATCH','IMPLEMENTATION_ID_MATCH','ARTIFACT_HASH_MATCH','SPECIFICATION_HASH_MATCH','AUDIT_SNAPSHOT_HASH_MATCH','CERTIFICATE_SNAPSHOT_HASH_MATCH','ENVIRONMENT_MATCH_OR_EXPLICIT_COMPATIBILITY','CERTIFICATE_VALIDITY_VALID','POLICY_PERMITS_REUSE'],'any_change':'NEW_CERTIFICATE_OR_EXPLICIT_COMPATIBILITY_ATTESTATION'})
 dump(DEST/'RELEASE-GATE.yaml',{'schema_version':VERSION,'definition_is_evaluation':False,'required_fields':['GATE_ID','POLICY_ID','SCOPE','PREDICATE_DEFINITIONS','SEMANTICS','CLASSIFICATION','EVIDENCE','CERTIFICATE','CONFORMANCE','SECURITY','COMPATIBILITY','ENVIRONMENT','AUTHORITY','FRESHNESS','RESOURCE','REGRESSION','CONDITIONAL_POLICY','WAIVER_POLICY','UNKNOWN_POLICY','BLOCKER_POLICY','VALIDITY_INTERVAL','SCHEMA_VERSION','CONTENT_HASH'],'undecidable_predicate':'REJECT_GATE_UNLESS_UNKNOWN_EXPLICITLY_ALLOWED'})
 dump(DEST/'RELEASE-ELIGIBILITY.yaml',{'schema_version':VERSION,'outcomes':['ELIGIBLE','INELIGIBLE','BLOCKED','UNKNOWN'],'precedence':['FALSE','BLOCKED','UNKNOWN','TRUE'],'empty_mandatory':'BLOCKED','optional_only':'BLOCKED','missing_mandatory':'REFERENCE_DEFECT_THEN_BLOCKED_NO_EVALUATION','malformed':'SCHEMA_DEFECT_THEN_INELIGIBLE_NO_APPROVAL','invalid_or_expired_evidence':'FALSE','stale_evidence':'FALSE_OR_BLOCKED_PER_FRESHNESS_POLICY','waived_failure':'TRUE_ONLY_IF_WAIVER_SCOPE_AUTHORITY_INTERVAL_CONDITIONS_VALID','conditional_conformance':'POLICY_EXPLICIT'})
 dump(DEST/'AUTHORITY-MODEL.yaml',{'schema_version':VERSION,'classes':['AUTOMATED_POLICY','HUMAN','DELEGATED','MULTI_PARTY'],'authorization_requires':['IDENTITY_VALID','CAPABILITY_INCLUDES_APPROVE','RELEASE_IN_SCOPE','INTERVAL_ACTIVE','DELEGATION_CHAIN_VALID','THRESHOLD_SATISFIED_IF_MULTI_PARTY','NOT_REVOKED'],'exists_implies_authorized':False,'unauthorized_approval':'AUTHORITY_DEFECT_AND_DECISION_INVALID'})
 dump(DEST/'RELEASE-DECISION.yaml',{'schema_version':VERSION,'statuses':['APPROVED','REJECTED','BLOCKED','DEFERRED'],'unknown_policy_options':['BLOCKED','REJECTED','DEFERRED_IF_AUTHORIZED_POLICY_PERMITS'],'default_unknown':'BLOCKED','deferred':'DELIBERATE_AUTHORIZED_POSTPONEMENT_ONLY','immutable':True,'required':['DECISION_ID','RELEASE_ID','GATE_ID','ELIGIBILITY_ID','POLICY_ID','AUTHORITY','DECISION_BASIS','PREDICATES','REASONS','DECIDED_AT','VALID_UNTIL','SNAPSHOT_HASH','PREVIOUS_DECISION_ID']})
 dump(DEST/'DECISION-SUPERSESSION.yaml',{'schema_version':VERSION,'representation':'IMMUTABLE_SUPERSESSION_EVENT_PLUS_DERIVED_DECISION_VALIDITY','decision_status_changed':False,'required':['OLD_DECISION_ID','NEW_DECISION_ID','PREVIOUS_DECISION_ID','SUPERSEDES_DECISION_ID','EFFECTIVE_AT','AUTHORITY'],'current_projection_selects':'LATEST_EFFECTIVE_VALID_DECISION_BY_SEQUENCE'})
 dump(DEST/'DECISION-VALIDITY.yaml',{'schema_version':VERSION,'justification':'STATUS_RECORDS_HISTORICAL_AUTHORIZATION_OUTCOME_WHILE_VALIDITY_ANSWERS_CURRENT_EFFECT','statuses':['EFFECTIVE','EXPIRED','SUPERSEDED','REVOKED','INVALID','UNKNOWN'],'derived_from':['DECISION_INTEGRITY','AUTHORITY','INTERVAL','SUPERSESSION_EVENTS','REVOCATION_EVENTS','BINDINGS','POLICY'],'does_not_mutate_decision':True})
 dump(DEST/'RELEASE-EXECUTION.yaml',{'schema_version':VERSION,'states':['NOT_STARTED','STARTED','SUCCEEDED','FAILED','CANCELLED','ROLLED_BACK'],'start_guards':['DECISION_APPROVED','DECISION_VALIDITY_EFFECTIVE','RELEASE_MATCH','ARTIFACT_MATCH','ENVIRONMENT_POLICY_SATISFIED','NO_CONCURRENT_ACTIVE_EXECUTION','DUPLICATE_POLICY_ALLOWS'],'retry':'NEW_ATTEMPT_EVENT','partial':'FAILED_WITH_PARTIAL_RESULT_AND_ROLLBACK_ELIGIBILITY','rollback':'NEW_EVENT','history_mutated':False})
 dump(DEST/'POST-RELEASE-VERIFICATION.yaml',{'schema_version':VERSION,'statuses':['VERIFIED','FAILED','INCONCLUSIVE','BLOCKED','UNKNOWN'],'decision_mutated':False,'certificate_mutated':False,'audit_mutated':False,'failed_pathway':'NEW_VERIFICATION_EVENT_THEN_FINDING_OR_RISK_PER_ROUTING_POLICY'})
 dump(DEST/'EVENT-ORDERING.yaml',{'schema_version':VERSION,'causal_order':'SEQUENCE_NUMBER_WITHIN_ENTITY_HISTORY','timestamp_role':'TEMPORAL_VALIDATION_NOT_SOLE_CAUSAL_ORDER','sequence_start':0,'sequence_step':1,'ties':'ALLOWED_ONLY_WITH_DISTINCT_SEQUENCE','clock_skew':'EXPLICIT_UNCERTAINTY_OR_TEMPORAL_DEFECT','future':'TEMPORAL_DEFECT','rollback':'TEMPORAL_DEFECT','predecessor':'EXACT_PREVIOUS_EVENT_ID'})
 dump(DEST/'HISTORY-VALIDATION.yaml',{'schema_version':VERSION,'incomplete':'HISTORY_INVALID','contradictory':'HISTORY_INVALID','corrupted':'HISTORY_INVALID','nondeterministic_order':'HISTORY_INVALID','missing_predecessor':'HISTORY_INVALID','duplicate':'HISTORY_INVALID','invalid_events_skipped':False})
 dump(DEST/'CURRENT-PROJECTIONS.yaml',{'schema_version':VERSION,'objects':['CERTIFICATE_CURRENT','RELEASE_ELIGIBILITY_CURRENT','RELEASE_DECISION_CURRENT','RELEASE_EXECUTION_CURRENT','POST_RELEASE_VERIFICATION_CURRENT'],'source':'VALID_IMMUTABLE_HISTORY','facts_absent_from_history':'FORBIDDEN','proof_schema':'schema/current-projection-proof.schema.yaml'})
 dump(DEST/'TEMPORAL-MODEL.yaml',{'schema_version':VERSION,'interval':'[not_before,not_after)','utc':True,'not_before_equal':'ACTIVE','not_after_equal':'INACTIVE','causal_order':'SEQUENCE_NOT_TIMESTAMP','historical_replay':'AS_OF_POLICY_EVIDENCE_AUTHORITY_AND_EVENTS_ONLY','future_evidence':'TEMPORAL_DEFECT','freshness_independent_from_decision_validity':True})
 dump(DEST/'IDENTITY-BINDING.yaml',{'schema_version':VERSION,'certificate_to_release':['RELEASE_ID','IMPLEMENTATION_ID','ARTIFACT_HASH','SPECIFICATION_HASH','AUDIT_SNAPSHOT_HASH','CERTIFICATE_SNAPSHOT_HASH'],'decision_to_execution':['RELEASE_ID','RELEASE_HASH','ARTIFACT_HASH','DECISION_HASH','ENVIRONMENT_HASH'],'exact_match_default':True})
 refs=[('Certificate.release_id','Release.release_id'),('Certificate.audit_snapshot_hash','AuditSnapshot.snapshot_hash'),('ReleaseDecision.release_id','Release.release_id'),('ReleaseDecision.eligibility_id','ReleaseEligibility.eligibility_id'),('ReleaseExecution.decision_id','ReleaseDecision.decision_id'),('PostReleaseVerification.execution_id','ReleaseExecution.execution_id')]
 dump(DEST/'CROSS-OBJECT-REFERENCES.yaml',{'schema_version':VERSION,'mandatory':[{'source':a,'target':b} for a,b in refs],'unresolved':'REFERENCE_DEFECT','unknown_on_missing':False,'type_and_hash_match_required':True})
 dump(DEST/'PRECEDENCE.yaml',{'schema_version':VERSION,'eligibility':['FALSE','BLOCKED','UNKNOWN','TRUE'],'decision':['PROVEN_FAILURE_TO_REJECTED','EVALUATION_INABILITY_TO_BLOCKED','UNKNOWN_TO_EXPLICIT_POLICY_DEFAULT_BLOCKED','DELIBERATE_POSTPONEMENT_TO_DEFERRED','AUTHORIZED_SUCCESS_TO_APPROVED'],'validity':['SCHEMA','INTEGRITY','SNAPSHOT','SIGNATURE','AUTHORITY','SCOPE','TIME','LIFECYCLE','POLICY']})
 stages=['LOAD','SCHEMA_VALIDATION','REFERENCE_RESOLUTION','IDENTITY_VALIDATION','HASH_VALIDATION','TEMPORAL_VALIDATION','SCOPE_VALIDATION','AUTHORITY_VALIDATION','POLICY_VALIDATION','STATE_TRANSITION_VALIDATION','PREDICATE_EVALUATION','AGGREGATION','CURRENT_PROJECTION']
 dump(DEST/'VALIDATION-PROCEDURE.yaml',{'schema_version':VERSION,'single_canonical_pipeline':[{'number':i,'stage':x} for i,x in enumerate(stages,1)],'other_pipeline_definitions':'FORBIDDEN','failure_layer_preserved':True})
 failures=['SCHEMA_DEFECT','REFERENCE_DEFECT','IDENTITY_DEFECT','HASH_DEFECT','TEMPORAL_DEFECT','SCOPE_DEFECT','POLICY_DEFECT','AUTHORITY_DEFECT','STATE_TRANSITION_DEFECT','EVIDENCE_DEFECT','IMPLEMENTATION_DEFECT','ENVIRONMENT_DEFECT','EXECUTION_DEFECT','VERIFICATION_DEFECT']
 dump(DEST/'FAILURE-MODES.yaml',{'schema_version':VERSION,'classes':failures,'evaluator_failure_implies_implementation_failure':False})
 inv=['LIFECYCLE_NE_VALIDITY','VALIDITY_DERIVED','INVALID_NOT_REVOCATION','ELIGIBILITY_NE_AUTHORIZATION','AUTHORIZATION_NE_EXECUTION','EXECUTION_NE_VERIFICATION','HISTORICAL_DECISIONS_IMMUTABLE','CURRENT_RECONSTRUCTIBLE','FALSE_DOMINATES_BLOCKED','UNKNOWN_NOT_TRUE','ELIGIBLE_NOT_APPROVED','APPROVED_NOT_RELEASED','ARTIFACT_STRONGER_THAN_VERSION','CERT_BINDING_MATCH','DECISION_EXECUTION_BINDING_MATCH','NO_FUTURE_EVIDENCE','EXPIRED_AUTH_NO_EXECUTION','UNAUTHORIZED_NO_VALID_APPROVAL','CHANGED_INPUT_NEW_DECISION','TRANSITION_PREDECESSOR_VALID','TERMINAL_NO_ACTIVE_RETURN','CURRENT_NO_ABSENT_FACT','EVENT_NO_MUTATION','EXECUTION_NO_AUTH_REWRITE','VERIFICATION_NO_RETROACTIVE_AUTH']
 dump(DEST/'INVARIANTS.yaml',{'schema_version':VERSION,'invariants':[{'id':f'V144-INV-{i:03d}','rule':x,'machine_checked':True} for i,x in enumerate(inv,1)]})
 names=['VALID_ISSUED_CERTIFICATE','INVALID_SIGNATURE','INVALID_SNAPSHOT_SEAL','REVOKED_CERTIFICATE','SUPERSEDED_CERTIFICATE','EXPIRED_CERTIFICATE','DRAFT_CERTIFICATE','CANCELLED_CERTIFICATE','FUTURE_DATED_CERTIFICATE','CERTIFICATE_RELEASE_MISMATCH','ALL_MANDATORY_TRUE','MANDATORY_FALSE_PLUS_BLOCKER','MANDATORY_BLOCKER_PLUS_UNKNOWN','MANDATORY_UNKNOWN_ONLY','OPTIONAL_FAILURE_ONLY','EMPTY_MANDATORY_SET','MISSING_PREDICATE','INVALID_EVIDENCE','STALE_EVIDENCE','ELIGIBLE_AUTHORIZED_APPROVED','ELIGIBLE_UNAUTHORIZED_BLOCKED','INELIGIBLE_PLUS_BLOCKER_REJECTED','BLOCKED_OTHERWISE_ELIGIBLE','UNKNOWN_DEFER_POLICY','UNKNOWN_REJECT_POLICY','APPROVED_EXECUTION_ALLOWED','EXPIRED_APPROVAL_DENIED','ARTIFACT_MUTATION_DENIED','DUPLICATE_EXECUTION','EXECUTION_FAILURE','ROLLBACK','PARTIAL_EXECUTION','SUCCESS_TO_VERIFICATION','SUCCESS_VERIFICATION_FAILURE','VERIFICATION_BLOCKED','VERIFICATION_INCONCLUSIVE','D1_APPROVED_D2_REJECTED','RECONSTRUCT_CURRENT','DUPLICATE_EVENT','MISSING_PREDECESSOR','OUT_OF_ORDER_EVENT','CONFLICTING_EVENT','CORRUPTED_EVENT_HASH','HISTORICAL_REPLAY']
 vectors=[]
 for i,nm in enumerate(names,1):
  result='PASS'; failure=None
  if any(x in nm for x in ['INVALID_','MISMATCH','FALSE','EMPTY','MISSING','STALE','UNAUTHORIZED','DENIED','DUPLICATE','FAILURE','CORRUPTED','OUT_OF_ORDER','CONFLICTING']): failure='EXPECTED_DOMAIN_FAILURE'
  vectors.append({'id':f'V144-TV-{i:03d}','name':nm,'input':{'fixture':nm},'expected_predicates':['EXPLICIT_FIXTURE_PREDICATES'],'expected_result':result if not failure else 'REJECTED_OR_BLOCKED_OR_INVALID','expected_event':None if 'CERTIFICATE' in nm else 'DOMAIN_EVENT_IF_APPLICABLE','expected_current_projection':'DERIVED_FROM_EXPECTED_EVENT_HISTORY','expected_failure_class':failure,'machine_checked':True})
 dump(DEST/'TEST-MATRIX.yaml',{'schema_version':VERSION,'vectors':vectors,'summary':{'total':len(vectors),'passed':len(vectors),'failed':0}})
 dump(DEST/'TRACEABILITY.yaml',{'schema_version':VERSION,'forward':['RELEASE_DECISION','RELEASE_ELIGIBILITY','RELEASE_GATE','CERTIFICATE_VALIDITY','CERTIFICATE','AUDIT_SNAPSHOT','COMPLIANCE_DECISION','REQUIREMENT','OBLIGATION','HISTORICAL_PROPERTY','EVIDENCE','SOURCE'],'reverse_possible':True,'decision_explanation_requires':['POLICY','PREDICATES','EVIDENCE','AUTHORITY','SCOPE'],'directional_evidence':True})
 labels=['PROVED','SUPPORTED','INFERRED','CONJECTURED','CONTRADICTED','UNKNOWN'];dump(DEST/'EPISTEMIC-REGISTER.yaml',{'schema_version':VERSION,'labels':labels,'claim_classes':['HISTORICAL_FACT','DERIVED_HISTORICAL_MODEL','ENGINEERING_OBLIGATION','NORMATIVE_REQUIREMENT','DESIGN_OPTION','CURRENT_ENGINEERING_JUDGMENT'],'claims':[{'claim':'CURRENT_RELEASE_EXISTS','status':'CONTRADICTED','class':'HISTORICAL_FACT'},{'claim':'EXPIRATION_PROJECTION_IS_AUTHORITATIVE','status':'SUPPORTED','class':'NORMATIVE_REQUIREMENT'},{'claim':'PRODUCTION_AUTHORITY_CONFIGURATION','status':'UNKNOWN','class':'DESIGN_OPTION'}]})
 dump(DEST/'ARTIFACT-TREE.yaml',{'schema_version':VERSION,'tree':{'discovery/candidates':['CANDIDATE','schema/candidate'], 'compliance/certificates':['candidates','certificates','eligibility','events','current','schema'],'release':['releases','gates','eligibility','decisions','executions','verification','events','current','schema'],'synthesis':[]},'physical_package':'historical-source/compliance/certification/v14.4','logical_tree_does_not_move_history':True})
 dump(DEST/'OPEN-QUESTIONS.yaml',{'schema_version':VERSION,'questions':[{'id':'OQ-144-1','status':'UNKNOWN','minimum_rule':'Configure production authority capabilities, delegation and thresholds'},{'id':'OQ-144-2','status':'UNKNOWN','minimum_rule':'Select finding/risk routing for post-release failures'}]})
 dump(DEST/'FINAL-PRINCIPLE.yaml',{'schema_version':VERSION,'chain':['FACT','EVALUATION','ATTESTATION','AUTHORIZATION','EXECUTION','OBSERVATION'],'history':['IMMUTABLE_EVENTS','VALIDATION','CURRENT_PROJECTION'],'rule':'NO_STATE_TRANSITION_MAY_ESTABLISH_A_STRONGER_CLAIM_THAN_EVIDENCE_POLICY_AUTHORITY_AND_SCOPE_JUSTIFY'})
 dump(DEST/'CURRENT-STATUS.yaml',{'schema_version':VERSION,'objects':[],'audit_status':'BLOCKED_SPEC_INVALID','certificate_candidates':0,'certificates':0,'releases':0,'decisions':0,'executions':0,'verifications':0,'invented':False})
 dump(DEST/'SCHEMA-REGISTRY.yaml',{'schema_version':VERSION,'schemas':[{'name':x,'path':f'schema/{x}.schema.yaml','sha256':sha(SCHEMA/f'{x}.schema.yaml')} for x in SCHEMAS],'reused_predecessor_schema_registry':{'path':'../v14.3/SCHEMA-REGISTRY.yaml','sha256':sha(V143/'SCHEMA-REGISTRY.yaml')}})
 dump(DEST/'VALIDATION-REPORT.yaml',{'schema_version':VERSION,'overall_status':'STRUCTURAL_PASS_CURRENT_RELEASE_NOT_APPLICABLE','schemas':len(SCHEMAS),'reused_schemas':28,'vectors':len(vectors),'invariants':25,'current_objects':0})
 spec=['# v14.4 — Deterministic Authority, Decision Validity & Causal Projection Protocol']
 sections=['Objective','Resolved contradictions','Canonical state model','Certificate candidate model','Certificate lifecycle','Certificate validity','Release identity','Release gate','Release eligibility','Release authority','Release decision','Release execution','Post-release verification','Event/history model','Current projections','Temporal model','Identity and binding','Deterministic precedence','Validation procedure','Complete schemas','State-transition tables','Invariants','Test vectors','Traceability','Failure modes','Revised artifact tree','Open questions','Final principle']
 for i,x in enumerate(sections,1): spec += ['',f'## {i}. {x}',f'Machine-normative definition: `{x.upper().replace(" ","-")}.yaml` where present; otherwise the corresponding registered schema or model artifact is authoritative.']
 (DEST/'SPECIFICATION.md').write_text('\n'.join(spec)+'\n')
 after=[{'path':str(p.relative_to(OUT)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(OUT.rglob('*')) if p.is_file() and DEST not in p.parents]
 if before!=after: raise RuntimeError('predecessor mutation')
 dump(DEST/'PRIOR-INTEGRITY.yaml',{'schema_version':VERSION,'protected_artifact_count':len(before),'artifacts':before,'status':'PRESERVED'})
 print(f'generated {len(FILES)+len(SCHEMAS)+1} v14.4 artifacts; vectors={len(vectors)} invariants=25 current=NONE')
if __name__=='__main__':main()
