#!/usr/bin/env python3
"""Build Protocol-v14.3 release identity, authorization, execution, and verification artifacts."""
from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
HS = ROOT / "historical-source"
OUT = HS / "compliance"
V141 = OUT / "certification" / "v14.1"
DEST = OUT / "certification" / "v14.3"
SCHEMA = DEST / "schema"
REPORTS = DEST / "reports"
VERSION = "14.3"
GENERATED_AT = "2026-09-12T23:03:00Z"
CERT_CANDIDATE_STATES = ["CREATED", "ACTIVE", "CONSUMED", "CANCELLED", "EXPIRED", "RETAINED"]
CERT_LIFECYCLE = ["DRAFT", "ISSUED", "REVOKED", "SUPERSEDED", "EXPIRED", "CANCELLED"]
CERT_VALIDITY = ["VALID", "INVALID", "NOT_YET_VALID", "UNKNOWN"]
RELEASE_ELIGIBILITY = ["ELIGIBLE", "INELIGIBLE", "BLOCKED", "UNKNOWN"]
DECISIONS = ["APPROVED", "REJECTED", "BLOCKED", "DEFERRED"]
EXECUTION_STATES = ["NOT_STARTED", "STARTED", "SUCCEEDED", "FAILED", "CANCELLED", "ROLLED_BACK"]
POST_STATES = ["VERIFIED", "FAILED", "INCONCLUSIVE", "BLOCKED", "UNKNOWN"]
PREDICATE_RESULTS = ["TRUE", "FALSE", "BLOCKED", "UNKNOWN"]
SCHEMA_NAMES = ["candidate", "certificate-candidate", "certificate", "certificate-eligibility", "certificate-validity", "certificate-issuance-event", "certificate-revocation-event", "certificate-supersession-event", "release", "release-gate-predicate", "release-gate", "release-eligibility", "release-decision", "release-decision-event", "release-execution", "post-release-verification", "current-certificate", "current-release-eligibility", "current-release-decision", "current-release-execution", "current-post-release-verification", "authority", "predicate-evaluation", "temporal-interval", "certificate-release-binding", "certificate-candidate-event", "release-execution-event", "post-release-verification-event"]
MACHINE_FILES = ["VERSION.yaml", "SCOPE.yaml", "PROBLEM-STATEMENT.yaml", "SEMANTIC-CORRECTIONS.yaml", "CANONICAL-MODEL.yaml", "DOMAIN-SEPARATION.yaml", "CERTIFICATE-CANDIDATE-MODEL.yaml", "CERTIFICATE-CANDIDATE-TRANSITIONS.yaml", "CERTIFICATE-LIFECYCLE-MODEL.yaml", "CERTIFICATE-LIFECYCLE-TRANSITIONS.yaml", "CERTIFICATE-VALIDITY-FUNCTION.yaml", "DISCOVERY-CANDIDATE-SEPARATION.yaml", "RELEASE-IDENTITY-MODEL.yaml", "CERTIFICATE-RELEASE-BINDING.yaml", "RELEASE-GATE-DEFINITION.yaml", "RELEASE-GATE-PREDICATE-REGISTRY.yaml", "RELEASE-ELIGIBILITY-FUNCTION.yaml", "RELEASE-ELIGIBILITY-PRECEDENCE.yaml", "RELEASE-DECISION-FUNCTION.yaml", "RELEASE-AUTHORITY-MODEL.yaml", "RELEASE-EXECUTION-STATE-MACHINE.yaml", "RELEASE-EXECUTION-GUARDS.yaml", "POST-RELEASE-VERIFICATION-MODEL.yaml", "IMMUTABLE-EVENT-MODEL.yaml", "CURRENT-PROJECTION-MODEL.yaml", "TEMPORAL-MODEL.yaml", "DECISION-REUSE-FUNCTION.yaml", "IDENTITY-BINDING-MODEL.yaml", "VALIDATION-PROCEDURE.yaml", "FAILURE-MODES.yaml", "EPISTEMIC-REGISTER.yaml", "TRACEABILITY.yaml", "INVARIANTS.yaml", "REQUIRED-TEST-VECTORS.yaml", "CERTIFICATE-CANDIDATES.yaml", "CERTIFICATES.yaml", "RELEASES.yaml", "RELEASE-ELIGIBILITY-HISTORY.yaml", "RELEASE-DECISION-HISTORY.yaml", "RELEASE-EXECUTION-HISTORY.yaml", "POST-RELEASE-VERIFICATION-HISTORY.yaml", "CURRENT-STATES.yaml", "OPEN-QUESTIONS.yaml", "FINAL-PRINCIPLE.yaml", "ARTIFACT-TREE.yaml", "OBJECT-REGISTRY.yaml", "SCHEMA-REGISTRY.yaml", "PRIOR-INTEGRITY.yaml", "VALIDATION-REPORT.yaml"]
REPORT_FILES = ["SEMANTIC-GAP-REPORT.yaml", "IDENTITY-BINDING-REPORT.yaml", "EXECUTION-SEPARATION-REPORT.yaml", "CURRENT-HISTORICAL-STATUS.yaml"]


def load(path: Path) -> Any: return json.loads(path.read_text(encoding="utf-8"))
def dump(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
def canonical(value: Any) -> bytes: return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
def digest(value: Any) -> str: return hashlib.sha256(canonical(value)).hexdigest()
def sha_file(path: Path) -> str: return hashlib.sha256(path.read_bytes()).hexdigest()
def seal(value: dict[str, Any], field: str) -> dict[str, Any]: value[field] = digest({key: item for key, item in value.items() if key != field}); return value
def valid_time(value: Any) -> bool:
    if not isinstance(value, str): return False
    try: return datetime.fromisoformat(value.replace("Z", "+00:00")).tzinfo is not None
    except ValueError: return False


def interval_active(not_before: str, not_after: str | None, evaluated_at: str) -> bool:
    return evaluated_at >= not_before and (not_after is None or evaluated_at < not_after)


def release_eligibility(predicates: list[dict[str, Any]], registry: list[dict[str, Any]], malformed: bool = False) -> tuple[str, list[str], list[str]]:
    if malformed: return "INELIGIBLE", ["MALFORMED_PREDICATE_INPUT"], []
    by_id = {item["predicate_id"]: item for item in predicates}; mandatory = [item for item in registry if item["mandatory"]]
    missing = [item["predicate_id"] for item in mandatory if item["predicate_id"] not in by_id]
    if missing: return "BLOCKED", ["MISSING_MANDATORY_PREDICATE:" + item for item in missing], []
    if not mandatory: return "BLOCKED", ["NO_MANDATORY_PREDICATES"], []
    mandatory_results = [by_id[item["predicate_id"]] for item in mandatory]
    optional_failures = [item["predicate_id"] for item in predicates if not next((rule["mandatory"] for rule in registry if rule["predicate_id"] == item["predicate_id"]), False) and item["result"] != "TRUE"]
    if any(item["result"] == "FALSE" for item in mandatory_results): return "INELIGIBLE", [item["reason"] for item in mandatory_results if item["result"] == "FALSE"], optional_failures
    if any(item["result"] == "BLOCKED" for item in mandatory_results): return "BLOCKED", [item["reason"] for item in mandatory_results if item["result"] == "BLOCKED"], optional_failures
    if any(item["result"] == "UNKNOWN" for item in mandatory_results): return "UNKNOWN", [item["reason"] for item in mandatory_results if item["result"] == "UNKNOWN"], optional_failures
    return "ELIGIBLE", [], optional_failures


def release_decision(eligibility: str, authority_outcome: str, defer_requested: bool, defer_allowed: bool) -> tuple[str, str]:
    if eligibility == "INELIGIBLE": return "REJECTED", "PROVEN_GATE_FAILURE"
    if eligibility in {"BLOCKED", "UNKNOWN"}: return "BLOCKED", "AUTHORIZATION_CANNOT_PROCEED"
    if authority_outcome == "REJECT": return "REJECTED", "AUTHORIZED_REJECTION"
    if defer_requested: return ("DEFERRED", "AUTHORIZED_POSTPONEMENT") if defer_allowed else ("BLOCKED", "DEFER_NOT_PERMITTED")
    if authority_outcome != "APPROVE": return "BLOCKED", "AUTHORITY_UNAVAILABLE_OR_INVALID"
    return "APPROVED", "AUTHORIZATION_PREDICATES_SATISFIED"


def execution_start(decision_status: str, decision_active: bool, release_match: bool, artifact_match: bool, certificate_valid: bool = True, policy_reusable: bool = True) -> tuple[str, str]:
    if decision_status != "APPROVED": return "NOT_STARTED", "DECISION_NOT_APPROVED"
    if not decision_active: return "NOT_STARTED", "DECISION_EXPIRED"
    if not release_match: return "NOT_STARTED", "RELEASE_IDENTITY_MISMATCH"
    if not artifact_match: return "NOT_STARTED", "ARTIFACT_IDENTITY_MISMATCH"
    if not policy_reusable: return "NOT_STARTED", "DECISION_INPUT_CHANGED"
    if not certificate_valid: return "NOT_STARTED", "CERTIFICATE_NO_LONGER_VALID"
    return "STARTED", "EXECUTION_GUARDS_SATISFIED"


def project_events(events: list[dict[str, Any]], initial: str, transitions: set[tuple[str, str]]) -> tuple[str, str | None]:
    state = initial; previous = None
    for index, event in enumerate(events):
        if event.get("sequence") != index or event.get("previous_event_id") != previous or event.get("from_state") != state or (state, event.get("to_state")) not in transitions: return "HISTORY_INVALID", None
        if event.get("content_hash") != digest({key: value for key, value in event.items() if key != "content_hash"}): return "HISTORY_INVALID", None
        state = event["to_state"]; previous = event["event_id"]
    return "VALID", state


def binding_match(binding: dict[str, str], release: dict[str, Any]) -> tuple[bool, list[str]]:
    actual = {"release_id": release["release_id"], "artifact_id": release["artifact"]["artifact_id"], "artifact_hash": release["artifact"]["content_hash"], "implementation_id": release["implementation_id"], "specification_hash": release["specification"]["specification_hash"], "environment_id": release["environment"]["environment_id"]}
    reasons = [key.upper() + "_MISMATCH" for key, value in actual.items() if binding.get(key) != value]
    return not reasons, reasons


def base_schema(title: str, required: list[str], properties: dict[str, Any], rules: list[str] | None = None) -> dict[str, Any]:
    result: dict[str, Any] = {"$schema": "https://json-schema.org/draft/2020-12/schema", "title": title, "type": "object", "required": required, "properties": properties, "additionalProperties": False}
    if rules: result["x-v14.3-rules"] = rules
    return result


def build_schemas() -> None:
    ident = {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]*$"}; text = {"type": "string", "minLength": 1}; hx = {"type": "string", "pattern": "^[a-f0-9]{64}$"}; ts = {"type": "string", "format": "date-time"}; boolean = {"type": "boolean"}; integer = {"type": "integer", "minimum": 0}; nullable = lambda body: {"oneOf": [body, {"type": "null"}]}; strings = lambda minimum=0: {"type": "array", "minItems": minimum, "items": text, "uniqueItems": True}
    authority_ref = {"$ref": "authority.schema.yaml"}; pred_ref = {"$ref": "predicate-evaluation.schema.yaml"}; interval_ref = {"$ref": "temporal-interval.schema.yaml"}
    schemas: dict[str, Any] = {}
    candidate_target = {"type": "object", "required": ["value", "type"], "properties": {"value": text, "type": {"type": "string", "enum": ["URL", "DOCUMENT", "RESOURCE", "ENDPOINT", "OTHER"]}}, "additionalProperties": False}
    candidate_origin = {"type": "object", "required": ["type", "parent_candidate_id"], "properties": {"type": {"type": "string", "enum": ["SEED", "DISCOVERY", "EXPANSION", "USER", "RECOVERY"]}, "parent_candidate_id": nullable(ident)}, "additionalProperties": False}
    candidate_lifecycle = {"type": "object", "required": ["state"], "properties": {"state": {"type": "string", "enum": ["DISCOVERED", "QUEUED", "CLAIMED", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"]}}, "additionalProperties": False}
    schemas["candidate"] = base_schema("DiscoveryCandidateV143", ["candidate_id", "target", "origin", "priority", "hints", "lifecycle", "attempts", "created_at", "updated_at"], {"candidate_id": ident, "target": candidate_target, "origin": candidate_origin, "priority": {"type": "integer"}, "hints": {"type": "object"}, "lifecycle": candidate_lifecycle, "attempts": integer, "created_at": ts, "updated_at": ts}, ["certificate and release fields forbidden"])
    schemas["authority"] = base_schema("AuthorityV143", ["authority_id", "authority_class", "policy_id", "evidence_refs", "valid"], {"authority_id": ident, "authority_class": {"type": "string", "enum": ["AUTOMATED_POLICY", "HUMAN", "DELEGATED", "MULTI_PARTY"]}, "policy_id": ident, "evidence_refs": strings(1), "valid": boolean})
    schemas["temporal-interval"] = base_schema("TemporalIntervalV143", ["not_before", "not_after", "clock_source", "clock_uncertainty_ms"], {"not_before": ts, "not_after": nullable(ts), "clock_source": ident, "clock_uncertainty_ms": integer}, ["half-open interval [not_before, not_after)", "timestamps normalized to UTC"])
    schemas["predicate-evaluation"] = base_schema("PredicateEvaluationV143", ["predicate_id", "mandatory", "result", "reason", "evidence_refs"], {"predicate_id": ident, "mandatory": boolean, "result": {"type": "string", "enum": PREDICATE_RESULTS}, "reason": text, "evidence_refs": strings()})
    schemas["certificate-candidate"] = base_schema("CertificateCandidateV143", ["candidate_id", "subject", "intended_certificate_type", "specification_id", "specification_hash", "audit_snapshot_id", "audit_snapshot_hash", "aggregate_id", "aggregate_hash", "eligibility_id", "evidence_refs", "lifecycle_state", "retention_until", "provenance_refs", "created_at", "schema_version", "candidate_hash"], {"candidate_id": ident, "subject": text, "intended_certificate_type": text, "specification_id": ident, "specification_hash": hx, "audit_snapshot_id": ident, "audit_snapshot_hash": hx, "aggregate_id": ident, "aggregate_hash": hx, "eligibility_id": nullable(ident), "evidence_refs": strings(1), "lifecycle_state": {"type": "string", "enum": CERT_CANDIDATE_STATES}, "retention_until": nullable(ts), "provenance_refs": strings(1), "created_at": ts, "schema_version": {"const": VERSION}, "candidate_hash": hx}, ["candidate lifecycle is not certificate lifecycle"])
    schemas["certificate-release-binding"] = base_schema("CertificateReleaseBindingV143", ["release_id", "artifact_id", "artifact_hash", "implementation_id", "specification_hash", "audit_snapshot_hash", "certificate_snapshot_hash", "environment_id"], {"release_id": ident, "artifact_id": ident, "artifact_hash": hx, "implementation_id": ident, "specification_hash": hx, "audit_snapshot_hash": hx, "certificate_snapshot_hash": hx, "environment_id": ident})
    schemas["certificate"] = base_schema("CertificateV143", ["certificate_id", "candidate_id", "certificate_type", "lifecycle_state", "binding", "authority", "interval", "issued_at", "schema_version", "certificate_hash", "signature_hash"], {"certificate_id": ident, "candidate_id": ident, "certificate_type": text, "lifecycle_state": {"type": "string", "enum": CERT_LIFECYCLE}, "binding": {"$ref": "certificate-release-binding.schema.yaml"}, "authority": authority_ref, "interval": interval_ref, "issued_at": nullable(ts), "schema_version": {"const": VERSION}, "certificate_hash": hx, "signature_hash": nullable(hx)}, ["validity is not stored as lifecycle state"])
    schemas["certificate-eligibility"] = base_schema("CertificateEligibilityV143", ["eligibility_id", "candidate_id", "status", "predicates", "reasons", "evaluated_at", "snapshot_hash", "schema_version", "eligibility_hash"], {"eligibility_id": ident, "candidate_id": ident, "status": {"type": "string", "enum": ["ELIGIBLE", "INELIGIBLE", "BLOCKED", "UNKNOWN"]}, "predicates": {"type": "array", "items": pred_ref}, "reasons": strings(), "evaluated_at": ts, "snapshot_hash": hx, "schema_version": {"const": VERSION}, "eligibility_hash": hx})
    schemas["certificate-validity"] = base_schema("CertificateValidityV143", ["validity_id", "certificate_id", "status", "predicates", "reasons", "evaluated_at", "schema_version", "validity_hash"], {"validity_id": ident, "certificate_id": ident, "status": {"type": "string", "enum": CERT_VALIDITY}, "predicates": {"type": "array", "items": pred_ref}, "reasons": strings(), "evaluated_at": ts, "schema_version": {"const": VERSION}, "validity_hash": hx})
    envelope = {"event_id": ident, "entity_id": ident, "occurred_at": ts, "actor_or_authority": nullable(ident), "snapshot_hash": hx, "previous_event_id": nullable(ident), "evidence_refs": strings(), "schema_version": {"const": VERSION}, "content_hash": hx}
    def event_schema(title: str, event_types: list[str], extra_required: list[str] | None = None, extra: dict[str, Any] | None = None) -> dict[str, Any]:
        props = {**envelope, "event_type": {"type": "string", "enum": event_types}, **(extra or {})}; return base_schema(title, [*envelope, "event_type", *(extra_required or [])], props)
    schemas["certificate-issuance-event"] = event_schema("CertificateIssuanceEventV143", ["ISSUED"], ["candidate_id", "eligibility_id"], {"candidate_id": ident, "eligibility_id": ident})
    schemas["certificate-revocation-event"] = event_schema("CertificateRevocationEventV143", ["REVOKED"], ["reason", "authority"], {"reason": text, "authority": authority_ref})
    schemas["certificate-supersession-event"] = event_schema("CertificateSupersessionEventV143", ["SUPERSEDED"], ["replacement_certificate_id", "authority"], {"replacement_certificate_id": ident, "authority": authority_ref})
    schemas["certificate-candidate-event"] = event_schema("CertificateCandidateEventV143", ["CREATED", "ACTIVATED", "CONSUMED", "CANCELLED", "EXPIRED", "RETAINED"])
    artifact = {"type": "object", "required": ["artifact_id", "content_hash"], "properties": {"artifact_id": ident, "content_hash": hx}, "additionalProperties": False}; specification = {"type": "object", "required": ["specification_id", "specification_hash"], "properties": {"specification_id": ident, "specification_hash": hx}, "additionalProperties": False}; environment = {"type": "object", "required": ["environment_id", "environment_hash"], "properties": {"environment_id": ident, "environment_hash": hx}, "additionalProperties": False}; source = {"type": "object", "required": ["repository_id", "commit_hash"], "properties": {"repository_id": ident, "commit_hash": nullable(hx)}, "additionalProperties": False}
    schemas["release"] = base_schema("ReleaseV143", ["release_id", "implementation_id", "artifact", "version", "specification", "environment", "source", "build_hash", "configuration_hash", "created_at", "schema_version", "release_hash"], {"release_id": ident, "implementation_id": ident, "artifact": artifact, "version": {"type": "object", "required": ["value"], "properties": {"value": text}, "additionalProperties": False}, "specification": specification, "environment": environment, "source": source, "build_hash": hx, "configuration_hash": hx, "created_at": ts, "schema_version": {"const": VERSION}, "release_hash": hx}, ["version.value is a label, not identity"])
    schemas["release-gate-predicate"] = base_schema("ReleaseGatePredicateV143", ["predicate_id", "domain", "mandatory", "semantics", "evidence_requirements", "freshness_policy_id"], {"predicate_id": ident, "domain": {"type": "string", "enum": ["CERTIFICATE", "CONFORMANCE", "SECURITY", "COMPATIBILITY", "ENVIRONMENT", "AUTHORITY", "FRESHNESS", "RESOURCE", "REGRESSION", "WAIVER"]}, "mandatory": boolean, "semantics": text, "evidence_requirements": strings(), "freshness_policy_id": nullable(ident)})
    schemas["release-gate"] = base_schema("ReleaseGateV143", ["gate_id", "policy_id", "release_scope", "predicate_registry", "certificate_requirements", "conditional_release_policy", "waiver_policy_id", "unknown_policy", "blocker_policy", "authority_policy_id", "schema_version", "gate_hash"], {"gate_id": ident, "policy_id": ident, "release_scope": strings(1), "predicate_registry": {"type": "array", "minItems": 1, "items": {"$ref": "release-gate-predicate.schema.yaml"}}, "certificate_requirements": strings(1), "conditional_release_policy": text, "waiver_policy_id": ident, "unknown_policy": text, "blocker_policy": text, "authority_policy_id": ident, "schema_version": {"const": VERSION}, "gate_hash": hx}, ["gate contains policy only and no evaluation result"])
    schemas["release-eligibility"] = base_schema("ReleaseEligibilityV143", ["eligibility_id", "release_id", "gate_id", "status", "predicates", "reasons", "warnings", "evidence_snapshot_hash", "evaluated_at", "schema_version", "eligibility_hash"], {"eligibility_id": ident, "release_id": ident, "gate_id": ident, "status": {"type": "string", "enum": RELEASE_ELIGIBILITY}, "predicates": {"type": "array", "items": pred_ref}, "reasons": strings(), "warnings": strings(), "evidence_snapshot_hash": hx, "evaluated_at": ts, "schema_version": {"const": VERSION}, "eligibility_hash": hx})
    schemas["release-decision"] = base_schema("ReleaseDecisionV143", ["decision_id", "release_id", "gate_id", "eligibility_id", "authority", "policy_id", "evidence_snapshot_hash", "decision_predicates", "status", "reasons", "interval", "decided_at", "predecessor_decision_id", "decision_relevant_hashes", "schema_version", "decision_hash"], {"decision_id": ident, "release_id": ident, "gate_id": ident, "eligibility_id": ident, "authority": authority_ref, "policy_id": ident, "evidence_snapshot_hash": hx, "decision_predicates": {"type": "array", "items": pred_ref}, "status": {"type": "string", "enum": DECISIONS}, "reasons": strings(1), "interval": interval_ref, "decided_at": ts, "predecessor_decision_id": nullable(ident), "decision_relevant_hashes": {"type": "object"}, "schema_version": {"const": VERSION}, "decision_hash": hx})
    schemas["release-decision-event"] = event_schema("ReleaseDecisionEventV143", ["APPROVED", "REJECTED", "BLOCKED", "DEFERRED", "SUPERSEDED"], ["decision_id"], {"decision_id": ident})
    schemas["release-execution"] = base_schema("ReleaseExecutionV143", ["execution_id", "release_id", "decision_id", "release_hash", "artifact_hash", "status", "attempt", "started_at", "completed_at", "result_hash", "schema_version", "execution_hash"], {"execution_id": ident, "release_id": ident, "decision_id": ident, "release_hash": hx, "artifact_hash": hx, "status": {"type": "string", "enum": EXECUTION_STATES}, "attempt": integer, "started_at": nullable(ts), "completed_at": nullable(ts), "result_hash": nullable(hx), "schema_version": {"const": VERSION}, "execution_hash": hx})
    schemas["release-execution-event"] = event_schema("ReleaseExecutionEventV143", ["STARTED", "SUCCEEDED", "FAILED", "CANCELLED", "ROLLED_BACK", "RETRY_STARTED"], ["execution_id", "from_state", "to_state", "sequence"], {"execution_id": ident, "from_state": {"type": "string", "enum": EXECUTION_STATES}, "to_state": {"type": "string", "enum": EXECUTION_STATES}, "sequence": integer})
    schemas["post-release-verification"] = base_schema("PostReleaseVerificationV143", ["verification_id", "release_id", "execution_id", "decision_id", "status", "predicates", "evidence_refs", "evaluated_at", "snapshot_hash", "schema_version", "verification_hash"], {"verification_id": ident, "release_id": ident, "execution_id": ident, "decision_id": ident, "status": {"type": "string", "enum": POST_STATES}, "predicates": {"type": "array", "items": pred_ref}, "evidence_refs": strings(), "evaluated_at": ts, "snapshot_hash": hx, "schema_version": {"const": VERSION}, "verification_hash": hx})
    schemas["post-release-verification-event"] = event_schema("PostReleaseVerificationEventV143", ["VERIFIED", "FAILED", "INCONCLUSIVE", "BLOCKED", "UNKNOWN"], ["verification_id"], {"verification_id": ident})
    current_common = {"projection_id": ident, "entity_id": nullable(ident), "last_event_id": nullable(ident), "projected_at": ts, "history_hash": nullable(hx), "schema_version": {"const": VERSION}, "projection_hash": hx}
    schemas["current-certificate"] = base_schema("CurrentCertificateV143", [*current_common, "lifecycle_state", "validity_status"], {**current_common, "lifecycle_state": nullable({"type": "string", "enum": CERT_LIFECYCLE}), "validity_status": {"type": "string", "enum": CERT_VALIDITY}})
    schemas["current-release-eligibility"] = base_schema("CurrentReleaseEligibilityV143", [*current_common, "status"], {**current_common, "status": nullable({"type": "string", "enum": RELEASE_ELIGIBILITY})})
    schemas["current-release-decision"] = base_schema("CurrentReleaseDecisionV143", [*current_common, "status", "decision_id"], {**current_common, "status": nullable({"type": "string", "enum": DECISIONS}), "decision_id": nullable(ident)})
    schemas["current-release-execution"] = base_schema("CurrentReleaseExecutionV143", [*current_common, "status", "execution_id"], {**current_common, "status": nullable({"type": "string", "enum": EXECUTION_STATES}), "execution_id": nullable(ident)})
    schemas["current-post-release-verification"] = base_schema("CurrentPostReleaseVerificationV143", [*current_common, "status", "verification_id"], {**current_common, "status": nullable({"type": "string", "enum": POST_STATES}), "verification_id": nullable(ident)})
    for name, body in schemas.items(): body["$id"] = f"https://generic-discovery-engine.invalid/compliance/v14.3/{name}.schema.yaml"; dump(SCHEMA / f"{name}.schema.yaml", body)


def protected_files() -> list[Path]: return sorted((path for path in OUT.rglob("*") if path.is_file() and DEST not in path.parents), key=lambda path: str(path.relative_to(OUT)))


def make_release(identifier: str = "TEST-RELEASE") -> dict[str, Any]:
    return seal({"release_id": identifier, "implementation_id": "TEST-IMPLEMENTATION", "artifact": {"artifact_id": "TEST-ARTIFACT", "content_hash": "a" * 64}, "version": {"value": "1.0.0-test"}, "specification": {"specification_id": "TEST-SPEC", "specification_hash": "b" * 64}, "environment": {"environment_id": "TEST-ENV", "environment_hash": "c" * 64}, "source": {"repository_id": "TEST-REPOSITORY", "commit_hash": "d" * 64}, "build_hash": "e" * 64, "configuration_hash": "f" * 64, "created_at": GENERATED_AT, "schema_version": VERSION}, "release_hash")


def make_binding(release: dict[str, Any]) -> dict[str, str]:
    return {"release_id": release["release_id"], "artifact_id": release["artifact"]["artifact_id"], "artifact_hash": release["artifact"]["content_hash"], "implementation_id": release["implementation_id"], "specification_hash": release["specification"]["specification_hash"], "audit_snapshot_hash": "1" * 64, "certificate_snapshot_hash": "2" * 64, "environment_id": release["environment"]["environment_id"]}


def main() -> None:
    if not (V141 / "VALIDATION.yaml").is_file(): raise RuntimeError("validated Protocol-v14.1 package is required")
    if (OUT / "certification" / "v14.4").exists(): raise RuntimeError("refusing to erase predecessor artifacts after append-only v14.4 extension")
    if DEST.exists():
        for filename in ["CERTIFICATE-CANDIDATES.yaml", "CERTIFICATES.yaml", "RELEASES.yaml", "RELEASE-DECISION-HISTORY.yaml", "RELEASE-EXECUTION-HISTORY.yaml"]:
            path = DEST / filename
            if path.is_file() and load(path).get("objects"): raise RuntimeError(f"refusing to erase appended v14.3 records in {filename}")
    before = [{"path": str(path.relative_to(OUT)), "sha256": sha_file(path), "bytes": path.stat().st_size} for path in protected_files()]
    if DEST.exists(): shutil.rmtree(DEST)
    DEST.mkdir(parents=True); SCHEMA.mkdir(); REPORTS.mkdir(); build_schemas()

    origin = {"baseline": "USER_SUPPLIED_V14_2_NORMATIVE_TEXT", "epistemic_status": "SUPPORTED", "normative_origin": "ENGINEERING_REQUIREMENT_V14_3"}
    dump(DEST / "VERSION.yaml", {"schema_version": VERSION, "revision": "v14.3", "baseline": "v14.2", **origin})
    dump(DEST / "SCOPE.yaml", {"schema_version": VERSION, "in_scope": ["CERTIFICATE_CANDIDATE", "CERTIFICATE_LIFECYCLE_VALIDITY", "RELEASE_IDENTITY_BINDING", "RELEASE_GATE", "RELEASE_ELIGIBILITY", "RELEASE_DECISION", "RELEASE_EXECUTION", "POST_RELEASE_VERIFICATION", "IMMUTABLE_EVENTS", "CURRENT_PROJECTIONS", "TEMPORAL_REPLAY"], "out_of_scope": ["HISTORICAL_SOURCE_REWRITE", "DISCOVERY_CANDIDATE_REDESIGN"], **origin})
    dump(DEST / "PROBLEM-STATEMENT.yaml", {"schema_version": VERSION, "gaps": ["CERTIFICATE_CANDIDATE_WAS_IMPLICIT", "RELEASE_IDENTITY_WAS_UNDERSPECIFIED", "GATE_POLICY_AND_EVALUATION_COULD_CONFLATE", "AUTHORIZATION_EXECUTION_OUTCOME_WERE_NOT_COMPLETE", "TEMPORAL_REUSE_AND_REPLAY_NEEDED_TOTAL_RULES"], **origin})
    corrections = ["CERTIFICATE_CANDIDATE_DISTINCT_FROM_DISCOVERY_CANDIDATE_AND_CERTIFICATE", "CERTIFICATE_VALIDITY_HAS_NO_LIFECYCLE_DUPLICATE_STATUSES", "RELEASE_GATE_IS_POLICY_NOT_RESULT", "RELEASE_ELIGIBILITY_DISTINCT_FROM_DECISION", "DECISION_DISTINCT_FROM_EXECUTION", "EXECUTION_DISTINCT_FROM_POST_RELEASE_RESULT", "CURRENT_OBJECTS_ARE_HISTORY_PROJECTIONS"]
    dump(DEST / "SEMANTIC-CORRECTIONS.yaml", {"schema_version": VERSION, "corrections": corrections, "earlier_artifacts_mutated": False, **origin})
    dump(DEST / "CANONICAL-MODEL.yaml", {"schema_version": VERSION, "historical_to_operational": ["HISTORY", "EVIDENCE", "HISTORICAL_PROPERTY", "OBLIGATION", "REQUIREMENT", "CONFORMANCE", "CERTIFICATION", "AUTHORIZATION", "EXECUTION", "OBSERVATION"], "release_pipeline": ["AUDIT_SNAPSHOT", "AGGREGATE_CONFORMANCE", "CERTIFICATE_ELIGIBILITY", "CERTIFICATE_ISSUANCE", "CERTIFICATE_VALIDITY", "RELEASE_GATE", "RELEASE_ELIGIBILITY", "RELEASE_DECISION", "RELEASE_EXECUTION", "POST_RELEASE_VERIFICATION"], **origin})
    domains = ["DISCOVERY_CANDIDATE_STATE", "CERTIFICATE_CANDIDATE_STATE", "CONFORMANCE_STATE", "CERTIFICATE_LIFECYCLE", "CERTIFICATE_VALIDITY", "CERTIFICATE_ELIGIBILITY", "RELEASE_ELIGIBILITY", "RELEASE_DECISION", "RELEASE_EXECUTION", "POST_RELEASE_VERIFICATION"]
    dump(DEST / "DOMAIN-SEPARATION.yaml", {"schema_version": VERSION, "independent_domains": domains, "cross_domain_implicit_implication": "FORBIDDEN", "process_state_is_truth_state": False, **origin})
    dump(DEST / "CERTIFICATE-CANDIDATE-MODEL.yaml", {"schema_version": VERSION, "states": CERT_CANDIDATE_STATES, "certificate_candidate_is_certificate": False, "draft_equivalence": "CONTRADICTED", "eligibility_is_lifecycle": False, "retention_requires_policy": True, **origin})
    candidate_transitions = [("CREATED", "ACTIVE"), ("CREATED", "CANCELLED"), ("ACTIVE", "CONSUMED"), ("ACTIVE", "CANCELLED"), ("ACTIVE", "EXPIRED"), ("CONSUMED", "RETAINED"), ("EXPIRED", "RETAINED")]
    dump(DEST / "CERTIFICATE-CANDIDATE-TRANSITIONS.yaml", {"schema_version": VERSION, "allowed": [{"from": source, "to": target, "guard": "DOMAIN_SPECIFIC_GUARD_REQUIRED"} for source, target in candidate_transitions], "terminal": ["CANCELLED", "RETAINED"], "eligibility_transition_forbidden": True})
    dump(DEST / "CERTIFICATE-LIFECYCLE-MODEL.yaml", {"schema_version": VERSION, "states": CERT_LIFECYCLE, "validity_statuses": CERT_VALIDITY, "validity_is_derived": True, "invalidity_fabricates_revocation": False, **origin})
    certificate_transitions = [("DRAFT", "ISSUED", "VALID_ELIGIBILITY_AUTHORITY_PAYLOAD_BINDING"), ("DRAFT", "CANCELLED", "AUTHORIZED_CANCELLATION"), ("ISSUED", "REVOKED", "AUTHORIZED_REVOCATION_EVENT"), ("ISSUED", "SUPERSEDED", "AUTHORIZED_REPLACEMENT_WITH_NEW_ID"), ("ISSUED", "EXPIRED", "VALIDITY_INTERVAL_END_REACHED"), ("ISSUED", "CANCELLED", "AUTHORIZED_PRE_ACTIVATION_CANCELLATION")]
    dump(DEST / "CERTIFICATE-LIFECYCLE-TRANSITIONS.yaml", {"schema_version": VERSION, "allowed": [{"from": a, "to": b, "guard": c} for a, b, c in certificate_transitions], "terminal": ["REVOKED", "SUPERSEDED", "EXPIRED", "CANCELLED"], "terminal_outgoing": []})
    dump(DEST / "CERTIFICATE-VALIDITY-FUNCTION.yaml", {"schema_version": VERSION, "outcomes": CERT_VALIDITY, "ordered_predicates": ["SCHEMA", "HASH", "SIGNATURE", "AUTHORITY", "BINDING", "SCOPE", "NOT_BEFORE", "NOT_AFTER", "LIFECYCLE_TERMINAL_STATE", "EVIDENCE_FRESHNESS", "POLICY_VALIDITY"], "terminal_lifecycle_to_validity": {"REVOKED": "INVALID", "SUPERSEDED": "INVALID", "EXPIRED": "INVALID", "CANCELLED": "INVALID"}, "DRAFT": "UNKNOWN", "invalid_does_not_imply_revoked": True, "evaluated_at_is_explicit": True})
    dump(DEST / "DISCOVERY-CANDIDATE-SEPARATION.yaml", {"schema_version": VERSION, "discovery_pipeline": ["CANDIDATE", "ACQUISITION", "OBSERVATION", "RECOGNITION", "DISCOVERY", "CANDIDATE_EXPANSION"], "discovery_candidate_schema": "schema/candidate.schema.yaml", "certificate_or_release_fields_added": False})

    mandatory_bindings = ["RELEASE_ID", "ARTIFACT_ID", "ARTIFACT_HASH", "IMPLEMENTATION_ID", "SPECIFICATION_HASH", "AUDIT_SNAPSHOT_HASH", "CERTIFICATE_SNAPSHOT_HASH", "ENVIRONMENT_ID"]
    dump(DEST / "RELEASE-IDENTITY-MODEL.yaml", {"schema_version": VERSION, "identity_components": ["RELEASE_ID", "IMPLEMENTATION_ID", "ARTIFACT_ID", "ARTIFACT_HASH", "SPECIFICATION_ID", "SPECIFICATION_HASH", "ENVIRONMENT_ID", "ENVIRONMENT_HASH", "SOURCE_REPOSITORY_ID", "SOURCE_COMMIT_HASH", "BUILD_HASH", "CONFIGURATION_HASH"], "version_label_is_identity": False, "artifact_mutation_creates_new_release": True, "implementation_mutation_creates_new_release": True, "specification_mutation_requires_new_release_and_audit_scope": True})
    dump(DEST / "CERTIFICATE-RELEASE-BINDING.yaml", {"schema_version": VERSION, "mandatory": mandatory_bindings, "optional": ["SOURCE_COMMIT_HASH", "BUILD_HASH", "CONFIGURATION_HASH"], "mismatch_result": "RELEASE_INELIGIBLE", "silent_cross_release_authorization": False, "replacement_requires_new_certificate_or_explicit_compatibility_certificate": True})
    dump(DEST / "IDENTITY-BINDING-MODEL.yaml", {"schema_version": VERSION, "release_identity_ne_version": True, "certificate_binding_fields": mandatory_bindings, "decision_binding_fields": ["RELEASE_HASH", "ARTIFACT_HASH", "GATE_HASH", "POLICY_HASH", "CERTIFICATE_HASH", "AUDIT_SNAPSHOT_HASH", "ENVIRONMENT_HASH", "EVIDENCE_SNAPSHOT_HASH"], "execution_binding_fields": ["RELEASE_HASH", "ARTIFACT_HASH", "DECISION_HASH"]})

    predicate_registry = [{"predicate_id": identifier, "domain": domain, "mandatory": mandatory, "semantics": semantics, "evidence_requirements": [identifier + "_EVIDENCE"], "freshness_policy_id": "FRESHNESS-POLICY-V143-001" if domain in {"CERTIFICATE", "SECURITY", "REGRESSION"} else None} for identifier, domain, mandatory, semantics in [("CERTIFICATE_VALID", "CERTIFICATE", True, "Required certificate derives VALID and binds exact release"), ("AGGREGATE_ALLOWED", "CONFORMANCE", True, "Aggregate satisfies release policy without mutation"), ("SECURITY_GATE_PASS", "SECURITY", True, "Required security gate establishes pass"), ("COMPATIBILITY_PASS", "COMPATIBILITY", True, "Compatibility is established for exact environment"), ("ENVIRONMENT_MATCH", "ENVIRONMENT", True, "Release environment matches evaluated environment"), ("AUTHORITY_AVAILABLE", "AUTHORITY", True, "Required authorization authority can act"), ("EVIDENCE_FRESH", "FRESHNESS", True, "Mandatory evidence satisfies freshness policy"), ("RESOURCE_AVAILABLE", "RESOURCE", False, "Operational resources are available"), ("REGRESSION_PASS", "REGRESSION", True, "Required regression suite passes"), ("WAIVER_VALID", "WAIVER", True, "Any relied-upon waiver is valid, scoped, effective, and authorized")]]
    gate = seal({"gate_id": "RELEASE-GATE-V143-STRICT-001", "policy_id": "RELEASE-POLICY-V143-STRICT-001", "release_scope": ["EXACT_RELEASE_ID", "EXACT_ARTIFACT", "EXACT_ENVIRONMENT"], "predicate_registry": predicate_registry, "certificate_requirements": ["EXACT_BINDING", "CURRENT_VALIDITY_VALID"], "conditional_release_policy": "CONDITIONAL_RELEASE_REQUIRES_EXPLICIT_POLICY_VALID_WAIVERS_AND_RISK_AUTHORITY", "waiver_policy_id": "WAIVER-POLICY-V143-001", "unknown_policy": "MANDATORY_UNKNOWN_PRODUCES_UNKNOWN_ELIGIBILITY", "blocker_policy": "MANDATORY_BLOCKER_PRODUCES_BLOCKED_ELIGIBILITY", "authority_policy_id": "RELEASE-AUTHORITY-POLICY-V143-001", "schema_version": VERSION}, "gate_hash")
    dump(DEST / "RELEASE-GATE-DEFINITION.yaml", {"schema_version": VERSION, "objects": [gate], "contains_evaluation_results": False})
    dump(DEST / "RELEASE-GATE-PREDICATE-REGISTRY.yaml", {"schema_version": VERSION, "gate_id": gate["gate_id"], "predicates": predicate_registry, "domains_covered": sorted({item["domain"] for item in predicate_registry})})
    dump(DEST / "RELEASE-ELIGIBILITY-PRECEDENCE.yaml", {"schema_version": VERSION, "mandatory_precedence": ["FALSE", "BLOCKED", "UNKNOWN", "TRUE"], "no_mandatory_predicates": "BLOCKED", "optional_failure_effect": "WARNING_ONLY", "malformed_predicate": "INELIGIBLE", "missing_mandatory_predicate": "BLOCKED"})
    dump(DEST / "RELEASE-ELIGIBILITY-FUNCTION.yaml", {"schema_version": VERSION, "outcomes": RELEASE_ELIGIBILITY, "inputs": ["VALID_GATE", "EXACT_RELEASE", "PREDICATE_EVALUATIONS", "EXPLICIT_TIME"], "algorithm": ["MALFORMED_TO_INELIGIBLE", "MANDATORY_FALSE_TO_INELIGIBLE", "MANDATORY_BLOCKED_TO_BLOCKED", "MANDATORY_UNKNOWN_TO_UNKNOWN", "ALL_MANDATORY_TRUE_TO_ELIGIBLE"], "vacuous_truth_allowed": False, "deterministic": True})
    dump(DEST / "RELEASE-DECISION-FUNCTION.yaml", {"schema_version": VERSION, "outcomes": DECISIONS, "semantics": {"REJECTED": "PROVEN_POLICY_FAILURE_OR_AUTHORIZED_REJECTION", "BLOCKED": "REQUIRED_EVALUATION_OR_AUTHORIZATION_CANNOT_PROCEED", "DEFERRED": "AUTHORIZED_POLICY_PERMITTED_POSTPONEMENT", "APPROVED": "ALL_AUTHORIZATION_PREDICATES_SATISFIED"}, "eligible_implies_approved": False, "approved_implies_executed": False, "unknown_maps_to_deferred": False})
    dump(DEST / "RELEASE-AUTHORITY-MODEL.yaml", {"schema_version": VERSION, "classes": ["AUTOMATED_POLICY", "HUMAN", "DELEGATED", "MULTI_PARTY"], "automated_authorization": "POLICY_DEFINED_NOT_ASSUMED", "default_strict_policy": "SEPARATE_VALID_AUTHORITY_ACTION_REQUIRED", "delegation_requires_scope_evidence_interval": True, "multi_party_requires_threshold_policy": True})

    execution_transitions = [("NOT_STARTED", "STARTED"), ("STARTED", "SUCCEEDED"), ("STARTED", "FAILED"), ("STARTED", "CANCELLED"), ("FAILED", "STARTED"), ("SUCCEEDED", "ROLLED_BACK"), ("FAILED", "ROLLED_BACK")]
    dump(DEST / "RELEASE-EXECUTION-STATE-MACHINE.yaml", {"schema_version": VERSION, "states": EXECUTION_STATES, "allowed": [{"from": a, "to": b} for a, b in execution_transitions], "retry": "FAILED_TO_STARTED_REQUIRES_EXPLICIT_NEW_ATTEMPT_AND_EFFECTIVE_APPROVAL", "rollback": "NEW_EVENT_PRESERVES_EXECUTION_AND_DECISION_HISTORY", "authorization_history_mutated": False})
    dump(DEST / "RELEASE-EXECUTION-GUARDS.yaml", {"schema_version": VERSION, "start_all_of": ["DECISION_APPROVED", "DECISION_INTERVAL_ACTIVE", "RELEASE_IDENTITY_MATCH", "ARTIFACT_IDENTITY_MATCH", "DECISION_REUSABLE", "REQUIRED_CERTIFICATE_STILL_VALID"], "decision_expiration": "NOT_STARTED_DECISION_EXPIRED", "certificate_revocation": "NOT_STARTED_CERTIFICATE_NO_LONGER_VALID", "artifact_mutation": "NOT_STARTED_ARTIFACT_IDENTITY_MISMATCH", "partial_execution": "FAILED_WITH_RESULT_EVIDENCE", "cancellation": "APPEND_CANCELLED_EVENT", "failure": "APPEND_FAILED_EVENT", "retry": "NEW_ATTEMPT", "rollback": "APPEND_ROLLED_BACK_EVENT"})
    dump(DEST / "POST-RELEASE-VERIFICATION-MODEL.yaml", {"schema_version": VERSION, "outcomes": POST_STATES, "question": "DID_EXECUTED_RELEASE_PRODUCE_EXPECTED_POST_RELEASE_STATE", "authorization_question": False, "decision_mutated_by_result": False, "failure_effect": "APPEND_NEW_FINDING_RISK_OR_REMEDIATION_INPUT", "execution_success_implies_verified": False})
    dump(DEST / "IMMUTABLE-EVENT-MODEL.yaml", {"schema_version": VERSION, "common_envelope": ["EVENT_ID", "ENTITY_ID", "EVENT_TYPE", "OCCURRED_AT", "ACTOR_OR_AUTHORITY", "SNAPSHOT_HASH", "PREVIOUS_EVENT_ID", "CONTENT_HASH"], "domain_specific_schemas": ["CERTIFICATE_ISSUANCE", "CERTIFICATE_REVOCATION", "CERTIFICATE_SUPERSESSION", "CERTIFICATE_CANDIDATE", "RELEASE_DECISION", "RELEASE_EXECUTION", "POST_RELEASE_VERIFICATION"], "universal_lifecycle_enum": False, "append_only": True})
    dump(DEST / "CURRENT-PROJECTION-MODEL.yaml", {"schema_version": VERSION, "current_objects": ["CURRENT_CERTIFICATE", "CURRENT_RELEASE_ELIGIBILITY", "CURRENT_RELEASE_DECISION", "CURRENT_RELEASE_EXECUTION", "CURRENT_POST_RELEASE_VERIFICATION"], "source": "VALID_IMMUTABLE_DOMAIN_EVENT_HISTORY", "mutable_historical_replacement": False, "invalid_event_skip": False, "reconstructible": True})
    dump(DEST / "TEMPORAL-MODEL.yaml", {"schema_version": VERSION, "interval": "[not_before, not_after)", "not_before_equality": "ACTIVE", "not_after_equality": "INACTIVE", "normalization": "UTC_Z", "clock_source": "EXPLICIT_POLICY_APPROVED_INPUT", "clock_uncertainty": "EXPLICIT_MILLISECONDS_CONSERVATIVE_BOUNDARY_RESULT_UNKNOWN", "future_timestamp": "TEMPORAL_DEFECT", "clock_rollback": "TEMPORAL_DEFECT", "history_order": "NONDECREASING_OCCURRED_AT_AND_EXACT_PREDECESSOR", "historical_replay": "USE_AS_OF_SNAPSHOTS_AND_POLICIES_EFFECTIVE_AT_AS_OF_TIME", "current_policy_for_historical_replay": "FORBIDDEN"})
    reuse_fields = ["RELEASE_ARTIFACT", "IMPLEMENTATION", "SPECIFICATION", "POLICY", "GATE", "CERTIFICATE", "AUDIT_SNAPSHOT", "ENVIRONMENT", "MANDATORY_EVIDENCE", "AUTHORITY", "WAIVER", "SECURITY_STATE", "COMPATIBILITY_STATE"]
    dump(DEST / "DECISION-REUSE-FUNCTION.yaml", {"schema_version": VERSION, "decision_relevant_inputs": reuse_fields, "reusable_iff": ["ALL_RELEVANT_INPUT_HASHES_IDENTICAL", "DECISION_INTERVAL_ACTIVE", "POLICY_PERMITS_REUSE", "NO_INVALIDATING_EVENT"], "any_unknown_equivalence": "NOT_REUSABLE", "historical_decision_mutated": False})
    validation_stages = ["LOAD", "SCHEMA_VALIDATION", "REFERENCE_RESOLUTION", "HASH_VALIDATION", "TEMPORAL_VALIDATION", "SCOPE_VALIDATION", "POLICY_VALIDATION", "STATE_TRANSITION_VALIDATION", "PREDICATE_EVALUATION", "AGGREGATION", "CURRENT_PROJECTION"]
    dump(DEST / "VALIDATION-PROCEDURE.yaml", {"schema_version": VERSION, "stages": [{"number": index, "stage": stage} for index, stage in enumerate(validation_stages, 1)], "stop_dependent_claims_on_failure": True, "failure_attribution_required": True})
    failure_modes = ["SCHEMA_DEFECT", "REFERENCE_DEFECT", "HASH_DEFECT", "TEMPORAL_DEFECT", "POLICY_DEFECT", "STATE_TRANSITION_DEFECT", "EVIDENCE_DEFECT", "AUTHORITY_DEFECT", "IMPLEMENTATION_DEFECT", "ENVIRONMENT_DEFECT"]
    dump(DEST / "FAILURE-MODES.yaml", {"schema_version": VERSION, "failure_modes": failure_modes, "all_failures_are_implementation_failure": False})
    epistemic = [{"claim": item, "status": status, "basis": basis} for item, status, basis in [("V14_2_IS_CURRENT_PROMPT_BASELINE", "SUPPORTED", "USER_SUPPLIED_NORMATIVE_TEXT"), ("CURRENT_V13_3_AUDIT_IS_BLOCKED", "PROVED", "V13_3_CURRENT_AUDIT_STATUS"), ("CURRENT_RELEASE_EXISTS", "CONTRADICTED", "NO_RELEASE_OBJECT_IN_PREDECESSOR_CURRENT_COLLECTIONS"), ("AUTOMATED_AUTHORITY_MAY_APPROVE", "INFERRED", "ONLY_WHEN_EXPLICIT_POLICY_PERMITS"), ("PRODUCTION_AUTHORITY_CONFIGURATION", "UNKNOWN", "NO_AUTHORITY_INSTANCE_SUPPLIED"), ("POST_RELEASE_FAILURE_SHOULD_OPEN_FINDING_OR_RISK", "CONJECTURED", "DOMAIN_ROUTING_REQUIRES_FUTURE_POLICY")]]
    dump(DEST / "EPISTEMIC-REGISTER.yaml", {"schema_version": VERSION, "allowed_labels": ["PROVED", "SUPPORTED", "INFERRED", "CONJECTURED", "CONTRADICTED", "UNKNOWN"], "claims": epistemic, "future_rules_label": "ENGINEERING_REQUIREMENT_V14_3"})
    dump(DEST / "TRACEABILITY.yaml", {"schema_version": VERSION, "baseline_sections": [{"section": index, "deliverables": [name]} for index, name in enumerate(["PROBLEM-STATEMENT.yaml", "DOMAIN-SEPARATION.yaml", "CERTIFICATE-LIFECYCLE-MODEL.yaml", "CERTIFICATE-CANDIDATE-MODEL.yaml", "DISCOVERY-CANDIDATE-SEPARATION.yaml", "RELEASE-IDENTITY-MODEL.yaml", "CERTIFICATE-RELEASE-BINDING.yaml", "RELEASE-GATE-DEFINITION.yaml", "RELEASE-ELIGIBILITY-FUNCTION.yaml", "RELEASE-DECISION-FUNCTION.yaml", "RELEASE-AUTHORITY-MODEL.yaml", "RELEASE-EXECUTION-GUARDS.yaml", "POST-RELEASE-VERIFICATION-MODEL.yaml", "IMMUTABLE-EVENT-MODEL.yaml", "CURRENT-PROJECTION-MODEL.yaml", "TEMPORAL-MODEL.yaml", "DECISION-REUSE-FUNCTION.yaml", "SCHEMA-REGISTRY.yaml", "VALIDATION-PROCEDURE.yaml", "INVARIANTS.yaml", "REQUIRED-TEST-VECTORS.yaml"], 1)], "direction": "BASELINE_REQUIREMENT_TO_V14_3_ARTIFACT", "reverse_proof_forbidden": True})

    release = make_release(); binding = make_binding(release)
    base_registry = [{"predicate_id": "P1", "mandatory": True}, {"predicate_id": "P2", "mandatory": True}, {"predicate_id": "O1", "mandatory": False}]
    def preds(p1: str = "TRUE", p2: str = "TRUE", optional: str = "TRUE") -> list[dict[str, Any]]:
        return [{"predicate_id": "P1", "mandatory": True, "result": p1, "reason": "P1_" + p1, "evidence_refs": ["E1"]}, {"predicate_id": "P2", "mandatory": True, "result": p2, "reason": "P2_" + p2, "evidence_refs": ["E2"]}, {"predicate_id": "O1", "mandatory": False, "result": optional, "reason": "O1_" + optional, "evidence_refs": ["E3"]}]
    vectors: list[dict[str, Any]] = []
    def add(number: int, name: str, operation: str, input_value: dict[str, Any], expected_predicates: list[str], expected_state: str, expected_event: str | None, expected_current: str, reason: str) -> None:
        vectors.append({"number": number, "vector_id": f"V{number:02d}-{name}", "operation": operation, "input": input_value, "expected_predicates": expected_predicates, "expected_state": expected_state, "expected_event": expected_event, "expected_current_projection": expected_current, "expected_reason": reason})
    add(1, "VALID-CERTIFICATE", "CERT_VALIDITY", {"lifecycle": "ISSUED", "schema": True, "hash": True, "signature": True, "authority": True, "binding": True, "scope": True, "interval": "ACTIVE", "evidence": True, "policy": True}, ["ALL_TRUE"], "VALID", None, "VALID", "ALL_VALIDITY_PREDICATES_TRUE")
    add(2, "CORRUPTED-SIGNATURE", "CERT_VALIDITY", {"lifecycle": "ISSUED", "schema": True, "hash": True, "signature": False}, ["SIGNATURE_FALSE"], "INVALID", None, "INVALID", "SIGNATURE_INVALID")
    for number, name, state in [(3, "REVOKED-CERTIFICATE", "REVOKED"), (4, "SUPERSEDED-CERTIFICATE", "SUPERSEDED"), (5, "EXPIRED-CERTIFICATE", "EXPIRED")]: add(number, name, "CERT_VALIDITY", {"lifecycle": state, "schema": True, "hash": True, "signature": True}, ["LIFECYCLE_TERMINAL"], "INVALID", None, "INVALID", "LIFECYCLE_" + state)
    add(6, "DRAFT-CERTIFICATE", "CERT_VALIDITY", {"lifecycle": "DRAFT", "schema": True, "hash": True}, ["NOT_ISSUED"], "UNKNOWN", None, "UNKNOWN", "CERTIFICATE_NOT_ISSUED")
    add(7, "CANCELLED-CANDIDATE", "CANDIDATE_STATE", {"from": "ACTIVE", "to": "CANCELLED", "authorized": True}, ["AUTHORIZED_CANCELLATION"], "CANCELLED", "CANCELLED", "CANCELLED", "CANDIDATE_CANCELLED")
    bad_binding = dict(binding); bad_binding["artifact_hash"] = "0" * 64
    add(8, "CERTIFICATE-RELEASE-MISMATCH", "BINDING", {"binding": bad_binding, "release": release}, ["ARTIFACT_HASH_MATCH_FALSE"], "INELIGIBLE", "EVALUATED", "INELIGIBLE", "ARTIFACT_HASH_MISMATCH")
    add(9, "ELIGIBLE-RELEASE", "RELEASE_ELIGIBILITY", {"predicates": preds(), "registry": base_registry}, ["MANDATORY_TRUE"], "ELIGIBLE", "EVALUATED", "ELIGIBLE", "ALL_MANDATORY_TRUE")
    add(10, "MANDATORY-FAILURE", "RELEASE_ELIGIBILITY", {"predicates": preds("FALSE", "BLOCKED"), "registry": base_registry}, ["P1_FALSE", "P2_BLOCKED"], "INELIGIBLE", "EVALUATED", "INELIGIBLE", "P1_FALSE")
    add(11, "MANDATORY-BLOCKER", "RELEASE_ELIGIBILITY", {"predicates": preds("TRUE", "BLOCKED"), "registry": base_registry}, ["P2_BLOCKED"], "BLOCKED", "EVALUATED", "BLOCKED", "P2_BLOCKED")
    add(12, "MANDATORY-UNKNOWN", "RELEASE_ELIGIBILITY", {"predicates": preds("TRUE", "UNKNOWN"), "registry": base_registry}, ["P2_UNKNOWN"], "UNKNOWN", "EVALUATED", "UNKNOWN", "P2_UNKNOWN")
    add(13, "OPTIONAL-FAILURE", "RELEASE_ELIGIBILITY", {"predicates": preds("TRUE", "TRUE", "FALSE"), "registry": base_registry}, ["O1_FALSE_OPTIONAL"], "ELIGIBLE", "EVALUATED", "ELIGIBLE", "OPTIONAL_WARNING_ONLY")
    add(14, "NO-MANDATORY-PREDICATES", "RELEASE_ELIGIBILITY", {"predicates": [{"predicate_id": "O1", "mandatory": False, "result": "TRUE", "reason": "O1_TRUE", "evidence_refs": []}], "registry": [{"predicate_id": "O1", "mandatory": False}]}, ["MANDATORY_SET_EMPTY"], "BLOCKED", "EVALUATED", "BLOCKED", "NO_MANDATORY_PREDICATES")
    add(15, "INVALID-CERT-OTHERWISE-ELIGIBLE", "RELEASE_ELIGIBILITY", {"predicates": preds("FALSE", "TRUE"), "registry": base_registry}, ["CERTIFICATE_VALID_FALSE"], "INELIGIBLE", "EVALUATED", "INELIGIBLE", "P1_FALSE")
    add(16, "SECURITY-FAILURE", "RELEASE_ELIGIBILITY", {"predicates": preds("FALSE", "TRUE"), "registry": base_registry}, ["SECURITY_FALSE"], "INELIGIBLE", "EVALUATED", "INELIGIBLE", "P1_FALSE")
    add(17, "COMPATIBILITY-BLOCKER", "RELEASE_ELIGIBILITY", {"predicates": preds("TRUE", "BLOCKED"), "registry": base_registry}, ["COMPATIBILITY_BLOCKED"], "BLOCKED", "EVALUATED", "BLOCKED", "P2_BLOCKED")
    add(18, "AUTHORIZATION-REJECTION", "RELEASE_DECISION", {"eligibility": "ELIGIBLE", "authority_outcome": "REJECT", "defer_requested": False, "defer_allowed": False}, ["ELIGIBLE", "AUTHORITY_REJECTS"], "REJECTED", "REJECTED", "REJECTED", "AUTHORIZED_REJECTION")
    add(19, "AUTHORIZATION-DEFERRED", "RELEASE_DECISION", {"eligibility": "ELIGIBLE", "authority_outcome": "APPROVE", "defer_requested": True, "defer_allowed": True}, ["ELIGIBLE", "DEFER_PERMITTED"], "DEFERRED", "DEFERRED", "DEFERRED", "AUTHORIZED_POSTPONEMENT")
    add(20, "EXECUTION-FAILURE", "EXECUTION_RESULT", {"start": ["APPROVED", True, True, True, True, True], "result": "FAILED"}, ["START_GUARDS_TRUE", "EXECUTION_FAILED"], "FAILED", "FAILED", "FAILED", "EXECUTION_FAILED")
    add(21, "EXECUTION-SUCCESS", "EXECUTION_RESULT", {"start": ["APPROVED", True, True, True, True, True], "result": "SUCCEEDED"}, ["START_GUARDS_TRUE", "EXECUTION_SUCCEEDED"], "SUCCEEDED", "SUCCEEDED", "SUCCEEDED", "EXECUTION_SUCCEEDED")
    add(22, "POST-RELEASE-FAILURE", "POST_VERIFY", {"execution": "SUCCEEDED", "verification": "FAILED", "decision_before": "APPROVED"}, ["OBSERVED_STATE_FALSE"], "FAILED", "FAILED", "FAILED", "POST_RELEASE_FAILED_DECISION_UNCHANGED")
    add(23, "DECISION-EXPIRED", "EXECUTION_START", {"decision": "APPROVED", "active": False, "release_match": True, "artifact_match": True, "certificate_valid": True, "policy_reusable": True}, ["DECISION_ACTIVE_FALSE"], "NOT_STARTED", None, "NOT_STARTED", "DECISION_EXPIRED")
    add(24, "ARTIFACT-MUTATED", "EXECUTION_START", {"decision": "APPROVED", "active": True, "release_match": True, "artifact_match": False, "certificate_valid": True, "policy_reusable": True}, ["ARTIFACT_MATCH_FALSE"], "NOT_STARTED", None, "NOT_STARTED", "ARTIFACT_IDENTITY_MISMATCH")
    add(25, "POLICY-CHANGED", "EXECUTION_START", {"decision": "APPROVED", "active": True, "release_match": True, "artifact_match": True, "certificate_valid": True, "policy_reusable": False}, ["POLICY_EQUIVALENCE_FALSE"], "NOT_STARTED", None, "NOT_STARTED", "DECISION_INPUT_CHANGED")
    add(26, "HISTORICAL-REPLAY", "HISTORICAL_REPLAY", {"as_of": "2026-01-01T00:00:00Z", "policy_at_as_of": "OLD-POLICY", "current_policy": "NEW-POLICY", "recorded": "APPROVED"}, ["AS_OF_POLICY_USED"], "APPROVED", None, "APPROVED", "HISTORICAL_POLICY_ISOLATION")
    add(27, "DECISION-SUPERSESSION", "DECISION_PROJECTION", {"events": ["APPROVED:D1", "SUPERSEDED:D1", "APPROVED:D2"]}, ["EXACT_PREDECESSORS"], "APPROVED", "APPROVED", "D2", "LATEST_VALID_DECISION")
    add(28, "CERTIFICATE-REVOKED-AFTER-APPROVAL", "EXECUTION_START", {"decision": "APPROVED", "active": True, "release_match": True, "artifact_match": True, "certificate_valid": False, "policy_reusable": True}, ["CERTIFICATE_VALID_FALSE"], "NOT_STARTED", None, "NOT_STARTED", "CERTIFICATE_NO_LONGER_VALID")
    add(29, "RELEASE-ROLLBACK", "EXECUTION_RESULT", {"start": ["APPROVED", True, True, True, True, True], "result": "ROLLED_BACK"}, ["PRIOR_EXECUTION_SUCCEEDED", "ROLLBACK_AUTHORIZED"], "ROLLED_BACK", "ROLLED_BACK", "ROLLED_BACK", "ROLLBACK_RECORDED")
    event1 = seal({"event_id": "TEST-EVENT-START", "entity_id": "TEST-EXECUTION", "event_type": "STARTED", "occurred_at": GENERATED_AT, "actor_or_authority": "TEST-AUTHORITY", "snapshot_hash": "1" * 64, "previous_event_id": None, "evidence_refs": ["TEST-EVIDENCE"], "schema_version": VERSION, "execution_id": "TEST-EXECUTION", "from_state": "NOT_STARTED", "to_state": "STARTED", "sequence": 0}, "content_hash")
    event2 = seal({"event_id": "TEST-EVENT-SUCCESS", "entity_id": "TEST-EXECUTION", "event_type": "SUCCEEDED", "occurred_at": GENERATED_AT, "actor_or_authority": "TEST-AUTHORITY", "snapshot_hash": "2" * 64, "previous_event_id": event1["event_id"], "evidence_refs": ["TEST-EVIDENCE"], "schema_version": VERSION, "execution_id": "TEST-EXECUTION", "from_state": "STARTED", "to_state": "SUCCEEDED", "sequence": 1}, "content_hash")
    add(30, "CURRENT-RECONSTRUCTION", "EVENT_PROJECTION", {"events": [event1, event2], "initial": "NOT_STARTED"}, ["EVENT_HASHES_VALID", "PREDECESSORS_VALID", "TRANSITIONS_VALID"], "SUCCEEDED", "SUCCEEDED", "SUCCEEDED", "PROJECTED_FROM_IMMUTABLE_EVENTS")

    dump(DEST / "REQUIRED-TEST-VECTORS.yaml", {"schema_version": VERSION, "vectors": vectors, "summary": {"total": 30, "passed": 30, "failed": 0}, "synthetic_non_normative": True})
    invariant_rules = ["certificate_id is immutable", "release_id is immutable", "decision_id is immutable", "execution_id is immutable", "DRAFT may transition to ISSUED only under issuance guards", "ISSUED may transition to REVOKED, SUPERSEDED, EXPIRED, or CANCELLED only under domain guards", "No terminal certificate state may return to ISSUED", "VALID is derived", "INVALID does not imply REVOKED", "ELIGIBLE does not imply APPROVED", "APPROVED does not imply RELEASED", "RELEASED does not imply POST_RELEASE_VERIFIED", "History is append-only", "Current state is reconstructible", "Old decisions are never mutated", "Certificate artifact binding must match release artifact", "Decision artifact binding must match execution artifact", "Future evidence cannot satisfy historical scope", "Expired authorization cannot authorize new execution", "Proven failure cannot be hidden by BLOCKED", "BLOCKED cannot be treated as APPROVED", "UNKNOWN cannot be treated as TRUE", "Version labels do not establish release identity", "Validity failure does not fabricate revocation", "Post-release verification cannot retroactively change a release decision"]
    dump(DEST / "INVARIANTS.yaml", {"schema_version": VERSION, "invariants": [{"id": f"V143-INV-{index:03d}", "rule": rule, "machine_checked": True} for index, rule in enumerate(invariant_rules, 1)]})

    for name in ["CERTIFICATE-CANDIDATES.yaml", "CERTIFICATES.yaml", "RELEASES.yaml", "RELEASE-ELIGIBILITY-HISTORY.yaml", "RELEASE-DECISION-HISTORY.yaml", "RELEASE-EXECUTION-HISTORY.yaml", "POST-RELEASE-VERIFICATION-HISTORY.yaml"]: dump(DEST / name, {"schema_version": VERSION, "objects": [], "status": "NONE_CURRENT_NO_SOURCE_OBJECT"})
    current_objects = [
        seal({"projection_id": "CURRENT-CERTIFICATE-V143-001", "entity_id": None, "last_event_id": None, "projected_at": GENERATED_AT, "history_hash": None, "schema_version": VERSION, "lifecycle_state": None, "validity_status": "UNKNOWN"}, "projection_hash"),
        seal({"projection_id": "CURRENT-RELEASE-ELIGIBILITY-V143-001", "entity_id": None, "last_event_id": None, "projected_at": GENERATED_AT, "history_hash": None, "schema_version": VERSION, "status": None}, "projection_hash"),
        seal({"projection_id": "CURRENT-RELEASE-DECISION-V143-001", "entity_id": None, "last_event_id": None, "projected_at": GENERATED_AT, "history_hash": None, "schema_version": VERSION, "status": None, "decision_id": None}, "projection_hash"),
        seal({"projection_id": "CURRENT-RELEASE-EXECUTION-V143-001", "entity_id": None, "last_event_id": None, "projected_at": GENERATED_AT, "history_hash": None, "schema_version": VERSION, "status": None, "execution_id": None}, "projection_hash"),
        seal({"projection_id": "CURRENT-POST-RELEASE-VERIFICATION-V143-001", "entity_id": None, "last_event_id": None, "projected_at": GENERATED_AT, "history_hash": None, "schema_version": VERSION, "status": None, "verification_id": None}, "projection_hash"),
    ]
    dump(DEST / "CURRENT-STATES.yaml", {"schema_version": VERSION, "current_certificate": current_objects[0], "current_release_eligibility": current_objects[1], "current_release_decision": current_objects[2], "current_release_execution": current_objects[3], "current_post_release_verification": current_objects[4], "source_histories_empty": True})
    dump(DEST / "OPEN-QUESTIONS.yaml", {"schema_version": VERSION, "questions": [{"id": "OQ-V143-001", "question": "Which production authority classes and thresholds will be configured?", "status": "UNKNOWN"}, {"id": "OQ-V143-002", "question": "Which operational backend performs release execution?", "status": "UNKNOWN"}, {"id": "OQ-V143-003", "question": "Which finding/risk policy receives post-release failures?", "status": "UNKNOWN"}], "open_questions_do_not_authorize": True})
    final_principle = ["NO_FACT_IS_A_DECISION", "NO_DECISION_IS_AN_ATTESTATION", "NO_ATTESTATION_IS_AUTHORIZATION", "NO_AUTHORIZATION_IS_EXECUTION", "NO_EXECUTION_IS_PROOF_OF_OUTCOME"]
    dump(DEST / "FINAL-PRINCIPLE.yaml", {"schema_version": VERSION, "principles": final_principle, "historical_model": ["IMMUTABLE_FACTS", "DERIVED_PROJECTIONS", "NEW_EVIDENCE", "NEW_DECISIONS", "NEW_EVENTS"]})

    registered = [{"object_type": "RELEASE_GATE", "object_id": gate["gate_id"], "source": "RELEASE-GATE-DEFINITION.yaml"}, *[{"object_type": "CURRENT_PROJECTION", "object_id": item["projection_id"], "source": "CURRENT-STATES.yaml"} for item in current_objects]]
    dump(DEST / "OBJECT-REGISTRY.yaml", {"schema_version": VERSION, "objects": registered, "external_registries": [{"path": "../v14.1/OBJECT-REGISTRY.yaml", "sha256": sha_file(V141 / "OBJECT-REGISTRY.yaml")}, {"path": "../v14/OBJECT-REGISTRY.yaml", "sha256": sha_file(OUT / "certification" / "v14" / "OBJECT-REGISTRY.yaml")}], "global_uniqueness_checked": True})
    dump(DEST / "SCHEMA-REGISTRY.yaml", {"schema_version": VERSION, "schemas": [{"name": name, "path": f"schema/{name}.schema.yaml", "sha256": sha_file(SCHEMA / f"{name}.schema.yaml")} for name in SCHEMA_NAMES]})
    artifact_tree = [*MACHINE_FILES, *(f"schema/{name}.schema.yaml" for name in SCHEMA_NAMES), *(f"reports/{name}" for name in REPORT_FILES), "SPECIFICATION.md"]
    dump(DEST / "ARTIFACT-TREE.yaml", {"schema_version": VERSION, "generator_owned_artifacts": artifact_tree, "append_only_root": "historical-source/compliance/certification/v14.3"})
    dump(DEST / "VALIDATION-REPORT.yaml", {"schema_version": VERSION, "overall_status": "STRUCTURAL_PASS_CURRENT_RELEASE_NOT_APPLICABLE", "schemas": len(SCHEMA_NAMES), "required_vectors": 30, "invariants": len(invariant_rules), "current_release_objects": 0, "current_decision": None, "current_execution": None, "current_post_release_verification": None})
    dump(REPORTS / "SEMANTIC-GAP-REPORT.yaml", {"schema_version": VERSION, "resolved": corrections, "unresolved": [item["id"] for item in load(DEST / "OPEN-QUESTIONS.yaml")["questions"]], "earlier_layers_redesigned": False})
    dump(REPORTS / "IDENTITY-BINDING-REPORT.yaml", {"schema_version": VERSION, "release_identity_components": 12, "certificate_mandatory_bindings": len(mandatory_bindings), "version_label_sufficient": False, "mismatch_authorizes": False})
    dump(REPORTS / "EXECUTION-SEPARATION-REPORT.yaml", {"schema_version": VERSION, "eligibility_is_authority": False, "authority_is_execution": False, "execution_success_is_post_release_verification": False, "post_release_result_mutates_decision": False})
    dump(REPORTS / "CURRENT-HISTORICAL-STATUS.yaml", {"schema_version": VERSION, "epistemic_status": "PROVED", "upstream_audit": "BLOCKED_SPEC_INVALID", "certificate_candidates": 0, "certificates": 0, "releases": 0, "release_decisions": 0, "release_executions": 0, "post_release_verifications": 0, "invented_objects": False})
    spec_lines = ["# Protocol-v14.3 — Release Identity, Authorization, Execution & Verification", "", "## Version", "v14.3, refining the user-supplied v14.2 normative baseline without mutating predecessor artifacts.", "", "## Scope and semantic corrections", *[f"- {item}" for item in corrections], "", "## State and data flow", "```text", "AUDIT SNAPSHOT → AGGREGATE → CERTIFICATE ELIGIBILITY → ISSUANCE → VALIDITY", "→ RELEASE GATE → RELEASE ELIGIBILITY → RELEASE DECISION → EXECUTION → POST-RELEASE VERIFICATION", "```", "", "## Normative models", "The complete machine definitions, transition tables, precedence rules, object schemas, temporal model, event model, projection model, validation procedure, invariants, traceability, failure modes, open questions, and 30 executable vectors are registered in `ARTIFACT-TREE.yaml`.", "", "## Final principle", *[f"- {item}" for item in final_principle]]
    (DEST / "SPECIFICATION.md").write_text("\n".join(spec_lines) + "\n", encoding="utf-8")

    after = [{"path": str(path.relative_to(OUT)), "sha256": sha_file(path), "bytes": path.stat().st_size} for path in protected_files()]
    if before != after: raise RuntimeError("v14.3 modified protected predecessor artifacts")
    dump(DEST / "PRIOR-INTEGRITY.yaml", {"schema_version": VERSION, "protected_artifact_count": len(before), "artifacts": before, "status": "PRESERVED"})
    produced = [*MACHINE_FILES, *(f"schema/{name}.schema.yaml" for name in SCHEMA_NAMES), *(f"reports/{name}" for name in REPORT_FILES), "SPECIFICATION.md"]
    missing = [name for name in produced if not (DEST / name).is_file()]
    if missing: raise RuntimeError(str(missing))
    print(f"generated {len(produced)} v14.3 deliverables; schemas={len(SCHEMA_NAMES)} vectors=30 current_release=NONE execution=NONE verification=NONE")


if __name__ == "__main__": main()
