#!/usr/bin/env python3
"""Deterministic Rust type-blueprint sources for the frozen R5 domains."""


def sources():
    return {
        "Cargo.toml": '''[package]
name = "gde_v147_r5_types"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
''',
        "Cargo.lock": '''# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "gde_v147_r5_types"
version = "0.1.0"
''',
        "src/lib.rs": '''#![forbid(unsafe_code)]
pub mod conversions;
pub mod enums;
pub mod evaluator;
pub mod ids;
pub mod objects;
''',
        "src/ids.rs": '''macro_rules! identifier { ($name:ident) => { #[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)] pub struct $name(pub String); }; }
identifier!(RequirementId);
identifier!(ProfileId);
identifier!(PredicateId);
identifier!(EvaluationId);
identifier!(ValidationId);
identifier!(EvidenceId);
identifier!(CertificateId);
identifier!(ReleaseId);
identifier!(DecisionId);
identifier!(EventId);
identifier!(ImplementationId);
identifier!(AuthorityId);
identifier!(SnapshotId);
identifier!(DecisionBasisId);
''',
        "src/enums.rs": '''#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum EvaluationValue { True, False, Unknown, Blocked, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ValidationStatus { Valid, Invalid, Blocked, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ConformanceStatus { Conformant, PartiallyConformant, NonConformant, Unverified, Blocked, NotApplicable, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum CertificateLifecycle { Draft, Issued, Revoked, Superseded, Expired, Cancelled }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum CertificateValidity { Valid, Invalid, NotYetValid, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ReleaseEligibility { Eligible, Ineligible, Blocked, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum AuthorizationStatus { Authorized, Refused, Blocked, Unknown, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ReleaseDecision { Approved, Rejected, Blocked, Deferred }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ReleaseExecution { NotStarted, Started, Succeeded, Failed, Cancelled, RolledBack }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum PostReleaseVerification { NotStarted, InProgress, Passed, Failed, Inconclusive, Blocked, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ReuseResult { Reusable, NotReusable, Blocked, Unknown, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum AuthorityStatus { Active, Suspended, Revoked, Expired, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum AuthorityQualification { Qualified, NotQualified, Blocked, Unknown, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum EventValidation { Valid, Invalid, Blocked, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum EventCommit { Pending, Committed, Rejected }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ProjectionStatus { Current, Replaying, Stale, Invalid, Blocked, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum RequirementLifecycle { Proposed, Draft, Active, Deprecated, Superseded, Retired }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum FindingLifecycle { Open, Triaged, RootCauseIdentified, RemediationPlanned, RemediationInProgress, ReadyForReverification, ReverificationInProgress, Resolved, Waived, Rejected, Closed }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum RemediationStatus { Planned, Approved, InProgress, Blocked, ReadyForVerification, Verified, Failed, Cancelled, Superseded }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum NormativeStrength { Must, MustNot, Should, ShouldNot, May }
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum EmptyMandatoryAction { Allow, Deny, Block, Unknown }
''',
        "src/evaluator.rs": '''use crate::enums::EvaluationValue;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EvaluatorError { InvalidPredicate, InvalidSubject, InvalidContext, ValidationRequired, ValidationFailed, UnsupportedPredicate, EvaluatorFailure, EvaluatorTimeout, EvaluatorResourceFailure, EvaluatorInternalFailure, OutputInvalid, EvaluatorDependencyUnavailable }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EvaluationResult { pub evaluation_id: crate::ids::EvaluationId, pub predicate_ref: crate::ids::PredicateId, pub value: EvaluationValue, pub content_hash: [u8; 32] }
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EvaluationCompletion { Result(EvaluationResult), Error(EvaluatorError) }
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ErrorDisposition { EvaluationFailure, Unknown, Blocked, Invalid }
pub fn default_disposition(_error: EvaluatorError) -> ErrorDisposition { ErrorDisposition::EvaluationFailure }
''',
        "src/conversions.rs": '''use crate::enums::{AuthorizationStatus, ConformanceStatus, EvaluationValue, ReleaseEligibility, ValidationStatus};
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub struct EvaluationEligible;
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub struct PredicateOutcome(pub EvaluationValue);
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub struct AggregateEvaluation(pub EvaluationValue);
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub struct AuthorizationInput;
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub struct ReleaseDecisionInput;
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum ConversionError { InvalidSource, MissingEvidence, PolicyRequired }
pub fn validation_to_evaluation_eligibility(value: ValidationStatus) -> Result<EvaluationEligible, ConversionError> { match value { ValidationStatus::Valid => Ok(EvaluationEligible), _ => Err(ConversionError::InvalidSource) } }
pub fn evaluation_to_predicate_outcome(value: EvaluationValue) -> Result<PredicateOutcome, ConversionError> { if value == EvaluationValue::Invalid { Err(ConversionError::InvalidSource) } else { Ok(PredicateOutcome(value)) } }
pub fn predicate_outcome_to_aggregate(value: PredicateOutcome) -> AggregateEvaluation { AggregateEvaluation(value.0) }
pub fn aggregate_to_release_eligibility(value: AggregateEvaluation) -> Result<ReleaseEligibility, ConversionError> { match value.0 { EvaluationValue::True => Ok(ReleaseEligibility::Eligible), EvaluationValue::False => Ok(ReleaseEligibility::Ineligible), EvaluationValue::Blocked => Ok(ReleaseEligibility::Blocked), EvaluationValue::Unknown => Ok(ReleaseEligibility::Unknown), EvaluationValue::Invalid => Err(ConversionError::InvalidSource) } }
pub fn conformance_to_compliance(value: ConformanceStatus) -> ConformanceStatus { value }
pub fn release_eligibility_to_authorization_input(value: ReleaseEligibility) -> Result<AuthorizationInput, ConversionError> { if value == ReleaseEligibility::Eligible { Ok(AuthorizationInput) } else { Err(ConversionError::InvalidSource) } }
pub fn authorization_to_decision_input(value: AuthorizationStatus) -> Result<ReleaseDecisionInput, ConversionError> { if value == AuthorizationStatus::Authorized { Ok(ReleaseDecisionInput) } else { Err(ConversionError::InvalidSource) } }
''',
        "src/objects.rs": '''use crate::enums::*;
use crate::ids::*;
#[derive(Clone, Debug, Eq, PartialEq)] pub struct ValidationResult { pub validation_id: ValidationId, pub subject_ref: String, pub status: ValidationStatus, pub content_hash: [u8; 32] }
#[derive(Clone, Debug, Eq, PartialEq)] pub struct ConformanceResult { pub requirement_ref: RequirementId, pub status: ConformanceStatus, pub evaluation_refs: Vec<EvaluationId>, pub evidence_refs: Vec<EvidenceId>, pub content_hash: [u8; 32] }
#[derive(Clone, Debug, Eq, PartialEq)] pub struct AuthorizationResult { pub authority_ref: AuthorityId, pub release_ref: ReleaseId, pub status: AuthorizationStatus, pub content_hash: [u8; 32] }
''',
        "tests/enum_closure.rs": '''use gde_v147_r5_types::enums::{EvaluationValue, ValidationStatus};
#[test] fn domains_are_not_interchangeable() { let evaluation = EvaluationValue::Unknown; let validation = ValidationStatus::Unknown; assert!(matches!(evaluation, EvaluationValue::Unknown)); assert!(matches!(validation, ValidationStatus::Unknown)); }
''',
        "tests/evaluator_error.rs": '''use gde_v147_r5_types::evaluator::{default_disposition, ErrorDisposition, EvaluatorError};
#[test] fn evaluator_error_defaults_to_failure() { assert_eq!(default_disposition(EvaluatorError::EvaluatorTimeout), ErrorDisposition::EvaluationFailure); }
''',
        "tests/conversions.rs": '''use gde_v147_r5_types::conversions::validation_to_evaluation_eligibility;
use gde_v147_r5_types::enums::ValidationStatus;
#[test] fn only_valid_is_evaluation_eligible() { assert!(validation_to_evaluation_eligibility(ValidationStatus::Valid).is_ok()); assert!(validation_to_evaluation_eligibility(ValidationStatus::Unknown).is_err()); }
''',
    }
