#!/usr/bin/env python3
"""Deterministic no-dependency Rust source templates for v14.7-R4."""


def sources():
    files = {
        "Cargo.toml": '''[package]
name = "v14_7_runtime"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
''',
        "Cargo.lock": '''# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "v14_7_runtime"
version = "0.1.0"
''',
        "src/lib.rs": '''#![forbid(unsafe_code)]
//! Reference domain model for the frozen v14.7-R4 realization profile.

pub mod authorization;
pub mod conformance;
pub mod domain;
pub mod evaluation;
pub mod events;
pub mod identity;
pub mod projection;
pub mod state;
pub mod validation;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawSubject {
    pub subject_ref: String,
    pub payload: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidatedSubject {
    subject_ref: String,
    payload: String,
}

impl ValidatedSubject {
    pub(crate) fn new(raw: RawSubject) -> Self {
        Self { subject_ref: raw.subject_ref, payload: raw.payload }
    }
    pub fn subject_ref(&self) -> &str { &self.subject_ref }
    pub fn payload(&self) -> &str { &self.payload }
}
''',
        "src/domain/mod.rs": '''pub mod authority;
pub mod certificate;
pub mod conformance;
pub mod decision;
pub mod evaluation;
pub mod evidence;
pub mod execution;
pub mod profile;
pub mod release;
pub mod requirement;
pub mod validation;
pub mod verification;
''',
        "src/domain/requirement.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RequirementId(pub String);
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ConditionRef(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NormativeStrength { Must, MustNot, Should, ShouldNot, May }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Requirement {
    pub requirement_id: RequirementId,
    pub statement: String,
    pub strength: NormativeStrength,
    pub acceptance_criteria: Vec<ConditionRef>,
}
''',
        "src/domain/profile.rs": '''use super::evaluation::EmptyMandatoryAction;
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ProfileId(pub String);
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ImplementationId(pub String);
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Profile {
    pub profile_id: ProfileId,
    pub profile_version: String,
    pub specification_hash: String,
    pub empty_mandatory_action: EmptyMandatoryAction,
}
''',
        "src/domain/evidence.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct EvidenceId(pub String);
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Evidence {
    pub evidence_id: EvidenceId,
    pub subject_ref: String,
    pub observation: String,
    pub integrity_valid: bool,
}
''',
        "src/domain/validation.rs": '''use super::evidence::EvidenceId;
use crate::identity::hashing::ContentHash;
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ValidationId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ValidationStatus { Valid, Invalid, Blocked, Unknown }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidationResult {
    pub validation_id: ValidationId,
    pub subject_ref: String,
    pub status: ValidationStatus,
    pub failure_codes: Vec<String>,
    pub evidence_refs: Vec<EvidenceId>,
    pub validator_id: String,
    pub scope_ref: String,
    pub input_hash: ContentHash,
    pub validated_at: String,
    pub content_hash: ContentHash,
}
''',
        "src/domain/evaluation.rs": '''use super::evidence::EvidenceId;
use crate::identity::hashing::ContentHash;
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PredicateId(pub String);
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct EvaluationId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EvaluationValue { True, False, Unknown, Blocked, Invalid }
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EmptyMandatoryAction { Allow, Deny, Block, Unknown }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EvaluationResult {
    pub evaluation_id: EvaluationId,
    pub subject_ref: String,
    pub predicate_ref: PredicateId,
    pub result: EvaluationValue,
    pub reason_codes: Vec<String>,
    pub evidence_refs: Vec<EvidenceId>,
    pub input_refs: Vec<String>,
    pub evaluator_id: String,
    pub evaluator_version: String,
    pub scope_ref: String,
    pub freshness: String,
    pub integrity: String,
    pub evaluated_at: String,
    pub sequence_no: u64,
    pub content_hash: ContentHash,
}
''',
        "src/domain/conformance.rs": '''use super::evidence::EvidenceId;
use crate::identity::hashing::ContentHash;
use super::evaluation::EvaluationId;
use super::requirement::{ConditionRef, RequirementId};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ConformanceStatus { Conformant, PartiallyConformant, NonConformant, Unverified, Blocked, NotApplicable, Unknown }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConformanceResult {
    pub requirement_ref: RequirementId,
    pub status: ConformanceStatus,
    pub evaluation_refs: Vec<EvaluationId>,
    pub evidence_refs: Vec<EvidenceId>,
    pub violated_conditions: Vec<ConditionRef>,
    pub rationale_codes: Vec<String>,
    pub content_hash: ContentHash,
}
''',
        "src/domain/authority.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct AuthorityId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthorityQualification { Qualified, Unqualified, Blocked, Unknown, Invalid }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Authority {
    pub authority_id: AuthorityId,
    pub active: bool,
    pub operations: Vec<String>,
    pub scopes: Vec<String>,
    pub not_before: u64,
    pub not_after: Option<u64>,
    pub threshold: usize,
}
''',
        "src/domain/certificate.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CertificateId(pub String);
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Certificate { pub certificate_id: CertificateId, pub subject_hash: String, pub valid: bool }
''',
        "src/domain/release.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ReleaseId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReleaseEligibility { Eligible, Ineligible, Blocked, Unknown }
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReuseResult { Reusable, NotReusable, Blocked, Unknown, Invalid }
''',
        "src/domain/decision.rs": '''use super::release::{ReleaseId, ReuseResult};
use crate::identity::hashing::ContentHash;
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DecisionId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DecisionStatus { Approved, Rejected, Blocked, Deferred }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DecisionBasis {
    pub release_id: ReleaseId, pub artifact_hash: String, pub implementation_id: String,
    pub specification_hash: String, pub audit_snapshot_hash: String, pub certificate_id: String,
    pub gate_hash: String, pub policy_hash: String, pub environment_hash: String, pub evidence_hash: String,
    pub authority_context_hash: String, pub waiver_hash: String, pub security_context_hash: String,
    pub compatibility_context_hash: String, pub temporal_context: String, pub content_hash: ContentHash,
}
pub fn check_decision_reuse(old_basis: &DecisionBasis, new_basis: &DecisionBasis, constraints_valid: bool) -> ReuseResult {
    if !constraints_valid { ReuseResult::Blocked }
    else if old_basis.content_hash == new_basis.content_hash { ReuseResult::Reusable }
    else { ReuseResult::NotReusable }
}
''',
        "src/domain/execution.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ExecutionId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutionStatus { Succeeded, Failed, Blocked, Unknown }
''',
        "src/domain/verification.rs": '''#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct VerificationId(pub String);
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum VerificationStatus { Verified, Failed, Blocked, Unknown }
''',
        "src/validation/mod.rs": '''pub mod authority;
pub mod freshness;
pub mod integrity;
pub mod policy;
pub mod reference;
pub mod scope;
pub mod structural;
pub mod temporal;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ValidationError {
    Structural(String), Reference(String), Integrity(String), Temporal(String), Scope(String),
    Policy(String), Authority(String), Evidence(String), Freshness(String),
}
''',
        "src/validation/structural.rs": '''use crate::{RawSubject, ValidatedSubject};
use super::ValidationError;
pub fn validate(raw: RawSubject) -> Result<ValidatedSubject, ValidationError> {
    if raw.subject_ref.is_empty() { return Err(ValidationError::Structural("missing subject_ref".into())); }
    Ok(ValidatedSubject::new(raw))
}
''',
        "src/validation/reference.rs": '''use super::ValidationError;
pub fn validate(exists: bool) -> Result<(), ValidationError> { if exists { Ok(()) } else { Err(ValidationError::Reference("missing reference".into())) } }
''',
        "src/validation/integrity.rs": '''use super::ValidationError;
pub fn validate(matches: bool) -> Result<(), ValidationError> { if matches { Ok(()) } else { Err(ValidationError::Integrity("hash mismatch".into())) } }
''',
        "src/validation/temporal.rs": '''use super::ValidationError;
pub fn validate(now: u64, not_before: u64, not_after: Option<u64>) -> Result<(), ValidationError> {
    if now < not_before || not_after.map(|end| now >= end).unwrap_or(false) { Err(ValidationError::Temporal("outside interval".into())) } else { Ok(()) }
}
''',
        "src/validation/scope.rs": '''use super::ValidationError;
pub fn validate(requested: &[String], granted: &[String]) -> Result<(), ValidationError> {
    if requested.iter().all(|item| granted.contains(item)) { Ok(()) } else { Err(ValidationError::Scope("out of scope".into())) }
}
''',
        "src/validation/policy.rs": '''use super::ValidationError;
pub fn validate(valid: bool) -> Result<(), ValidationError> { if valid { Ok(()) } else { Err(ValidationError::Policy("invalid policy".into())) } }
''',
        "src/validation/authority.rs": '''use super::ValidationError;
pub fn validate(valid: bool) -> Result<(), ValidationError> { if valid { Ok(()) } else { Err(ValidationError::Authority("invalid authority".into())) } }
''',
        "src/validation/freshness.rs": '''use super::ValidationError;
pub fn validate(fresh: bool) -> Result<(), ValidationError> { if fresh { Ok(()) } else { Err(ValidationError::Freshness("stale evidence".into())) } }
''',
        "src/evaluation/mod.rs": '''pub mod aggregate;
pub mod evaluator;
pub mod predicate;
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EvaluationError { InvalidPredicate, MissingInput, EvaluatorUnavailable, EvaluationContextInvalid, EvidenceInvalid, InternalFailure }
''',
        "src/evaluation/predicate.rs": '''#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Predicate { AlwaysTrue, AlwaysFalse, Unknown, Blocked }
''',
        "src/evaluation/evaluator.rs": '''use crate::ValidatedSubject;
use crate::domain::evaluation::{EvaluationId, EvaluationResult, EvaluationValue, PredicateId};
use crate::identity::hashing::ContentHash;
use super::{EvaluationError, predicate::Predicate};
pub trait Evaluator {
    fn identity(&self) -> (&str, &str);
    fn evaluate(&self, predicate: &Predicate, subject: &ValidatedSubject, context_ref: &str) -> Result<EvaluationResult, EvaluationError>;
}
pub struct ReferenceEvaluator;
impl Evaluator for ReferenceEvaluator {
    fn identity(&self) -> (&str, &str) { ("v14.7-reference", "14.7-R4") }
    fn evaluate(&self, predicate: &Predicate, subject: &ValidatedSubject, context_ref: &str) -> Result<EvaluationResult, EvaluationError> {
        if context_ref.is_empty() { return Err(EvaluationError::EvaluationContextInvalid); }
        let value = match predicate { Predicate::AlwaysTrue => EvaluationValue::True, Predicate::AlwaysFalse => EvaluationValue::False, Predicate::Unknown => EvaluationValue::Unknown, Predicate::Blocked => EvaluationValue::Blocked };
        Ok(EvaluationResult { evaluation_id: EvaluationId("reference".into()), subject_ref: subject.subject_ref().into(), predicate_ref: PredicateId("predicate".into()), result: value, reason_codes: vec![], evidence_refs: vec![], input_refs: vec![], evaluator_id: self.identity().0.into(), evaluator_version: self.identity().1.into(), scope_ref: context_ref.into(), freshness: "FRESH".into(), integrity: "VALID".into(), evaluated_at: "1970-01-01T00:00:00Z".into(), sequence_no: 0, content_hash: ContentHash::zero() })
    }
}
''',
        "src/evaluation/aggregate.rs": '''use crate::domain::evaluation::{EmptyMandatoryAction, EvaluationValue};
use super::EvaluationError;
pub fn aggregate(results: &[EvaluationValue], empty: EmptyMandatoryAction) -> Result<EvaluationValue, EvaluationError> {
    if results.is_empty() { return Ok(match empty { EmptyMandatoryAction::Allow => EvaluationValue::True, EmptyMandatoryAction::Deny => EvaluationValue::False, EmptyMandatoryAction::Block => EvaluationValue::Blocked, EmptyMandatoryAction::Unknown => EvaluationValue::Unknown }); }
    if results.contains(&EvaluationValue::Invalid) { return Err(EvaluationError::InvalidPredicate); }
    if results.contains(&EvaluationValue::False) { return Ok(EvaluationValue::False); }
    if results.contains(&EvaluationValue::Blocked) { return Ok(EvaluationValue::Blocked); }
    if results.contains(&EvaluationValue::Unknown) { return Ok(EvaluationValue::Unknown); }
    Ok(EvaluationValue::True)
}
''',
        "src/authorization/mod.rs": '''pub mod authorize;
pub mod qualification;
pub mod threshold;
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthorizationResult { Authorized, Denied, Blocked, Unknown, Invalid }
''',
        "src/authorization/threshold.rs": '''use std::collections::BTreeSet;
pub fn distinct_valid(approvals: &[(String, bool)]) -> usize { approvals.iter().filter(|(_, valid)| *valid).map(|(id, _)| id).collect::<BTreeSet<_>>().len() }
''',
        "src/authorization/qualification.rs": '''use crate::domain::authority::{Authority, AuthorityQualification};
use super::threshold::distinct_valid;
pub fn qualify(authority: &Authority, operation: &str, scope: &str, now: u64, approvals: &[(String, bool)]) -> AuthorityQualification {
    if !authority.active || !authority.operations.iter().any(|item| item == operation) || !authority.scopes.iter().any(|item| item == scope) { return AuthorityQualification::Unqualified; }
    if now < authority.not_before || authority.not_after.map(|end| now >= end).unwrap_or(false) { return AuthorityQualification::Unqualified; }
    if distinct_valid(approvals) < authority.threshold { return AuthorityQualification::Blocked; }
    AuthorityQualification::Qualified
}
''',
        "src/authorization/authorize.rs": '''use crate::domain::{authority::AuthorityQualification, release::ReleaseEligibility};
use super::AuthorizationResult;
pub fn authorize(eligibility: ReleaseEligibility, authority: AuthorityQualification, policy_valid: bool, scope_valid: bool, credential_valid: bool, temporal_valid: bool, threshold_valid: bool) -> AuthorizationResult {
    if eligibility == ReleaseEligibility::Eligible && authority == AuthorityQualification::Qualified && policy_valid && scope_valid && credential_valid && temporal_valid && threshold_valid { AuthorizationResult::Authorized } else if eligibility == ReleaseEligibility::Ineligible { AuthorizationResult::Denied } else { AuthorizationResult::Blocked }
}
''',
        "src/state/mod.rs": '''pub mod guard;
pub mod transition;
''',
        "src/state/transition.rs": '''#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CurrentState { pub state: String, pub last_event: Option<String>, pub allowed_events: Vec<String> }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StateTransitionEvent { pub event_id: String, pub event_type: String, pub predecessor: Option<String>, pub evidence_valid: bool, pub authority_valid: bool, pub scope_valid: bool, pub temporal_valid: bool }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidatedTransition(pub(crate) StateTransitionEvent);
impl ValidatedTransition { pub fn event(&self) -> &StateTransitionEvent { &self.0 } }
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TransitionError { InvalidEvidence, InvalidAuthority, InvalidScope, InvalidTemporalContext, InvalidPredecessor, IllegalTransition }
''',
        "src/state/guard.rs": '''use super::transition::{CurrentState, StateTransitionEvent, TransitionError, ValidatedTransition};
pub fn guard_transition(current: &CurrentState, event: StateTransitionEvent) -> Result<ValidatedTransition, TransitionError> {
    if !event.evidence_valid { return Err(TransitionError::InvalidEvidence); }
    if !event.authority_valid { return Err(TransitionError::InvalidAuthority); }
    if !event.scope_valid { return Err(TransitionError::InvalidScope); }
    if !event.temporal_valid { return Err(TransitionError::InvalidTemporalContext); }
    if event.predecessor != current.last_event { return Err(TransitionError::InvalidPredecessor); }
    if !current.allowed_events.contains(&event.event_type) { return Err(TransitionError::IllegalTransition); }
    Ok(ValidatedTransition(event))
}
''',
        "src/events/mod.rs": '''pub mod event;
pub mod ordering;
pub mod store;
''',
        "src/events/event.rs": '''use crate::state::transition::ValidatedTransition;
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct EventId(pub String);
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidatedEvent { pub(crate) stream_id: String, pub(crate) sequence_no: u64, pub(crate) transition: ValidatedTransition }
impl ValidatedEvent {
    pub fn from_transition(stream_id: String, sequence_no: u64, transition: ValidatedTransition) -> Self { Self { stream_id, sequence_no, transition } }
    pub fn stream_id(&self) -> &str { &self.stream_id }
    pub fn sequence_no(&self) -> u64 { self.sequence_no }
    pub fn transition(&self) -> &ValidatedTransition { &self.transition }
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommittedEvent { pub event: ValidatedEvent, pub commit_index: u64 }
''',
        "src/events/ordering.rs": '''use super::event::CommittedEvent;
pub fn ordered(history: &[CommittedEvent]) -> Vec<&CommittedEvent> {
    let mut items: Vec<_> = history.iter().collect();
    items.sort_by(|left, right| left.event.stream_id.cmp(&right.event.stream_id)
        .then(left.event.sequence_no.cmp(&right.event.sequence_no))
        .then(left.commit_index.cmp(&right.commit_index)));
    items
}
''',
        "src/events/store.rs": '''use std::collections::BTreeSet;
use std::sync::Mutex;
use super::event::{CommittedEvent, ValidatedEvent};
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EventStoreError { SequenceCollision, Poisoned }
pub trait EventStore { fn append(&self, event: ValidatedEvent) -> Result<CommittedEvent, EventStoreError>; }
pub struct InMemoryEventStore { inner: Mutex<(BTreeSet<(String, u64)>, Vec<CommittedEvent>)> }
impl InMemoryEventStore { pub fn new() -> Self { Self { inner: Mutex::new((BTreeSet::new(), vec![])) } } }
impl Default for InMemoryEventStore { fn default() -> Self { Self::new() } }
impl EventStore for InMemoryEventStore {
    fn append(&self, event: ValidatedEvent) -> Result<CommittedEvent, EventStoreError> {
        let mut guard = self.inner.lock().map_err(|_| EventStoreError::Poisoned)?;
        let key = (event.stream_id.clone(), event.sequence_no);
        if !guard.0.insert(key) { return Err(EventStoreError::SequenceCollision); }
        let committed = CommittedEvent { event, commit_index: guard.1.len() as u64 };
        guard.1.push(committed.clone()); Ok(committed)
    }
}
''',
        "src/projection/mod.rs": '''pub mod projector;
pub mod verifier;
''',
        "src/projection/projector.rs": '''use std::collections::BTreeMap;
use crate::events::{event::CommittedEvent, ordering::ordered};
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CurrentState(pub BTreeMap<String, String>);
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProjectionError { InvalidHistory }
pub fn project(history: &[CommittedEvent], _profile_ref: &str) -> Result<CurrentState, ProjectionError> {
    let mut state = BTreeMap::new();
    for committed in ordered(history) { state.insert(committed.event.transition.0.event_type.clone(), committed.event.transition.0.event_id.clone()); }
    Ok(CurrentState(state))
}
''',
        "src/projection/verifier.rs": '''use super::projector::CurrentState;
pub fn verify(expected: &CurrentState, actual: &CurrentState) -> bool { expected == actual }
''',
        "src/identity/mod.rs": '''pub mod canonical;
pub mod hashing;
''',
        "src/identity/canonical.rs": '''use std::collections::BTreeMap;
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CanonicalizationError { Unsupported }
pub trait CanonicalSerialize { fn canonical_bytes(&self) -> Result<Vec<u8>, CanonicalizationError>; }
impl CanonicalSerialize for BTreeMap<String, String> {
    fn canonical_bytes(&self) -> Result<Vec<u8>, CanonicalizationError> {
        let body = self.iter().map(|(key, value)| format!("{}:{}{}:{}", key.len(), key, value.len(), value)).collect::<Vec<_>>().join("|");
        Ok(body.into_bytes())
    }
}
''',
        "src/identity/hashing.rs": '''use super::canonical::{CanonicalSerialize, CanonicalizationError};
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ContentHash(pub [u8; 32]);
impl ContentHash { pub fn zero() -> Self { Self([0; 32]) } }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DomainSeparatedInput(pub Vec<u8>);
pub fn hash_input<T: CanonicalSerialize>(domain_tag: &str, value: &T) -> Result<DomainSeparatedInput, CanonicalizationError> {
    let mut input = domain_tag.as_bytes().to_vec(); input.push(b':'); input.extend(value.canonical_bytes()?); Ok(DomainSeparatedInput(input))
}
''',
        "src/conformance/mod.rs": '''pub mod harness;
pub mod oracle;
pub mod report;
pub mod vectors;
''',
        "src/conformance/vectors.rs": '''#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TestVector { pub test_id: String, pub profile_ref: String, pub requirement_refs: Vec<String>, pub operation: String, pub expected: String }
''',
        "src/conformance/oracle.rs": '''use crate::domain::conformance::{ConformanceResult, ConformanceStatus};
use crate::domain::evidence::EvidenceId;
use crate::domain::evaluation::{EvaluationResult, EvaluationValue};
use crate::domain::requirement::Requirement;
use crate::identity::hashing::ContentHash;
use super::vectors::TestVector;
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ConformanceError { InvalidEvaluation, MissingAcceptanceCriterion }
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OracleResult { pub test_id: String, pub passed: bool, pub actual: String }
pub fn compare(vector: &TestVector, actual: String) -> OracleResult { OracleResult { test_id: vector.test_id.clone(), passed: actual == vector.expected, actual } }
pub fn assess_requirement(requirement: &Requirement, evaluations: &[EvaluationResult], evidence_refs: Vec<EvidenceId>) -> Result<ConformanceResult, ConformanceError> {
    if evaluations.iter().any(|item| item.result == EvaluationValue::Invalid) { return Err(ConformanceError::InvalidEvaluation); }
    if evidence_refs.is_empty() { return Ok(ConformanceResult { requirement_ref: requirement.requirement_id.clone(),
        status: ConformanceStatus::Unverified, evaluation_refs: evaluations.iter().map(|item| item.evaluation_id.clone()).collect(),
        evidence_refs, violated_conditions: vec![], rationale_codes: vec![], content_hash: ContentHash::zero() }); }
    let mut status = ConformanceStatus::Conformant;
    let mut violated_conditions = vec![];
    if evaluations.iter().any(|item| item.result == EvaluationValue::False) {
        let condition = requirement.acceptance_criteria.first().cloned().ok_or(ConformanceError::MissingAcceptanceCriterion)?;
        violated_conditions.push(condition); status = ConformanceStatus::NonConformant;
    } else if evaluations.iter().any(|item| item.result == EvaluationValue::Blocked) { status = ConformanceStatus::Blocked; }
    else if evaluations.iter().any(|item| item.result == EvaluationValue::Unknown) { status = ConformanceStatus::Unknown; }
    Ok(ConformanceResult { requirement_ref: requirement.requirement_id.clone(), status,
        evaluation_refs: evaluations.iter().map(|item| item.evaluation_id.clone()).collect(), evidence_refs,
        violated_conditions, rationale_codes: vec![], content_hash: ContentHash::zero() })
}
''',
        "src/conformance/report.rs": '''use super::oracle::OracleResult;
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConformanceReport { pub profile_id: String, pub implementation_id: String, pub vector_identity: String, pub results: Vec<OracleResult>, pub executed_at: String, pub harness_version: String }
''',
        "src/conformance/harness.rs": '''use super::{oracle::{compare, OracleResult}, vectors::TestVector};
pub fn run_conformance<F>(vectors: &[TestVector], operation: F) -> Vec<OracleResult> where F: Fn(&TestVector) -> String { vectors.iter().map(|vector| compare(vector, operation(vector))).collect() }
''',
        "tests/golden.rs": '''use v14_7_runtime::domain::evaluation::{EmptyMandatoryAction, EvaluationValue};
use v14_7_runtime::evaluation::aggregate::aggregate;
#[test] fn false_dominates_true() { assert_eq!(aggregate(&[EvaluationValue::True, EvaluationValue::False], EmptyMandatoryAction::Deny).unwrap(), EvaluationValue::False); }
#[test] fn empty_action_is_explicit() { assert_eq!(aggregate(&[], EmptyMandatoryAction::Deny).unwrap(), EvaluationValue::False); }
''',
        "tests/negative.rs": '''use v14_7_runtime::RawSubject;
use v14_7_runtime::validation::structural::validate;
#[test] fn empty_subject_is_rejected() { assert!(validate(RawSubject { subject_ref: String::new(), payload: String::new() }).is_err()); }
''',
        "tests/boundary.rs": '''use v14_7_runtime::RawSubject;
use v14_7_runtime::validation::structural::validate;
#[test] fn raw_requires_validation() { let validated = validate(RawSubject { subject_ref: "subject".into(), payload: "body".into() }).unwrap(); assert_eq!(validated.subject_ref(), "subject"); }
''',
        "tests/property.rs": '''use std::collections::BTreeMap;
use v14_7_runtime::identity::canonical::CanonicalSerialize;
#[test] fn canonical_order_is_deterministic() { let mut left = BTreeMap::new(); left.insert("b".into(), "2".into()); left.insert("a".into(), "1".into()); let mut right = BTreeMap::new(); right.insert("a".into(), "1".into()); right.insert("b".into(), "2".into()); assert_eq!(left.canonical_bytes().unwrap(), right.canonical_bytes().unwrap()); }
''',
    }
    return files
