#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ValidationStatus { Valid,Invalid,Blocked,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum EvaluationValue { True,False,Unknown,Blocked,Invalid }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ConformanceStatus { Conformant,PartiallyConformant,NonConformant,Unverified,Blocked,NotApplicable,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum CertificateLifecycle { Draft,Issued,Revoked,Superseded,Expired,Cancelled }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum CertificateValidity { Valid,Invalid,NotYetValid,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ReleaseEligibility { Eligible,Ineligible,Blocked,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum AuthorizationStatus { Authorized,Refused,Blocked,Unknown,Invalid }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ReleaseDecisionStatus { Approved,Rejected,Blocked,Deferred }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ReleaseExecutionStatus { NotStarted,Started,Succeeded,Failed,Cancelled,RolledBack }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum PostReleaseVerificationStatus { NotStarted,InProgress,Passed,Failed,Inconclusive,Blocked,Invalid }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ReuseStatus { Reusable,NotReusable,Blocked,Unknown,Invalid }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum AuthorityStatus { Active,Suspended,Revoked,Expired,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum AuthorityQualificationStatus { Qualified,NotQualified,Blocked,Unknown,Invalid }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum RequirementLifecycle { Proposed,Draft,Active,Deprecated,Superseded,Retired }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum FindingStatus { Open,Triaged,RootCauseIdentified,RemediationPlanned,RemediationInProgress,ReadyForReverification,ReverificationInProgress,Resolved,Waived,Rejected,Closed }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum RemediationStatus { Planned,Approved,InProgress,Blocked,ReadyForVerification,Verified,Failed,Cancelled,Superseded }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum EventValidationStatus { Valid,Invalid,Blocked,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum EventCommitStatus { Pending,Committed,Rejected }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum ProjectionStatus { Current,Replaying,Stale,Invalid,Blocked,Unknown }
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum NormativeStrength { Must,MustNot,Should,ShouldNot,May }
